'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Accessi
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Operatori As Nullable(Of Decimal)
    Public Property dateDataOraLogin As Nullable(Of Date)
    Public Property dateDataOraLogout As Nullable(Of Date)
    Public Property strNomePostazioneDiAccesso As String

    Public Overridable Property Anag_Operatori As Anag_Operatori

End Class
