'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Ricette
    Public Property KeyId As Decimal
    Public Property intTipoRicetta As Short
    Public Property strCodice As String
    Public Property KeyIdAnag_Reparti As Nullable(Of Decimal)
    Public Property strDescrizione As String
    Public Property intQuantita As Nullable(Of Decimal)
    Public Property dblCostoLavorazione As Nullable(Of Double)
    Public Property dateDataOra As Nullable(Of Date)
    Public Property bitCalcolaInAutomatico As Nullable(Of Boolean)
    Public Property bitMultiEtichettatura As Nullable(Of Boolean)
    Public Property intNumEtichette As Nullable(Of Decimal)
    Public Property intContenutoEtichetta As Nullable(Of Decimal)
    Public Property intPorzioniProdotte As Nullable(Of Decimal)
    Public Property intTipoScomposizione As Short
    Public Property bitEliminato As Nullable(Of Boolean)

    Public Overridable Property Anag_Reparti As Anag_Reparti
    Public Overridable Property Anag_Ricette_AnagArticoliFiniti As ICollection(Of Anag_Ricette_AnagArticoliFiniti) = New HashSet(Of Anag_Ricette_AnagArticoliFiniti)
    Public Overridable Property Anag_RicetteDettagli As ICollection(Of Anag_RicetteDettagli) = New HashSet(Of Anag_RicetteDettagli)
    Public Overridable Property Anag_RicetteDettagli1 As ICollection(Of Anag_RicetteDettagli) = New HashSet(Of Anag_RicetteDettagli)
    Public Overridable Property Anag_RicetteImballi As ICollection(Of Anag_RicetteImballi) = New HashSet(Of Anag_RicetteImballi)
    Public Overridable Property MovimentiMagazzino As ICollection(Of MovimentiMagazzino) = New HashSet(Of MovimentiMagazzino)
    Public Overridable Property Progressivi As ICollection(Of Progressivi) = New HashSet(Of Progressivi)

End Class
