'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_TipoDocumento
    Public Property codeId As Decimal
    Public Property strCodice As String
    Public Property strDescrizione As String

    Public Overridable Property Anag_Fornitori As ICollection(Of Anag_Fornitori) = New HashSet(Of Anag_Fornitori)
    Public Overridable Property Conferimenti As ICollection(Of Conferimenti) = New HashSet(Of Conferimenti)
    Public Overridable Property MovimentiMagazzino As ICollection(Of MovimentiMagazzino) = New HashSet(Of MovimentiMagazzino)
    Public Overridable Property Sezionali As ICollection(Of Sezionali) = New HashSet(Of Sezionali)

End Class
