'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_ArticoliConfezionamenti
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property KeyIdAnag_Confezionamenti As Decimal
    Public Property intGiorniScadenza As Nullable(Of Decimal)

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Confezionamenti As Anag_Confezionamenti
    Public Overridable Property Anag_Lavorazioni_Sezionamento As ICollection(Of Anag_Lavorazioni_Sezionamento) = New HashSet(Of Anag_Lavorazioni_Sezionamento)
    Public Overridable Property Anag_Ricette_AnagArticoliFiniti As ICollection(Of Anag_Ricette_AnagArticoliFiniti) = New HashSet(Of Anag_Ricette_AnagArticoliFiniti)
    Public Overridable Property LavorazioniFasi_Ricette As ICollection(Of LavorazioniFasi_Ricette) = New HashSet(Of LavorazioniFasi_Ricette)
    Public Overridable Property LavorazioniFasi_Sezionamento As ICollection(Of LavorazioniFasi_Sezionamento) = New HashSet(Of LavorazioniFasi_Sezionamento)

End Class
