'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Tipo_Barcode
    Public Property KeyId As Decimal
    Public Property descTipoBarcode As String

    Public Overridable Property Anag_ArticoliBarcode As ICollection(Of Anag_ArticoliBarcode) = New HashSet(Of Anag_ArticoliBarcode)

End Class
