'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Serbatoi
    Public Property KeyId As Decimal
    Public Property codePv As Short
    Public Property strCodice As String
    Public Property strDescrizione As String
    Public Property dblCapMaxLitri As Double
    Public Property KeyIdAnag_Bilance As Nullable(Of Decimal)
    Public Property bitEliminato As Boolean
    Public Property KeyIdAnag_Magazzini As Nullable(Of Decimal)
    Public Property KeyIdAnag_Plc As Nullable(Of Decimal)
    Public Property KeyIdAnag_Celle As Decimal
    Public Property code_Plc As Nullable(Of Short)
    Public Property intTipo As Short

    Public Overridable Property Anag_Bilance As Anag_Bilance
    Public Overridable Property Anag_Celle As Anag_Celle
    Public Overridable Property Anag_Magazzini As Anag_Magazzini
    Public Overridable Property Anag_Plc As Anag_Plc
    Public Overridable Property Anag_Pv As Anag_Pv
    Public Overridable Property Conferimenti As ICollection(Of Conferimenti) = New HashSet(Of Conferimenti)
    Public Overridable Property Contenitori As ICollection(Of Contenitori) = New HashSet(Of Contenitori)
    Public Overridable Property Storico_PesiPlc As ICollection(Of Storico_PesiPlc) = New HashSet(Of Storico_PesiPlc)
    Public Overridable Property tmpConferimentiFluidi As ICollection(Of tmpConferimentiFluidi) = New HashSet(Of tmpConferimentiFluidi)
    Public Overridable Property tmpConfigConferimentiFluidiDettagli As ICollection(Of tmpConfigConferimentiFluidiDettagli) = New HashSet(Of tmpConfigConferimentiFluidiDettagli)

End Class
