'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_ConfezionamentiConfig_Layout
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_ConfezionamentiConfig As Decimal
    Public Property strNomeLayoutEtik As String

    Public Overridable Property Anag_ConfezionamentiConfig As Anag_ConfezionamentiConfig

End Class
