'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Stampanti
    Public Property KeyId As Decimal
    Public Property strDescrizione As String
    Public Property strIp As String
    Public Property intTipo As Short
    Public Property bitStampanteLocale As Boolean
    Public Property bitEliminato As Boolean

    Public Overridable Property Anag_Lavorazioni_Confezionamenti As ICollection(Of Anag_Lavorazioni_Confezionamenti) = New HashSet(Of Anag_Lavorazioni_Confezionamenti)
    Public Overridable Property Anag_Lavorazioni_InsacchiArticoliInOut As ICollection(Of Anag_Lavorazioni_InsacchiArticoliInOut) = New HashSet(Of Anag_Lavorazioni_InsacchiArticoliInOut)
    Public Overridable Property Anag_Lavorazioni_InsacchiArticoliInOut1 As ICollection(Of Anag_Lavorazioni_InsacchiArticoliInOut) = New HashSet(Of Anag_Lavorazioni_InsacchiArticoliInOut)
    Public Overridable Property Anag_Lavorazioni_Sezionamento As ICollection(Of Anag_Lavorazioni_Sezionamento) = New HashSet(Of Anag_Lavorazioni_Sezionamento)
    Public Overridable Property Anag_Lavorazioni_Vasche As ICollection(Of Anag_Lavorazioni_Vasche) = New HashSet(Of Anag_Lavorazioni_Vasche)
    Public Overridable Property CartonePalletsConfig As ICollection(Of CartonePalletsConfig) = New HashSet(Of CartonePalletsConfig)
    Public Overridable Property CartonePalletsConfig1 As ICollection(Of CartonePalletsConfig) = New HashSet(Of CartonePalletsConfig)
    Public Overridable Property CartonePalletsConfig2 As ICollection(Of CartonePalletsConfig) = New HashSet(Of CartonePalletsConfig)
    Public Overridable Property PoolDiStampa As ICollection(Of PoolDiStampa) = New HashSet(Of PoolDiStampa)

End Class
