'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Magazzini
    Public Property KeyId As Decimal
    Public Property codePv As Short
    Public Property strCodice As String
    Public Property strDescrizione As String
    Public Property bitEliminato As Boolean
    Public Property bitScarica As Boolean
    Public Property bitMagazzinoEsterno As Boolean
    Public Property KeyIdSezionaliDefaultTrasfInterni As Nullable(Of Decimal)

    Public Overridable Property Anag_Celle As ICollection(Of Anag_Celle) = New HashSet(Of Anag_Celle)
    Public Overridable Property Anag_Clienti As ICollection(Of Anag_Clienti) = New HashSet(Of Anag_Clienti)
    Public Overridable Property Anag_Fornitori As ICollection(Of Anag_Fornitori) = New HashSet(Of Anag_Fornitori)
    Public Overridable Property Anag_Lavorazioni As ICollection(Of Anag_Lavorazioni) = New HashSet(Of Anag_Lavorazioni)
    Public Overridable Property Anag_LavorazioniComplete As ICollection(Of Anag_LavorazioniComplete) = New HashSet(Of Anag_LavorazioniComplete)
    Public Overridable Property Anag_Pv As Anag_Pv
    Public Overridable Property Anag_MagazziniAnag_CausaliMagazzino As ICollection(Of Anag_MagazziniAnag_CausaliMagazzino) = New HashSet(Of Anag_MagazziniAnag_CausaliMagazzino)
    Public Overridable Property Anag_Serbatoi As ICollection(Of Anag_Serbatoi) = New HashSet(Of Anag_Serbatoi)
    Public Overridable Property DdtAcquisto As ICollection(Of DdtAcquisto) = New HashSet(Of DdtAcquisto)
    Public Overridable Property DdtAcquisto1 As ICollection(Of DdtAcquisto) = New HashSet(Of DdtAcquisto)
    Public Overridable Property tmpConferimentiFluidi As ICollection(Of tmpConferimentiFluidi) = New HashSet(Of tmpConferimentiFluidi)
    Public Overridable Property tmpConferimentiFluidi1 As ICollection(Of tmpConferimentiFluidi) = New HashSet(Of tmpConferimentiFluidi)
    Public Overridable Property TrasferimentoInterno As ICollection(Of TrasferimentoInterno) = New HashSet(Of TrasferimentoInterno)
    Public Overridable Property TrasferimentoInterno1 As ICollection(Of TrasferimentoInterno) = New HashSet(Of TrasferimentoInterno)

End Class
