'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Gm
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Reparti As Decimal
    Public Property strCodice As String
    Public Property strDescrizione As String
    Public Property KeyIdAnag_GmPadre As Nullable(Of Decimal)
    Public Property KeyIdCE As Nullable(Of Decimal)
    Public Property KeyIdAnag_Iva As Nullable(Of Decimal)

    Public Overridable Property Anag_Articoli As ICollection(Of Anag_Articoli) = New HashSet(Of Anag_Articoli)
    Public Overridable Property Anag_Gm1 As ICollection(Of Anag_Gm) = New HashSet(Of Anag_Gm)
    Public Overridable Property Anag_Gm2 As Anag_Gm
    Public Overridable Property Anag_IVA As Anag_IVA
    Public Overridable Property Anag_Reparti As Anag_Reparti

End Class
