'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_LineaArticoliIngresso
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Linea As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property bitEliminato As Boolean

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Linea As Anag_Linea
    Public Overridable Property Anag_LineaArticoliIngresso_Sezionamenti As ICollection(Of Anag_LineaArticoliIngresso_Sezionamenti) = New HashSet(Of Anag_LineaArticoliIngresso_Sezionamenti)

End Class
