'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Lavorazioni
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Reparti As Nullable(Of Decimal)
    Public Property KeyIdAnag_LavorazioniTipiLav As Nullable(Of Decimal)
    Public Property strCodiceLavorazione As String
    Public Property strDescrizione As String
    Public Property bitEliminato As Boolean
    Public Property KeyIdAnag_Magazzini As Nullable(Of Decimal)

    Public Overridable Property Anag_Clienti_Anag_Lavorazioni As ICollection(Of Anag_Clienti_Anag_Lavorazioni) = New HashSet(Of Anag_Clienti_Anag_Lavorazioni)
    Public Overridable Property Anag_LavorazioniTipiLav As Anag_LavorazioniTipiLav
    Public Overridable Property Anag_Magazzini As Anag_Magazzini
    Public Overridable Property Anag_Reparti As Anag_Reparti
    Public Overridable Property Anag_Lavorazioni_ArtOutPerAltreLav As ICollection(Of Anag_Lavorazioni_ArtOutPerAltreLav) = New HashSet(Of Anag_Lavorazioni_ArtOutPerAltreLav)
    Public Overridable Property Anag_Lavorazioni_Confezionamenti As ICollection(Of Anag_Lavorazioni_Confezionamenti) = New HashSet(Of Anag_Lavorazioni_Confezionamenti)
    Public Overridable Property Anag_Lavorazioni_ConfSezionamento As ICollection(Of Anag_Lavorazioni_ConfSezionamento) = New HashSet(Of Anag_Lavorazioni_ConfSezionamento)
    Public Overridable Property Anag_Lavorazioni_ContSezionamento As ICollection(Of Anag_Lavorazioni_ContSezionamento) = New HashSet(Of Anag_Lavorazioni_ContSezionamento)
    Public Overridable Property Anag_Lavorazioni_Costi As ICollection(Of Anag_Lavorazioni_Costi) = New HashSet(Of Anag_Lavorazioni_Costi)
    Public Overridable Property Anag_Lavorazioni_Destinazione As ICollection(Of Anag_Lavorazioni_Destinazione) = New HashSet(Of Anag_Lavorazioni_Destinazione)
    Public Overridable Property Anag_Lavorazioni_Etichettatura As ICollection(Of Anag_Lavorazioni_Etichettatura) = New HashSet(Of Anag_Lavorazioni_Etichettatura)
    Public Overridable Property Anag_Lavorazioni_Insacchi As ICollection(Of Anag_Lavorazioni_Insacchi) = New HashSet(Of Anag_Lavorazioni_Insacchi)
    Public Overridable Property Anag_Lavorazioni_SdlSezionamento As ICollection(Of Anag_Lavorazioni_SdlSezionamento) = New HashSet(Of Anag_Lavorazioni_SdlSezionamento)
    Public Overridable Property Anag_Lavorazioni_Sezionamento As ICollection(Of Anag_Lavorazioni_Sezionamento) = New HashSet(Of Anag_Lavorazioni_Sezionamento)
    Public Overridable Property Anag_Lavorazioni_Vasche As ICollection(Of Anag_Lavorazioni_Vasche) = New HashSet(Of Anag_Lavorazioni_Vasche)
    Public Overridable Property Anag_LavorazioniCompleteDettagli As ICollection(Of Anag_LavorazioniCompleteDettagli) = New HashSet(Of Anag_LavorazioniCompleteDettagli)
    Public Overridable Property Anag_LineaArticoliIngresso_Sezionamenti As ICollection(Of Anag_LineaArticoliIngresso_Sezionamenti) = New HashSet(Of Anag_LineaArticoliIngresso_Sezionamenti)
    Public Overridable Property LavorazioniFasiCustom_Dettagli As ICollection(Of LavorazioniFasiCustom_Dettagli) = New HashSet(Of LavorazioniFasiCustom_Dettagli)

End Class
