'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Celle
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Magazzini As Nullable(Of Decimal)
    Public Property codePv As Nullable(Of Short)
    Public Property KeyIdAnag_Reparti As Decimal
    Public Property strCodice As String
    Public Property strDescrizione As String
    Public Property bitDaLavorazione As Nullable(Of Boolean)
    Public Property bitDiVendita As Nullable(Of Boolean)
    Public Property bitBancoTakeAway As Nullable(Of Boolean)

    Public Overridable Property Anag_Articoli_InCelleLavorazione As ICollection(Of Anag_Articoli_InCelleLavorazione) = New HashSet(Of Anag_Articoli_InCelleLavorazione)
    Public Overridable Property Anag_Magazzini As Anag_Magazzini
    Public Overridable Property Anag_Pv As Anag_Pv
    Public Overridable Property Anag_Reparti As Anag_Reparti
    Public Overridable Property Anag_Celle_Aree As ICollection(Of Anag_Celle_Aree) = New HashSet(Of Anag_Celle_Aree)
    Public Overridable Property Anag_Serbatoi As ICollection(Of Anag_Serbatoi) = New HashSet(Of Anag_Serbatoi)
    Public Overridable Property Conferimenti As ICollection(Of Conferimenti) = New HashSet(Of Conferimenti)
    Public Overridable Property Contenitori As ICollection(Of Contenitori) = New HashSet(Of Contenitori)
    Public Overridable Property InAreaLavorazione As ICollection(Of InAreaLavorazione) = New HashSet(Of InAreaLavorazione)
    Public Overridable Property InVendita As ICollection(Of InVendita) = New HashSet(Of InVendita)
    Public Overridable Property LavorazioniFasi_ConfezionamentoD As ICollection(Of LavorazioniFasi_ConfezionamentoD) = New HashSet(Of LavorazioniFasi_ConfezionamentoD)
    Public Overridable Property LavorazioniFasi_Destinazione As ICollection(Of LavorazioniFasi_Destinazione) = New HashSet(Of LavorazioniFasi_Destinazione)
    Public Overridable Property LavorazioniFasi_Impasti As ICollection(Of LavorazioniFasi_Impasti) = New HashSet(Of LavorazioniFasi_Impasti)
    Public Overridable Property LavorazioniFasi_Insacco As ICollection(Of LavorazioniFasi_Insacco) = New HashSet(Of LavorazioniFasi_Insacco)
    Public Overridable Property LavorazioniFasi_Ricette As ICollection(Of LavorazioniFasi_Ricette) = New HashSet(Of LavorazioniFasi_Ricette)
    Public Overridable Property LavorazioniFasi_VascheArtOut As ICollection(Of LavorazioniFasi_VascheArtOut) = New HashSet(Of LavorazioniFasi_VascheArtOut)
    Public Overridable Property Listini_Associazione As ICollection(Of Listini_Associazione) = New HashSet(Of Listini_Associazione)
    Public Overridable Property MovimentiMagazzino As ICollection(Of MovimentiMagazzino) = New HashSet(Of MovimentiMagazzino)
    Public Overridable Property Sezionamenti As ICollection(Of Sezionamenti) = New HashSet(Of Sezionamenti)
    Public Overridable Property Totalizzazione As ICollection(Of Totalizzazione) = New HashSet(Of Totalizzazione)

End Class
