'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Media
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property imgImage As Byte()

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property ListiniDettagli_Media As ICollection(Of ListiniDettagli_Media) = New HashSet(Of ListiniDettagli_Media)

End Class
