'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Tare
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Reparti As Decimal
    Public Property strDescrizione As String
    Public Property intValoreInGrammi As Decimal
    Public Property bitTaraVeloce As Boolean
    Public Property KeyIdCE As Nullable(Of Decimal)

    Public Overridable Property Anag_Articoli As ICollection(Of Anag_Articoli) = New HashSet(Of Anag_Articoli)
    Public Overridable Property Anag_Reparti As Anag_Reparti
    Public Overridable Property Contenitori As ICollection(Of Contenitori) = New HashSet(Of Contenitori)
    Public Overridable Property InParzializzazione_Esecuzione As ICollection(Of InParzializzazione_Esecuzione) = New HashSet(Of InParzializzazione_Esecuzione)
    Public Overridable Property LavorazioniFasi_Ricette As ICollection(Of LavorazioniFasi_Ricette) = New HashSet(Of LavorazioniFasi_Ricette)
    Public Overridable Property Sezionamenti As ICollection(Of Sezionamenti) = New HashSet(Of Sezionamenti)

End Class
