'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Clienti_ListiniArticoli
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Clienti_Listini As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property dblPrezzo As Double
    Public Property KeyIdAnag_Um As Decimal
    Public Property strMascheraBarcode As String

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Clienti_Listini As Anag_Clienti_Listini
    Public Overridable Property Anag_Um As Anag_Um

End Class
