'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Confezionamenti
    Public Property KeyId As Decimal
    Public Property strDescrizione As String

    Public Overridable Property Anag_ArticoliConfezionamenti As ICollection(Of Anag_ArticoliConfezionamenti) = New HashSet(Of Anag_ArticoliConfezionamenti)
    Public Overridable Property Anag_Clienti_LayoutEtichette As ICollection(Of Anag_Clienti_LayoutEtichette) = New HashSet(Of Anag_Clienti_LayoutEtichette)
    Public Overridable Property Anag_ConfezionamentiConfig As ICollection(Of Anag_ConfezionamentiConfig) = New HashSet(Of Anag_ConfezionamentiConfig)
    Public Overridable Property Anag_Lavorazioni_Confezionamenti As ICollection(Of Anag_Lavorazioni_Confezionamenti) = New HashSet(Of Anag_Lavorazioni_Confezionamenti)
    Public Overridable Property Anag_Lavorazioni_Etichettatura As ICollection(Of Anag_Lavorazioni_Etichettatura) = New HashSet(Of Anag_Lavorazioni_Etichettatura)

End Class
