'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Lav_SezImb
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Lavorazioni_Sezionamento As Nullable(Of Decimal)
    Public Property KeyIdAnag_ArticoliImballo As Nullable(Of Decimal)
    Public Property strCodImballo As String

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Lavorazioni_Sezionamento As Anag_Lavorazioni_Sezionamento
    Public Overridable Property SezionamentiImballi As ICollection(Of SezionamentiImballi) = New HashSet(Of SezionamentiImballi)

End Class
