'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_ArticoliBarcode
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property Barcode As String
    Public Property KeyIdAnag_tipo_barcode As Decimal

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Tipo_Barcode As Anag_Tipo_Barcode
    Public Overridable Property InAreaLavorazione_ContenitoriRiutilizzabili As ICollection(Of InAreaLavorazione_ContenitoriRiutilizzabili) = New HashSet(Of InAreaLavorazione_ContenitoriRiutilizzabili)
    Public Overridable Property InParzializzazione_ContenitoriRiutilizzabili As ICollection(Of InParzializzazione_ContenitoriRiutilizzabili) = New HashSet(Of InParzializzazione_ContenitoriRiutilizzabili)

End Class
