'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Lavorazioni_Confezionamenti
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Lavorazioni As Decimal
    Public Property KeyIdAnag_Confezionamenti As Decimal
    Public Property strNomeLayoutEtik As String
    Public Property intGiorniScadenza As Nullable(Of Decimal)
    Public Property bitEliminato As Boolean
    Public Property bitStampaAutomatica As Nullable(Of Boolean)
    Public Property KeyIdAnag_Stampanti As Nullable(Of Decimal)
    Public Property bitConfezionamentoAutomatico As Nullable(Of Boolean)
    Public Property bitConfezionamentoFasi As Nullable(Of Boolean)

    Public Overridable Property Anag_Confezionamenti As Anag_Confezionamenti
    Public Overridable Property Anag_Lavorazioni As Anag_Lavorazioni
    Public Overridable Property Anag_Stampanti As Anag_Stampanti
    Public Overridable Property Anag_Lavorazioni_ConfezionamentiArticoliInOut As ICollection(Of Anag_Lavorazioni_ConfezionamentiArticoliInOut) = New HashSet(Of Anag_Lavorazioni_ConfezionamentiArticoliInOut)

End Class
