'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_RicetteDettagli
    Public Property KeyId As Decimal
    Public Property KeyId_AnagRicette As Nullable(Of Decimal)
    Public Property KeyIdAnag_Articoli As Nullable(Of Decimal)
    Public Property KeyIdAnag_RicetteMisPrep As Nullable(Of Decimal)
    Public Property intQuantita As Nullable(Of Decimal)
    Public Property bitModificabile As Nullable(Of Boolean)
    Public Property bitFacoltativo As Nullable(Of Boolean)
    Public Property bitPesoObbligatorio As Nullable(Of Boolean)
    Public Property bitEliminato As Nullable(Of Boolean)

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Ricette As Anag_Ricette
    Public Overridable Property Anag_Ricette1 As Anag_Ricette
    Public Overridable Property Anag_RicetteDettagli_ListaModificabili As ICollection(Of Anag_RicetteDettagli_ListaModificabili) = New HashSet(Of Anag_RicetteDettagli_ListaModificabili)
    Public Overridable Property LavorazioniFasi_Ricette_Eseguite As ICollection(Of LavorazioniFasi_Ricette_Eseguite) = New HashSet(Of LavorazioniFasi_Ricette_Eseguite)

End Class
