'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_ConfezionamentiConfig
    Public Property KeyId As Decimal
    Public Property codePv As Short
    Public Property KeyIdAnag_Reparti As Decimal
    Public Property KeyIdAnag_Confezionamenti As Decimal
    Public Property strDescrizione As String
    Public Property dblCostoLav As Nullable(Of Double)
    Public Property strNomeLayoutEtik As String
    Public Property dblCostoEtik As Nullable(Of Double)
    Public Property intGiorniScadenza As Nullable(Of Decimal)
    Public Property bitEliminato As Boolean
    Public Property bitGenerico As Boolean

    Public Overridable Property Anag_Confezionamenti As Anag_Confezionamenti
    Public Overridable Property Anag_Pv As Anag_Pv
    Public Overridable Property Anag_Reparti As Anag_Reparti
    Public Overridable Property Anag_ConfezionamentiConfig_Layout As ICollection(Of Anag_ConfezionamentiConfig_Layout) = New HashSet(Of Anag_ConfezionamentiConfig_Layout)
    Public Overridable Property Anag_ConfezionamentiConfigArtInOut As ICollection(Of Anag_ConfezionamentiConfigArtInOut) = New HashSet(Of Anag_ConfezionamentiConfigArtInOut)
    Public Overridable Property Anag_ConfezionamentiConfigImb As ICollection(Of Anag_ConfezionamentiConfigImb) = New HashSet(Of Anag_ConfezionamentiConfigImb)

End Class
