'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Bilance
    Public Property KeyId As Decimal
    Public Property codePv As Short
    Public Property strCodice As String
    Public Property strNomeBilancia As String
    Public Property strIp As String
    Public Property intPorta As Short
    Public Property intPortaUdpServer As Nullable(Of Short)
    Public Property strIpServer As String
    Public Property intModello As Short
    Public Property intDividiPesoPer As Nullable(Of Short)

    Public Overridable Property Anag_Pv As Anag_Pv
    Public Overridable Property Anag_Serbatoi As ICollection(Of Anag_Serbatoi) = New HashSet(Of Anag_Serbatoi)
    Public Overridable Property tmpUscitaMerceManuale As ICollection(Of tmpUscitaMerceManuale) = New HashSet(Of tmpUscitaMerceManuale)

End Class
