'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Lavorazioni_ConfezionamentiArticoliInOut
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Lavorazioni_Confezionamenti As Decimal
    Public Property bitIngresso As Boolean
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property bitEliminato As Boolean
    Public Property strPathLayoutCarrello As String
    Public Property bitAccorpaQtaInEtichetta As Boolean

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Lavorazioni_Confezionamenti As Anag_Lavorazioni_Confezionamenti
    Public Overridable Property Anag_Lavorazioni_ConfezionamentiArticoliInOutImballi As ICollection(Of Anag_Lavorazioni_ConfezionamentiArticoliInOutImballi) = New HashSet(Of Anag_Lavorazioni_ConfezionamentiArticoliInOutImballi)

End Class
