'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Lavorazioni_ImpastiAdditiviQtaVariabili
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Lavorazioni_ImpastiAdditivi As Decimal
    Public Property dblDa As Double
    Public Property dblA As Double
    Public Property dblQuantita As Double

    Public Overridable Property Anag_Lavorazioni_ImpastiAdditivi As Anag_Lavorazioni_ImpastiAdditivi

End Class
