'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Clienti_Listini
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Clienti As Decimal
    Public Property strDescrizione As String
    Public Property bitActive As Boolean
    Public Property dateDa As Nullable(Of Date)
    Public Property dateA As Nullable(Of Date)

    Public Overridable Property Anag_Clienti As Anag_Clienti
    Public Overridable Property Anag_Clienti_ListiniArticoli As ICollection(Of Anag_Clienti_ListiniArticoli) = New HashSet(Of Anag_Clienti_ListiniArticoli)

End Class
