'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Riga0
    Public Property KeyId As Decimal
    Public Property strDescrizione As String
    Public Property KeyIdCE As Nullable(Of Decimal)

    Public Overridable Property MaschereTr_Campi As ICollection(Of MaschereTr_Campi) = New HashSet(Of MaschereTr_Campi)
    Public Overridable Property TracciabilitaAddizionale_Dettagli As ICollection(Of TracciabilitaAddizionale_Dettagli) = New HashSet(Of TracciabilitaAddizionale_Dettagli)
    Public Overridable Property Traduzioni_Anag_Riga0 As ICollection(Of Traduzioni_Anag_Riga0) = New HashSet(Of Traduzioni_Anag_Riga0)

End Class
