'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Lavorazioni_InsacchiArticoliInOut
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Lavorazioni_Insacchi As Decimal
    Public Property bitIngresso As Boolean
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property intNumPz As Nullable(Of Integer)
    Public Property dblPesoSingoloPz As Nullable(Of Double)
    Public Property bitEliminato As Boolean
    Public Property dblPesoMedioConImballo As Nullable(Of Double)
    Public Property dblResa As Nullable(Of Double)
    Public Property bitPesaCarrello As Boolean
    Public Property dblTaraCarrello As Nullable(Of Double)
    Public Property dblTolleranzaCarrello As Nullable(Of Double)
    Public Property strPathLayoutCarrello As String
    Public Property KeyIdAnag_StampantiCarrello As Nullable(Of Decimal)
    Public Property bitStampaAutoCarrello As Boolean
    Public Property strPathLayoutEtichetta As String
    Public Property KeyIdAnag_StampantiEtichetta As Nullable(Of Decimal)
    Public Property bitStampaAutoEtichetta As Boolean

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Lavorazioni_Insacchi As Anag_Lavorazioni_Insacchi
    Public Overridable Property Anag_Stampanti As Anag_Stampanti
    Public Overridable Property Anag_Stampanti1 As Anag_Stampanti
    Public Overridable Property Anag_Lavorazioni_InsacchiArticoliInOutImballi As ICollection(Of Anag_Lavorazioni_InsacchiArticoliInOutImballi) = New HashSet(Of Anag_Lavorazioni_InsacchiArticoliInOutImballi)

End Class
