'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_MiaAzienda
    Public Property KeyId As Decimal
    Public Property strCodice As String
    Public Property strRagioneSociale As String
    Public Property strIndirizzo As String
    Public Property strCap As String
    Public Property strCitta As String
    Public Property strProvincia As String
    Public Property strCodFiscale As String
    Public Property strPIva As String
    Public Property strIndirizzoOperativo As String
    Public Property strCapOperativo As String
    Public Property strCittaOperativo As String
    Public Property strProvinciaOperativo As String
    Public Property strCodiceRegFiscale As String

End Class
