'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_ArticoliConversioneUm
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property dblQuantita1 As Double
    Public Property KeyIdAnag_Um1 As Decimal
    Public Property dblQuantita2 As Double
    Public Property KeyIdAnag_Um2 As Decimal

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Um As Anag_Um
    Public Overridable Property Anag_Um1 As Anag_Um

End Class
