'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_RicetteDettagli_ListaModificabili
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_RicetteDettagli As Nullable(Of Decimal)
    Public Property KeyIdAnag_Articoli As Nullable(Of Decimal)
    Public Property bitEliminato As Nullable(Of Boolean)

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_RicetteDettagli As Anag_RicetteDettagli
    Public Overridable Property LavorazioniFasi_Ricette_Eseguite As ICollection(Of LavorazioniFasi_Ricette_Eseguite) = New HashSet(Of LavorazioniFasi_Ricette_Eseguite)

End Class
