'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Articoli
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Reparti As Decimal
    Public Property KeyIdAnag_Gm As Nullable(Of Decimal)
    Public Property strCodice As String
    Public Property strDescrizione As String
    Public Property strDescrizioneAggiuntiva As String
    Public Property strIngredienti As String
    Public Property strAllergeni As String
    Public Property strValoriNutrizionali As String
    Public Property KeyIdAnag_UmOrdini As Nullable(Of Decimal)
    Public Property KeyIdAnag_Um As Decimal
    Public Property dblPrezzo As Nullable(Of Double)
    Public Property dblPercProvvigione As Nullable(Of Double)
    Public Property strCodiceStatistico As String
    Public Property KeyIdMaschereTr As Nullable(Of Decimal)
    Public Property KeyIdAnag_Tara As Nullable(Of Decimal)
    Public Property bitVariato As Boolean
    Public Property bitEliminato As Boolean
    Public Property KeyIdAnag_Iva As Nullable(Of Decimal)
    Public Property KeyIdCE As Nullable(Of Decimal)
    Public Property KeyIdGW As Nullable(Of Decimal)

    Public Overridable Property Anag_Gm As Anag_Gm
    Public Overridable Property Anag_IVA As Anag_IVA
    Public Overridable Property Anag_Reparti As Anag_Reparti
    Public Overridable Property Anag_Tare As Anag_Tare
    Public Overridable Property Anag_Um As Anag_Um
    Public Overridable Property Anag_Um1 As Anag_Um
    Public Overridable Property Anag_Articoli_InCelleLavorazione As ICollection(Of Anag_Articoli_InCelleLavorazione) = New HashSet(Of Anag_Articoli_InCelleLavorazione)
    Public Overridable Property Anag_Articoli_InCelleLavorazione1 As ICollection(Of Anag_Articoli_InCelleLavorazione) = New HashSet(Of Anag_Articoli_InCelleLavorazione)
    Public Overridable Property MaschereTr As MaschereTr
    Public Overridable Property Anag_ArticoliComposizioneiCasher As ICollection(Of Anag_ArticoliComposizioneiCasher) = New HashSet(Of Anag_ArticoliComposizioneiCasher)
    Public Overridable Property Anag_ArticoliComposizioneiCasher1 As ICollection(Of Anag_ArticoliComposizioneiCasher) = New HashSet(Of Anag_ArticoliComposizioneiCasher)
    Public Overridable Property Anag_ArticoliConfezionamenti As ICollection(Of Anag_ArticoliConfezionamenti) = New HashSet(Of Anag_ArticoliConfezionamenti)
    Public Overridable Property Anag_ArticoliContenitori_Risultati As ICollection(Of Anag_ArticoliContenitori_Risultati) = New HashSet(Of Anag_ArticoliContenitori_Risultati)
    Public Overridable Property Anag_ArticoliContenitori_Risultati1 As ICollection(Of Anag_ArticoliContenitori_Risultati) = New HashSet(Of Anag_ArticoliContenitori_Risultati)
    Public Overridable Property Anag_ArticoliContenitori_Vincoli As ICollection(Of Anag_ArticoliContenitori_Vincoli) = New HashSet(Of Anag_ArticoliContenitori_Vincoli)
    Public Overridable Property Anag_ArticoliContenitori_Vincoli1 As ICollection(Of Anag_ArticoliContenitori_Vincoli) = New HashSet(Of Anag_ArticoliContenitori_Vincoli)
    Public Overridable Property Anag_ArticoliConversioneUm As ICollection(Of Anag_ArticoliConversioneUm) = New HashSet(Of Anag_ArticoliConversioneUm)
    Public Overridable Property Anag_ArticoliDatiAggiuntivi As Anag_ArticoliDatiAggiuntivi
    Public Overridable Property Anag_ArticoliBarcode As ICollection(Of Anag_ArticoliBarcode) = New HashSet(Of Anag_ArticoliBarcode)
    Public Overridable Property Anag_Clienti_ListiniArticoli As ICollection(Of Anag_Clienti_ListiniArticoli) = New HashSet(Of Anag_Clienti_ListiniArticoli)
    Public Overridable Property Anag_ConfezionamentiConfigArtInOut As ICollection(Of Anag_ConfezionamentiConfigArtInOut) = New HashSet(Of Anag_ConfezionamentiConfigArtInOut)
    Public Overridable Property Anag_ConfezionamentiConfigImb As ICollection(Of Anag_ConfezionamentiConfigImb) = New HashSet(Of Anag_ConfezionamentiConfigImb)
    Public Overridable Property Anag_Decodifica_Articoli As ICollection(Of Anag_Decodifica_Articoli) = New HashSet(Of Anag_Decodifica_Articoli)
    Public Overridable Property Anag_Lav_SezImb As ICollection(Of Anag_Lav_SezImb) = New HashSet(Of Anag_Lav_SezImb)
    Public Overridable Property Anag_Lavorazioni_ArtOutPerAltreLav As ICollection(Of Anag_Lavorazioni_ArtOutPerAltreLav) = New HashSet(Of Anag_Lavorazioni_ArtOutPerAltreLav)
    Public Overridable Property Anag_Lavorazioni_ConfezionamentiArticoliInOut As ICollection(Of Anag_Lavorazioni_ConfezionamentiArticoliInOut) = New HashSet(Of Anag_Lavorazioni_ConfezionamentiArticoliInOut)
    Public Overridable Property Anag_Lavorazioni_ConfezionamentiArticoliInOutImballi As ICollection(Of Anag_Lavorazioni_ConfezionamentiArticoliInOutImballi) = New HashSet(Of Anag_Lavorazioni_ConfezionamentiArticoliInOutImballi)
    Public Overridable Property Anag_Lavorazioni_ContSezionamento As ICollection(Of Anag_Lavorazioni_ContSezionamento) = New HashSet(Of Anag_Lavorazioni_ContSezionamento)
    Public Overridable Property Anag_Lavorazioni_Destinazione As ICollection(Of Anag_Lavorazioni_Destinazione) = New HashSet(Of Anag_Lavorazioni_Destinazione)
    Public Overridable Property Anag_Lavorazioni_Destinazione1 As ICollection(Of Anag_Lavorazioni_Destinazione) = New HashSet(Of Anag_Lavorazioni_Destinazione)
    Public Overridable Property Anag_Lavorazioni_EtichettaturaArticoliInOut As ICollection(Of Anag_Lavorazioni_EtichettaturaArticoliInOut) = New HashSet(Of Anag_Lavorazioni_EtichettaturaArticoliInOut)
    Public Overridable Property Anag_Lavorazioni_EtichettaturaArticoliInOutImballi As ICollection(Of Anag_Lavorazioni_EtichettaturaArticoliInOutImballi) = New HashSet(Of Anag_Lavorazioni_EtichettaturaArticoliInOutImballi)
    Public Overridable Property Anag_Lavorazioni_ImpastiAdditivi As ICollection(Of Anag_Lavorazioni_ImpastiAdditivi) = New HashSet(Of Anag_Lavorazioni_ImpastiAdditivi)
    Public Overridable Property Anag_Lavorazioni_ImpastiArticoliInOut As ICollection(Of Anag_Lavorazioni_ImpastiArticoliInOut) = New HashSet(Of Anag_Lavorazioni_ImpastiArticoliInOut)
    Public Overridable Property Anag_Lavorazioni_InsacchiArticoliInOut As ICollection(Of Anag_Lavorazioni_InsacchiArticoliInOut) = New HashSet(Of Anag_Lavorazioni_InsacchiArticoliInOut)
    Public Overridable Property Anag_Lavorazioni_InsacchiArticoliInOutImballi As ICollection(Of Anag_Lavorazioni_InsacchiArticoliInOutImballi) = New HashSet(Of Anag_Lavorazioni_InsacchiArticoliInOutImballi)
    Public Overridable Property Anag_Lavorazioni_SdlSezionamento As ICollection(Of Anag_Lavorazioni_SdlSezionamento) = New HashSet(Of Anag_Lavorazioni_SdlSezionamento)
    Public Overridable Property Anag_Lavorazioni_Sezionamento As ICollection(Of Anag_Lavorazioni_Sezionamento) = New HashSet(Of Anag_Lavorazioni_Sezionamento)
    Public Overridable Property Anag_Lavorazioni_Sezionamento1 As ICollection(Of Anag_Lavorazioni_Sezionamento) = New HashSet(Of Anag_Lavorazioni_Sezionamento)
    Public Overridable Property Anag_Lavorazioni_VascheArticoliInOut As ICollection(Of Anag_Lavorazioni_VascheArticoliInOut) = New HashSet(Of Anag_Lavorazioni_VascheArticoliInOut)
    Public Overridable Property Anag_Lavorazioni_VascheArticoliInOutImballi As ICollection(Of Anag_Lavorazioni_VascheArticoliInOutImballi) = New HashSet(Of Anag_Lavorazioni_VascheArticoliInOutImballi)
    Public Overridable Property Anag_LineaArticoliIngresso As ICollection(Of Anag_LineaArticoliIngresso) = New HashSet(Of Anag_LineaArticoliIngresso)
    Public Overridable Property Anag_Media As ICollection(Of Anag_Media) = New HashSet(Of Anag_Media)
    Public Overridable Property Anag_Ricette_AnagArticoliFiniti As ICollection(Of Anag_Ricette_AnagArticoliFiniti) = New HashSet(Of Anag_Ricette_AnagArticoliFiniti)
    Public Overridable Property Anag_RicetteDettagli As ICollection(Of Anag_RicetteDettagli) = New HashSet(Of Anag_RicetteDettagli)
    Public Overridable Property Anag_RicetteDettagli_ListaModificabili As ICollection(Of Anag_RicetteDettagli_ListaModificabili) = New HashSet(Of Anag_RicetteDettagli_ListaModificabili)
    Public Overridable Property Anag_RicetteImballi As ICollection(Of Anag_RicetteImballi) = New HashSet(Of Anag_RicetteImballi)
    Public Overridable Property CartonePallets_Dettagli As ICollection(Of CartonePallets_Dettagli) = New HashSet(Of CartonePallets_Dettagli)
    Public Overridable Property Conferimenti As ICollection(Of Conferimenti) = New HashSet(Of Conferimenti)
    Public Overridable Property Contenitori As ICollection(Of Contenitori) = New HashSet(Of Contenitori)
    Public Overridable Property DdtAcquisto_Dettagli As ICollection(Of DdtAcquisto_Dettagli) = New HashSet(Of DdtAcquisto_Dettagli)
    Public Overridable Property InVendita As ICollection(Of InVendita) = New HashSet(Of InVendita)
    Public Overridable Property KeyIdArticoliInBilance As ICollection(Of KeyIdArticoliInBilance) = New HashSet(Of KeyIdArticoliInBilance)
    Public Overridable Property KeyIdArticoliInBilance_Plu As ICollection(Of KeyIdArticoliInBilance_Plu) = New HashSet(Of KeyIdArticoliInBilance_Plu)
    Public Overridable Property LavorazioniFasi_ArtOutPerAltreLav As ICollection(Of LavorazioniFasi_ArtOutPerAltreLav) = New HashSet(Of LavorazioniFasi_ArtOutPerAltreLav)
    Public Overridable Property LavorazioniFasi_ConfezionamentiArtOUT As ICollection(Of LavorazioniFasi_ConfezionamentiArtOUT) = New HashSet(Of LavorazioniFasi_ConfezionamentiArtOUT)
    Public Overridable Property LavorazioniFasi_ConfezionamentoDArtOut As ICollection(Of LavorazioniFasi_ConfezionamentoDArtOut) = New HashSet(Of LavorazioniFasi_ConfezionamentoDArtOut)
    Public Overridable Property LavorazioniFasi_ContSezionamento As ICollection(Of LavorazioniFasi_ContSezionamento) = New HashSet(Of LavorazioniFasi_ContSezionamento)
    Public Overridable Property LavorazioniFasi_Destinazione As ICollection(Of LavorazioniFasi_Destinazione) = New HashSet(Of LavorazioniFasi_Destinazione)
    Public Overridable Property LavorazioniFasi_Impasti As ICollection(Of LavorazioniFasi_Impasti) = New HashSet(Of LavorazioniFasi_Impasti)
    Public Overridable Property LavorazioniFasi_ImpastiAdditivi As ICollection(Of LavorazioniFasi_ImpastiAdditivi) = New HashSet(Of LavorazioniFasi_ImpastiAdditivi)
    Public Overridable Property LavorazioniFasi_ImpastiAdditiviLotti As ICollection(Of LavorazioniFasi_ImpastiAdditiviLotti) = New HashSet(Of LavorazioniFasi_ImpastiAdditiviLotti)
    Public Overridable Property LavorazioniFasi_Insacco As ICollection(Of LavorazioniFasi_Insacco) = New HashSet(Of LavorazioniFasi_Insacco)
    Public Overridable Property LavorazioniFasi_InsaccoImballi As ICollection(Of LavorazioniFasi_InsaccoImballi) = New HashSet(Of LavorazioniFasi_InsaccoImballi)
    Public Overridable Property LavorazioniFasi_Ricette As ICollection(Of LavorazioniFasi_Ricette) = New HashSet(Of LavorazioniFasi_Ricette)
    Public Overridable Property LavorazioniFasi_SdlSezionamento As ICollection(Of LavorazioniFasi_SdlSezionamento) = New HashSet(Of LavorazioniFasi_SdlSezionamento)
    Public Overridable Property LavorazioniFasi_Sezionamento As ICollection(Of LavorazioniFasi_Sezionamento) = New HashSet(Of LavorazioniFasi_Sezionamento)
    Public Overridable Property LavorazioniFasi_VascheArtIn As ICollection(Of LavorazioniFasi_VascheArtIn) = New HashSet(Of LavorazioniFasi_VascheArtIn)
    Public Overridable Property LavorazioniFasi_VascheArtOut As ICollection(Of LavorazioniFasi_VascheArtOut) = New HashSet(Of LavorazioniFasi_VascheArtOut)
    Public Overridable Property LavorazioniFasi_VascheFasiSecondarie As ICollection(Of LavorazioniFasi_VascheFasiSecondarie) = New HashSet(Of LavorazioniFasi_VascheFasiSecondarie)
    Public Overridable Property LavorazioniFasi_VascheImballi As ICollection(Of LavorazioniFasi_VascheImballi) = New HashSet(Of LavorazioniFasi_VascheImballi)
    Public Overridable Property LavorazioniFasi_VascheIngredienti As ICollection(Of LavorazioniFasi_VascheIngredienti) = New HashSet(Of LavorazioniFasi_VascheIngredienti)
    Public Overridable Property ListiniDettagli As ICollection(Of ListiniDettagli) = New HashSet(Of ListiniDettagli)
    Public Overridable Property LottiInCucina As ICollection(Of LottiInCucina) = New HashSet(Of LottiInCucina)
    Public Overridable Property LottoUnicoAperto As ICollection(Of LottoUnicoAperto) = New HashSet(Of LottoUnicoAperto)
    Public Overridable Property PreLavorazioniDatiDaSerb As ICollection(Of PreLavorazioniDatiDaSerb) = New HashSet(Of PreLavorazioniDatiDaSerb)
    Public Overridable Property PreLavorazioniDettagli As ICollection(Of PreLavorazioniDettagli) = New HashSet(Of PreLavorazioniDettagli)
    Public Overridable Property Progressivi As ICollection(Of Progressivi) = New HashSet(Of Progressivi)
    Public Overridable Property Sezionamenti As ICollection(Of Sezionamenti) = New HashSet(Of Sezionamenti)
    Public Overridable Property Spedizioni_Dettagli As ICollection(Of Spedizioni_Dettagli) = New HashSet(Of Spedizioni_Dettagli)
    Public Overridable Property Totalizzazione As ICollection(Of Totalizzazione) = New HashSet(Of Totalizzazione)
    Public Overridable Property TransazioniCasse As ICollection(Of TransazioniCasse) = New HashSet(Of TransazioniCasse)
    Public Overridable Property TrasferimentoInterno_Dettagli As ICollection(Of TrasferimentoInterno_Dettagli) = New HashSet(Of TrasferimentoInterno_Dettagli)

End Class
