'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Fornitori
    Public Property keyId As Decimal
    Public Property strCodice As String
    Public Property strRagioneSociale As String
    Public Property strIndirizzo As String
    Public Property strCap As String
    Public Property strCitta As String
    Public Property strProvincia As String
    Public Property strCodFiscale As String
    Public Property strPIva As String
    Public Property strTelefono As String
    Public Property codeTipoImportTrac As Nullable(Of Short)
    Public Property codeIdTipoPagamento As Nullable(Of Short)
    Public Property codeIdLastAnag_TipoDocumento As Nullable(Of Decimal)
    Public Property KeyIdGW As Nullable(Of Decimal)
    Public Property KeyIdAnag_Magazzini As Nullable(Of Decimal)

    Public Overridable Property Anag_ArticoliDatiAggiuntivi As ICollection(Of Anag_ArticoliDatiAggiuntivi) = New HashSet(Of Anag_ArticoliDatiAggiuntivi)
    Public Overridable Property Anag_Decodifica_Articoli As ICollection(Of Anag_Decodifica_Articoli) = New HashSet(Of Anag_Decodifica_Articoli)
    Public Overridable Property Anag_Magazzini As Anag_Magazzini
    Public Overridable Property Anag_TipoDocumento As Anag_TipoDocumento
    Public Overridable Property TipoImportTrac As TipoImportTrac
    Public Overridable Property TipoPagamento As TipoPagamento
    Public Overridable Property Conferimenti As ICollection(Of Conferimenti) = New HashSet(Of Conferimenti)
    Public Overridable Property DdtAcquisto As ICollection(Of DdtAcquisto) = New HashSet(Of DdtAcquisto)
    Public Overridable Property Fatture As ICollection(Of Fatture) = New HashSet(Of Fatture)
    Public Overridable Property ImpSeurop As ICollection(Of ImpSeurop) = New HashSet(Of ImpSeurop)
    Public Overridable Property Listini_Associazione As ICollection(Of Listini_Associazione) = New HashSet(Of Listini_Associazione)
    Public Overridable Property MovimentiMagazzino As ICollection(Of MovimentiMagazzino) = New HashSet(Of MovimentiMagazzino)
    Public Overridable Property Ordini As ICollection(Of Ordini) = New HashSet(Of Ordini)
    Public Overridable Property PrimaNota As ICollection(Of PrimaNota) = New HashSet(Of PrimaNota)

End Class
