'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Lavorazioni_Destinazione_Esecuzione
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Lavorazioni_Destinazione As Nullable(Of Decimal)
    Public Property intOrdine As Nullable(Of Decimal)
    Public Property KeyIdAnag_LavorazioniTipiOp As Nullable(Of Decimal)
    Public Property intDurataInMinuti As Nullable(Of Decimal)

    Public Overridable Property Anag_Lavorazioni_Destinazione As Anag_Lavorazioni_Destinazione
    Public Overridable Property Anag_LavorazioniTipiOp As Anag_LavorazioniTipiOp

End Class
