'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_ArticoliContenitori_Risultati
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property KeyIdAnag_Articoli_exit As Decimal

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Articoli1 As Anag_Articoli

End Class
