'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Clienti_LayoutEtichette
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_LavorazioniTipiLav As Decimal
    Public Property KeyIdAnag_Confezionamenti As Nullable(Of Decimal)
    Public Property KeyIdAnag_Clienti As Nullable(Of Decimal)
    Public Property strNomeLayout As String

    Public Overridable Property Anag_Clienti As Anag_Clienti
    Public Overridable Property Anag_Confezionamenti As Anag_Confezionamenti
    Public Overridable Property Anag_LavorazioniTipiLav As Anag_LavorazioniTipiLav

End Class
