'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Aree
    Public Property KeyId As Decimal
    Public Property strDescrizione As String

    Public Overridable Property LottoUnicoAperto As ICollection(Of LottoUnicoAperto) = New HashSet(Of LottoUnicoAperto)

End Class
