'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_RepartiBilance
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Reparti As Decimal
    Public Property intNumero As Nullable(Of Decimal)
    Public Property strCodice As String
    Public Property strDescrizione As String
    Public Property bitCalcolaPercRicette As Boolean
    Public Property bitTakeAway As Boolean
    Public Property bitSempreInBilancia As Boolean
    Public Property KeyIdCE As Nullable(Of Decimal)

    Public Overridable Property Anag_ArticoliDatiAggiuntivi As ICollection(Of Anag_ArticoliDatiAggiuntivi) = New HashSet(Of Anag_ArticoliDatiAggiuntivi)
    Public Overridable Property Anag_Reparti As Anag_Reparti

End Class
