'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Allevatori
    Public Property KeyId As Decimal
    Public Property strCodice As String
    Public Property strRagioneSociale As String
    Public Property strIndirizzo As String
    Public Property strCap As String
    Public Property strCitta As String
    Public Property strProvincia As String
    Public Property strTelefono As String
    Public Property strNazione As String
    Public Property strNumeroAllevamento As String
    Public Property bitEliminato As Boolean

    Public Overridable Property Ddt_Acquisto_Vivi As ICollection(Of Ddt_Acquisto_Vivi) = New HashSet(Of Ddt_Acquisto_Vivi)

End Class
