'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Filiere
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Reparti As Nullable(Of Decimal)
    Public Property intLivello As Nullable(Of Decimal)
    Public Property strDescrizione As String
    Public Property KeyIdCE As Nullable(Of Decimal)

    Public Overridable Property Anag_Reparti As Anag_Reparti
    Public Overridable Property Conferimenti As ICollection(Of Conferimenti) = New HashSet(Of Conferimenti)
    Public Overridable Property DdtAcquisto_Dettagli As ICollection(Of DdtAcquisto_Dettagli) = New HashSet(Of DdtAcquisto_Dettagli)

End Class
