'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Clienti_Destinazioni
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Clienti As Decimal
    Public Property strCodice As String
    Public Property strDescrizione As String
    Public Property strIndirizzo As String
    Public Property strCap As String
    Public Property strCitta As String
    Public Property strProvincia As String
    Public Property bitMagTraceRepo As Boolean
    Public Property bitMTAggiornatoRepo As Boolean

    Public Overridable Property Anag_Clienti As Anag_Clienti
    Public Overridable Property Anag_Decodifica_Articoli As ICollection(Of Anag_Decodifica_Articoli) = New HashSet(Of Anag_Decodifica_Articoli)
    Public Overridable Property CartonePallets As ICollection(Of CartonePallets) = New HashSet(Of CartonePallets)
    Public Overridable Property Ddt_Acquisto_Vivi As ICollection(Of Ddt_Acquisto_Vivi) = New HashSet(Of Ddt_Acquisto_Vivi)
    Public Overridable Property Fatture As ICollection(Of Fatture) = New HashSet(Of Fatture)
    Public Overridable Property InParzializzazione_Esecuzione As ICollection(Of InParzializzazione_Esecuzione) = New HashSet(Of InParzializzazione_Esecuzione)
    Public Overridable Property LavorazioniFasi_VascheArtOut As ICollection(Of LavorazioniFasi_VascheArtOut) = New HashSet(Of LavorazioniFasi_VascheArtOut)
    Public Overridable Property PrimaNota As ICollection(Of PrimaNota) = New HashSet(Of PrimaNota)
    Public Overridable Property tmpConfigConferimentiFluidi As ICollection(Of tmpConfigConferimentiFluidi) = New HashSet(Of tmpConfigConferimentiFluidi)

End Class
