'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Lavorazioni_Costi
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Lavorazioni As Decimal
    Public Property KeyIdAnag_Costi As Decimal
    Public Property intQta As Short
    Public Property dblCosto As Double
    Public Property bitEliminato As Boolean

    Public Overridable Property Anag_Costi As Anag_Costi
    Public Overridable Property Anag_Lavorazioni As Anag_Lavorazioni

End Class
