'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Lavorazioni_ImpastiAdditivi
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Lavorazioni_Impasti As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property KeyIdAnag_Um As Decimal
    Public Property intTipoAdditivo As Short
    Public Property dblQuantita As Nullable(Of Double)
    Public Property bitCalcolaPercentuale As Boolean
    Public Property bitEliminato As Boolean

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Lavorazioni_Impasti As Anag_Lavorazioni_Impasti
    Public Overridable Property Anag_Um As Anag_Um
    Public Overridable Property Anag_Lavorazioni_ImpastiAdditiviQtaVariabili As ICollection(Of Anag_Lavorazioni_ImpastiAdditiviQtaVariabili) = New HashSet(Of Anag_Lavorazioni_ImpastiAdditiviQtaVariabili)

End Class
