'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Ricette_AnagArticoliFiniti
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Ricette As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property KeyIdAnag_ArticoliConfezionamenti As Nullable(Of Decimal)
    Public Property bitEliminato As Boolean

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_ArticoliConfezionamenti As Anag_ArticoliConfezionamenti
    Public Overridable Property Anag_Ricette As Anag_Ricette

End Class
