'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Linea
    Public Property KeyId As Decimal
    Public Property strCodice As String
    Public Property strDescrizione As String
    Public Property bitEliminato As Boolean

    Public Overridable Property Anag_LineaArticoliIngresso As ICollection(Of Anag_LineaArticoliIngresso) = New HashSet(Of Anag_LineaArticoliIngresso)

End Class
