'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_LavorazioniCompleteDettagli
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_LavorazioniComplete As Decimal
    Public Property KeyIdAnag_Lavorazioni As Decimal
    Public Property intOrdine As Short
    Public Property bitFacoltativa As Boolean

    Public Overridable Property Anag_Lavorazioni As Anag_Lavorazioni
    Public Overridable Property Anag_LavorazioniComplete As Anag_LavorazioniComplete

End Class
