'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_MagazziniAnag_CausaliMagazzino
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Magazzini As Decimal
    Public Property codeAnag_CausaliMagazzino As Integer
    Public Property strTipoDoc As String
    Public Property strCausaleDoc As String

    Public Overridable Property Anag_CausaliMagazzino As Anag_CausaliMagazzino
    Public Overridable Property Anag_Magazzini As Anag_Magazzini

End Class
