'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Lavorazioni_Sezionamento
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Lavorazioni As Decimal
    Public Property KeyIdAnag_Articoli As Nullable(Of Decimal)
    Public Property dblPercentuale As Nullable(Of Double)
    Public Property KeyIdAnagLavorazioniSezionamento_Padre As Nullable(Of Decimal)
    Public Property KeyIdAnag_ArticoliImballo As Nullable(Of Decimal)
    Public Property intTipo As Short
    Public Property strDescrizioneScelta As String
    Public Property KeyIdAnag_ArticoliConfezionamenti As Nullable(Of Decimal)
    Public Property KeyIdAnag_Stampanti As Nullable(Of Decimal)
    Public Property KeyIdAnag_ArticoliContenitori As Nullable(Of Decimal)

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Articoli1 As Anag_Articoli
    Public Overridable Property Anag_ArticoliConfezionamenti As Anag_ArticoliConfezionamenti
    Public Overridable Property Anag_Lav_SezImb As ICollection(Of Anag_Lav_SezImb) = New HashSet(Of Anag_Lav_SezImb)
    Public Overridable Property Anag_Lavorazioni As Anag_Lavorazioni
    Public Overridable Property Anag_Lavorazioni_Sezionamento1 As ICollection(Of Anag_Lavorazioni_Sezionamento) = New HashSet(Of Anag_Lavorazioni_Sezionamento)
    Public Overridable Property Anag_Lavorazioni_Sezionamento2 As Anag_Lavorazioni_Sezionamento
    Public Overridable Property Anag_Stampanti As Anag_Stampanti

End Class
