'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_LavorazioniTipiOp
    Public Property KeyId As Decimal
    Public Property strDescrizione As String

    Public Overridable Property Anag_Lavorazioni_Destinazione_Esecuzione As ICollection(Of Anag_Lavorazioni_Destinazione_Esecuzione) = New HashSet(Of Anag_Lavorazioni_Destinazione_Esecuzione)
    Public Overridable Property LavorazioniFasi_Destinazione_Esecuzione As ICollection(Of LavorazioniFasi_Destinazione_Esecuzione) = New HashSet(Of LavorazioniFasi_Destinazione_Esecuzione)

End Class
