'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Decodifica_Articoli
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Clienti As Nullable(Of Decimal)
    Public Property KeyIdAnag_Clienti_Destinazioni As Nullable(Of Decimal)
    Public Property KeyIdAnag_Fornitori As Nullable(Of Decimal)
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property strCodice As String
    Public Property strDescrizione As String
    Public Property strBarcode As String
    Public Property KeyIdMaschereTr As Nullable(Of Decimal)
    Public Property strFormatoData As String
    Public Property intPesoConfInGr As Nullable(Of Integer)
    Public Property strCodice2 As String

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Clienti As Anag_Clienti
    Public Overridable Property Anag_Clienti_Destinazioni As Anag_Clienti_Destinazioni
    Public Overridable Property Anag_Fornitori As Anag_Fornitori
    Public Overridable Property MaschereTr As MaschereTr

End Class
