'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Plc
    Public Property KeyId As Decimal
    Public Property strNome As String
    Public Property strIp As String
    Public Property intModello As Short

    Public Overridable Property Anag_Serbatoi As ICollection(Of Anag_Serbatoi) = New HashSet(Of Anag_Serbatoi)
    Public Overridable Property Storico_PesiPlc As ICollection(Of Storico_PesiPlc) = New HashSet(Of Storico_PesiPlc)

End Class
