'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Lingue
    Public Property strCodiceLingua As String
    Public Property strDescrizione As String
    Public Property bitActive As Boolean
    Public Property intOrdine As Decimal

    Public Overridable Property Anag_Clienti As ICollection(Of Anag_Clienti) = New HashSet(Of Anag_Clienti)
    Public Overridable Property Traduzioni_Parole As ICollection(Of Traduzioni_Parole) = New HashSet(Of Traduzioni_Parole)

End Class
