'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_IVA
    Public Property KeyId As Decimal
    Public Property strCodice As String
    Public Property strDescrizione As String
    Public Property dblPercentuale As Double
    Public Property strNaturaIva As String
    Public Property KeyIdCE As Nullable(Of Decimal)
    Public Property KeyIdGW As Nullable(Of Decimal)

    Public Overridable Property Anag_Articoli As ICollection(Of Anag_Articoli) = New HashSet(Of Anag_Articoli)
    Public Overridable Property Anag_Gm As ICollection(Of Anag_Gm) = New HashSet(Of Anag_Gm)
    Public Overridable Property ContabilitaCassa_Dettagli As ICollection(Of ContabilitaCassa_Dettagli) = New HashSet(Of ContabilitaCassa_Dettagli)
    Public Overridable Property DdtAcquisto_Dettagli As ICollection(Of DdtAcquisto_Dettagli) = New HashSet(Of DdtAcquisto_Dettagli)
    Public Overridable Property Fatture_Dettagli As ICollection(Of Fatture_Dettagli) = New HashSet(Of Fatture_Dettagli)
    Public Overridable Property InVendita As ICollection(Of InVendita) = New HashSet(Of InVendita)
    Public Overridable Property MovimentiMagazzino As ICollection(Of MovimentiMagazzino) = New HashSet(Of MovimentiMagazzino)

End Class
