'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_ClientiDatiAggiuntivi
    Public Property KeyIdAnag_Clienti As Decimal
    Public Property strSDI As String
    Public Property strCig As String
    Public Property strCup As String

    Public Overridable Property Anag_Clienti As Anag_Clienti

End Class
