'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Lavorazioni_Impasti
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Lavorazioni As Decimal
    Public Property dblQuantita As Double
    Public Property dblCapMaxContenitoreOut As Double

    Public Overridable Property Anag_Lavorazioni_ImpastiAdditivi As ICollection(Of Anag_Lavorazioni_ImpastiAdditivi) = New HashSet(Of Anag_Lavorazioni_ImpastiAdditivi)
    Public Overridable Property Anag_Lavorazioni_ImpastiArticoliInOut As ICollection(Of Anag_Lavorazioni_ImpastiArticoliInOut) = New HashSet(Of Anag_Lavorazioni_ImpastiArticoliInOut)

End Class
