'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Clienti_Anag_Lavorazioni
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Clienti As Nullable(Of Decimal)
    Public Property KeyIdAnag_Lavorazioni As Nullable(Of Decimal)

    Public Overridable Property Anag_Clienti As Anag_Clienti
    Public Overridable Property Anag_Lavorazioni As Anag_Lavorazioni

End Class
