'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Costi
    Public Property KeyId As Decimal
    Public Property strDescrizione As String
    Public Property imgImage As Byte()

    Public Overridable Property Anag_Lavorazioni_Costi As ICollection(Of Anag_Lavorazioni_Costi) = New HashSet(Of Anag_Lavorazioni_Costi)

End Class
