'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Lavorazioni_ImpastiArticoliInOut
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Lavorazioni_Impasti As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property bitIngresso As Boolean
    Public Property bitEliminato As Boolean

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Lavorazioni_Impasti As Anag_Lavorazioni_Impasti

End Class
