'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Celle_Aree
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Celle As Nullable(Of Decimal)
    Public Property strCodice As String
    Public Property strDescrizione As String

    Public Overridable Property Anag_Celle As Anag_Celle
    Public Overridable Property InAreaLavorazione As ICollection(Of InAreaLavorazione) = New HashSet(Of InAreaLavorazione)

End Class
