'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Articoli_InCelleLavorazione
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property KeyIdAnag_Celle As Decimal
    Public Property KeyIdAnag_ArticoliTrasformato As Decimal
    Public Property strIngredientiAggiuntivi As String

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Articoli1 As Anag_Articoli
    Public Overridable Property Anag_Celle As Anag_Celle

End Class
