'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_TabellaConversioneUm
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_UmPr As Decimal
    Public Property KeyIdAnag_UmSc As Decimal
    Public Property dblCoefficiente As Double
    Public Property strDescrizione As String

End Class
