'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_LavorazioniTipiDestinazioni_Confezionamenti
    Public Property KeyId As Decimal
    Public Property strNome As String
    Public Property bitQtaInput As Nullable(Of Boolean)
    Public Property bitArticoloOut As Nullable(Of Boolean)
    Public Property bitContenitoreOut As Nullable(Of Boolean)
    Public Property bitQtaCarrelli As Nullable(Of Boolean)
    Public Property bitVisibile As Nullable(Of Boolean)
    Public Property bitQtaInputStabilita As Nullable(Of Boolean)

    Public Overridable Property Anag_Lavorazioni_Destinazione As ICollection(Of Anag_Lavorazioni_Destinazione) = New HashSet(Of Anag_Lavorazioni_Destinazione)

End Class
