'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Lavorazioni_VascheArticoliInOut
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Lavorazioni_Vasche As Decimal
    Public Property bitIngresso As Boolean
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property bitEliminato As Boolean
    Public Property intTipoArticolo As Short
    Public Property dblRapportoPercentuale As Nullable(Of Double)

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Lavorazioni_Vasche As Anag_Lavorazioni_Vasche
    Public Overridable Property Anag_Lavorazioni_VascheArticoliInOutImballi As ICollection(Of Anag_Lavorazioni_VascheArticoliInOutImballi) = New HashSet(Of Anag_Lavorazioni_VascheArticoliInOutImballi)

End Class
