'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_LavorazioniComplete
    Public Property KeyId As Decimal
    Public Property strCodiceLavorazione As String
    Public Property strDescrizione As String
    Public Property bitEliminato As Boolean
    Public Property KeyIdAnag_Magazzini As Nullable(Of Decimal)

    Public Overridable Property Anag_Magazzini As Anag_Magazzini
    Public Overridable Property Anag_LavorazioniCompleteDettagli As ICollection(Of Anag_LavorazioniCompleteDettagli) = New HashSet(Of Anag_LavorazioniCompleteDettagli)
    Public Overridable Property Lavorazioni As ICollection(Of Lavorazioni) = New HashSet(Of Lavorazioni)
    Public Overridable Property PreLavorazioni As ICollection(Of PreLavorazioni) = New HashSet(Of PreLavorazioni)

End Class
