'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Lavorazioni_EtichettaturaArticoliInOutImballi
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Lavorazioni_EtichettaturaArticoliInOut As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property KeyIdAnag_Um As Decimal
    Public Property dblQuantitaUm As Double
    Public Property intPzInImballo As Nullable(Of Decimal)
    Public Property bitEliminato As Boolean

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Lavorazioni_EtichettaturaArticoliInOut As Anag_Lavorazioni_EtichettaturaArticoliInOut
    Public Overridable Property Anag_Um As Anag_Um

End Class
