'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_ArticoliDatiAggiuntivi
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property intGiorniScadenza As Nullable(Of Decimal)
    Public Property intScortaMinima As Nullable(Of Integer)
    Public Property bitEsportainiCasher As Nullable(Of Boolean)
    Public Property intDisponibilitaSuiCasher As Nullable(Of Short)
    Public Property bitContChiudibile As Nullable(Of Boolean)
    Public Property bitContPerSezionamento As Nullable(Of Boolean)
    Public Property bitContApribileSingolo As Nullable(Of Boolean)
    Public Property KeyIdAnag_RepartiBilance As Nullable(Of Decimal)
    Public Property intNumPluBilance As Nullable(Of Decimal)
    Public Property strDescrizionePluBilance As String
    Public Property bitUnioneAutomaticaLotti As Nullable(Of Boolean)
    Public Property intTipoImballo As Nullable(Of Short)
    Public Property bitLua As Nullable(Of Boolean)
    Public Property bitLottoDaLavPrec As Nullable(Of Boolean)
    Public Property bitSempreDisponibile As Nullable(Of Boolean)
    Public Property KeyIdAnag_Fornitore_ASD As Nullable(Of Decimal)
    Public Property bitLuaAutomatico As Nullable(Of Boolean)
    Public Property bitLuaFiFo As Nullable(Of Boolean)
    Public Property bitLuaDaily As Nullable(Of Boolean)
    Public Property bitNumeroPezziObbligatorio As Nullable(Of Boolean)

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Fornitori As Anag_Fornitori
    Public Overridable Property Anag_RepartiBilance As Anag_RepartiBilance

End Class
