'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_LavorazioniTipiLav
    Public Property KeyId As Decimal
    Public Property strNome As String
    Public Property bitAnag_Confezionamenti As Boolean

    Public Overridable Property Anag_Clienti_LayoutEtichette As ICollection(Of Anag_Clienti_LayoutEtichette) = New HashSet(Of Anag_Clienti_LayoutEtichette)
    Public Overridable Property Anag_Lavorazioni As ICollection(Of Anag_Lavorazioni) = New HashSet(Of Anag_Lavorazioni)
    Public Overridable Property LavorazioniFasi As ICollection(Of LavorazioniFasi) = New HashSet(Of LavorazioniFasi)

End Class
