'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Pv
    Public Property codePv As Short
    Public Property KeyIdAnag_Clienti As Nullable(Of Decimal)
    Public Property strDescrizione As String
    Public Property strIndirizzo As String
    Public Property strCap As String
    Public Property strCitta As String
    Public Property strProvincia As String
    Public Property strCodFiscale As String
    Public Property strTelefono As String
    Public Property bitEliminato As Nullable(Of Boolean)

    Public Overridable Property Anag_Bilance As ICollection(Of Anag_Bilance) = New HashSet(Of Anag_Bilance)
    Public Overridable Property Anag_Celle As ICollection(Of Anag_Celle) = New HashSet(Of Anag_Celle)
    Public Overridable Property Anag_Clienti As Anag_Clienti
    Public Overridable Property Anag_ConfezionamentiConfig As ICollection(Of Anag_ConfezionamentiConfig) = New HashSet(Of Anag_ConfezionamentiConfig)
    Public Overridable Property Anag_Magazzini As ICollection(Of Anag_Magazzini) = New HashSet(Of Anag_Magazzini)
    Public Overridable Property Anag_Operatori As ICollection(Of Anag_Operatori) = New HashSet(Of Anag_Operatori)
    Public Overridable Property Anag_Reparti As ICollection(Of Anag_Reparti) = New HashSet(Of Anag_Reparti)
    Public Overridable Property Anag_Serbatoi As ICollection(Of Anag_Serbatoi) = New HashSet(Of Anag_Serbatoi)
    Public Overridable Property Conferimenti As ICollection(Of Conferimenti) = New HashSet(Of Conferimenti)
    Public Overridable Property Contenitori As ICollection(Of Contenitori) = New HashSet(Of Contenitori)
    Public Overridable Property DdtAcquisto As ICollection(Of DdtAcquisto) = New HashSet(Of DdtAcquisto)
    Public Overridable Property Lavorazioni As ICollection(Of Lavorazioni) = New HashSet(Of Lavorazioni)
    Public Overridable Property Ordini As ICollection(Of Ordini) = New HashSet(Of Ordini)
    Public Overridable Property Progressivi As ICollection(Of Progressivi) = New HashSet(Of Progressivi)
    Public Overridable Property Sezionali As ICollection(Of Sezionali) = New HashSet(Of Sezionali)
    Public Overridable Property Sezionamenti As ICollection(Of Sezionamenti) = New HashSet(Of Sezionamenti)
    Public Overridable Property Totalizzazione As ICollection(Of Totalizzazione) = New HashSet(Of Totalizzazione)

End Class
