'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Lavorazioni_Destinazione
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Lavorazioni As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property dblQuantitaIn As Nullable(Of Double)
    Public Property KeyIdAnagLavorazioniTipiDestinazioni_Confezionamenti As Decimal
    Public Property KeyIdAnag_ArticoliOut As Nullable(Of Decimal)
    Public Property dblQuantitaCarrello As Nullable(Of Double)
    Public Property bitSenzaObbligoPesata As Boolean

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Articoli1 As Anag_Articoli
    Public Overridable Property Anag_Lavorazioni As Anag_Lavorazioni
    Public Overridable Property Anag_LavorazioniTipiDestinazioni_Confezionamenti As Anag_LavorazioniTipiDestinazioni_Confezionamenti
    Public Overridable Property Anag_Lavorazioni_Destinazione_Esecuzione As ICollection(Of Anag_Lavorazioni_Destinazione_Esecuzione) = New HashSet(Of Anag_Lavorazioni_Destinazione_Esecuzione)

End Class
