'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_CausaliMagazzino
    Public Property code As Integer
    Public Property strCodice As String
    Public Property strDescrizione As String
    Public Property Carichi As Nullable(Of Short)
    Public Property Scarichi As Nullable(Of Short)
    Public Property CarichiCL As Nullable(Of Short)
    Public Property ScarichiCL As Nullable(Of Short)
    Public Property OrdinatoC As Nullable(Of Short)
    Public Property OrdinatoF As Nullable(Of Short)

    Public Overridable Property Anag_MagazziniAnag_CausaliMagazzino As ICollection(Of Anag_MagazziniAnag_CausaliMagazzino) = New HashSet(Of Anag_MagazziniAnag_CausaliMagazzino)
    Public Overridable Property MovimentiMagazzino As ICollection(Of MovimentiMagazzino) = New HashSet(Of MovimentiMagazzino)
    Public Overridable Property Spedizioni As ICollection(Of Spedizioni) = New HashSet(Of Spedizioni)

End Class
