'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Lavorazioni_Vasche
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Lavorazioni As Decimal
    Public Property strNomeLayoutEtik As String
    Public Property bitEliminato As Nullable(Of Boolean)
    Public Property bitStampaAutomatica As Nullable(Of Boolean)
    Public Property KeyIdAnag_Stampanti As Nullable(Of Decimal)

    Public Overridable Property Anag_Lavorazioni As Anag_Lavorazioni
    Public Overridable Property Anag_Stampanti As Anag_Stampanti
    Public Overridable Property Anag_Lavorazioni_VascheArticoliInOut As ICollection(Of Anag_Lavorazioni_VascheArticoliInOut) = New HashSet(Of Anag_Lavorazioni_VascheArticoliInOut)
    Public Overridable Property LavorazioniFasi_Vasche As ICollection(Of LavorazioniFasi_Vasche) = New HashSet(Of LavorazioniFasi_Vasche)

End Class
