'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Um
    Public Property KeyId As Decimal
    Public Property codeUm As String
    Public Property strdescUm As String

    Public Overridable Property Anag_Articoli As ICollection(Of Anag_Articoli) = New HashSet(Of Anag_Articoli)
    Public Overridable Property Anag_Articoli1 As ICollection(Of Anag_Articoli) = New HashSet(Of Anag_Articoli)
    Public Overridable Property Anag_ArticoliConversioneUm As ICollection(Of Anag_ArticoliConversioneUm) = New HashSet(Of Anag_ArticoliConversioneUm)
    Public Overridable Property Anag_ArticoliConversioneUm1 As ICollection(Of Anag_ArticoliConversioneUm) = New HashSet(Of Anag_ArticoliConversioneUm)
    Public Overridable Property Anag_Clienti_ListiniArticoli As ICollection(Of Anag_Clienti_ListiniArticoli) = New HashSet(Of Anag_Clienti_ListiniArticoli)
    Public Overridable Property Anag_Lavorazioni_ConfezionamentiArticoliInOutImballi As ICollection(Of Anag_Lavorazioni_ConfezionamentiArticoliInOutImballi) = New HashSet(Of Anag_Lavorazioni_ConfezionamentiArticoliInOutImballi)
    Public Overridable Property Anag_Lavorazioni_EtichettaturaArticoliInOutImballi As ICollection(Of Anag_Lavorazioni_EtichettaturaArticoliInOutImballi) = New HashSet(Of Anag_Lavorazioni_EtichettaturaArticoliInOutImballi)
    Public Overridable Property Anag_Lavorazioni_ImpastiAdditivi As ICollection(Of Anag_Lavorazioni_ImpastiAdditivi) = New HashSet(Of Anag_Lavorazioni_ImpastiAdditivi)
    Public Overridable Property Anag_Lavorazioni_InsacchiArticoliInOutImballi As ICollection(Of Anag_Lavorazioni_InsacchiArticoliInOutImballi) = New HashSet(Of Anag_Lavorazioni_InsacchiArticoliInOutImballi)
    Public Overridable Property Anag_Lavorazioni_VascheArticoliInOutImballi As ICollection(Of Anag_Lavorazioni_VascheArticoliInOutImballi) = New HashSet(Of Anag_Lavorazioni_VascheArticoliInOutImballi)
    Public Overridable Property DdtAcquisto_Dettagli As ICollection(Of DdtAcquisto_Dettagli) = New HashSet(Of DdtAcquisto_Dettagli)
    Public Overridable Property DdtAcquisto_Dettagli1 As ICollection(Of DdtAcquisto_Dettagli) = New HashSet(Of DdtAcquisto_Dettagli)
    Public Overridable Property Fatture_Dettagli As ICollection(Of Fatture_Dettagli) = New HashSet(Of Fatture_Dettagli)
    Public Overridable Property InVendita As ICollection(Of InVendita) = New HashSet(Of InVendita)
    Public Overridable Property Inventario_Dettagli As ICollection(Of Inventario_Dettagli) = New HashSet(Of Inventario_Dettagli)
    Public Overridable Property LavorazioniFasi_ImpastiAdditivi As ICollection(Of LavorazioniFasi_ImpastiAdditivi) = New HashSet(Of LavorazioniFasi_ImpastiAdditivi)
    Public Overridable Property LavorazioniFasi_InsaccoImballi As ICollection(Of LavorazioniFasi_InsaccoImballi) = New HashSet(Of LavorazioniFasi_InsaccoImballi)
    Public Overridable Property ListiniDettagli As ICollection(Of ListiniDettagli) = New HashSet(Of ListiniDettagli)
    Public Overridable Property PreLavorazioniDettagli As ICollection(Of PreLavorazioniDettagli) = New HashSet(Of PreLavorazioniDettagli)
    Public Overridable Property Spedizioni_Dettagli As ICollection(Of Spedizioni_Dettagli) = New HashSet(Of Spedizioni_Dettagli)
    Public Overridable Property TrasferimentoInterno_Dettagli As ICollection(Of TrasferimentoInterno_Dettagli) = New HashSet(Of TrasferimentoInterno_Dettagli)

End Class
