'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Clienti
    Public Property KeyId As Decimal
    Public Property strCodice As String
    Public Property intTipologia As Nullable(Of Short)
    Public Property strRagioneSociale As String
    Public Property strIndirizzo As String
    Public Property strCap As String
    Public Property strCitta As String
    Public Property strProvincia As String
    Public Property strCodFiscale As String
    Public Property strPIva As String
    Public Property Cod_MacroArea As String
    Public Property Cod_Area As String
    Public Property Cod_Zona As String
    Public Property strTelefono As String
    Public Property strMobile As String
    Public Property strNome As String
    Public Property strCognome As String
    Public Property strMail As String
    Public Property strMailPec As String
    Public Property strCodiceLingua As String
    Public Property intLivelloAccesso As Short
    Public Property strUsername As String
    Public Property strPassword As String
    Public Property bitAccettaSubitoOrdini As Nullable(Of Boolean)
    Public Property codeIdTipoPagamento As Nullable(Of Short)
    Public Property strCodiceVettore As String
    Public Property strCodicePorto As String
    Public Property codeModelloDDT As Nullable(Of Short)
    Public Property strCodiceAgente As String
    Public Property bitMagTraceRepo As Boolean
    Public Property KeyIdGW As Nullable(Of Decimal)
    Public Property KeyIdAnag_Magazzini As Nullable(Of Decimal)
    Public Property bitMTAggiornatoRepo As Boolean
    Public Property codeDocumentoGestionaleEsterno As Nullable(Of Short)

    Public Overridable Property Anag_Clienti_Anag_Lavorazioni As ICollection(Of Anag_Clienti_Anag_Lavorazioni) = New HashSet(Of Anag_Clienti_Anag_Lavorazioni)
    Public Overridable Property Anag_Lingue As Anag_Lingue
    Public Overridable Property Anag_Magazzini As Anag_Magazzini
    Public Overridable Property Anag_Clienti_Destinazioni As ICollection(Of Anag_Clienti_Destinazioni) = New HashSet(Of Anag_Clienti_Destinazioni)
    Public Overridable Property Anag_Clienti_LayoutEtichette As ICollection(Of Anag_Clienti_LayoutEtichette) = New HashSet(Of Anag_Clienti_LayoutEtichette)
    Public Overridable Property Anag_Clienti_Listini As ICollection(Of Anag_Clienti_Listini) = New HashSet(Of Anag_Clienti_Listini)
    Public Overridable Property TipoPagamento As TipoPagamento
    Public Overridable Property Anag_ClientiDatiAggiuntivi As Anag_ClientiDatiAggiuntivi
    Public Overridable Property Anag_Decodifica_Articoli As ICollection(Of Anag_Decodifica_Articoli) = New HashSet(Of Anag_Decodifica_Articoli)
    Public Overridable Property Anag_Pv As ICollection(Of Anag_Pv) = New HashSet(Of Anag_Pv)
    Public Overridable Property CartonePallets As ICollection(Of CartonePallets) = New HashSet(Of CartonePallets)
    Public Overridable Property Ddt_Acquisto_Vivi As ICollection(Of Ddt_Acquisto_Vivi) = New HashSet(Of Ddt_Acquisto_Vivi)
    Public Overridable Property Fatture As ICollection(Of Fatture) = New HashSet(Of Fatture)
    Public Overridable Property InParzializzazione As ICollection(Of InParzializzazione) = New HashSet(Of InParzializzazione)
    Public Overridable Property InParzializzazione_Esecuzione As ICollection(Of InParzializzazione_Esecuzione) = New HashSet(Of InParzializzazione_Esecuzione)
    Public Overridable Property Lavorazioni As ICollection(Of Lavorazioni) = New HashSet(Of Lavorazioni)
    Public Overridable Property LavorazioniFasi_VascheArtOut As ICollection(Of LavorazioniFasi_VascheArtOut) = New HashSet(Of LavorazioniFasi_VascheArtOut)
    Public Overridable Property Listini_Associazione As ICollection(Of Listini_Associazione) = New HashSet(Of Listini_Associazione)
    Public Overridable Property Ordini As ICollection(Of Ordini) = New HashSet(Of Ordini)
    Public Overridable Property PrimaNota As ICollection(Of PrimaNota) = New HashSet(Of PrimaNota)
    Public Overridable Property Spedizioni As ICollection(Of Spedizioni) = New HashSet(Of Spedizioni)
    Public Overridable Property tmpConfigConferimentiFluidi As ICollection(Of tmpConfigConferimentiFluidi) = New HashSet(Of tmpConfigConferimentiFluidi)

End Class
