'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_RicetteImballi
    Public Property KeyId As Decimal
    Public Property KeyId_AnagRicette As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property intConteggiaOgni As Decimal
    Public Property bitEliminato As Nullable(Of Boolean)

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Ricette As Anag_Ricette

End Class
