'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Reparti
    Public Property KeyId As Decimal
    Public Property codePv As Short
    Public Property intNumRep As Decimal
    Public Property strDescrizione As String
    Public Property KeyIdCE As Nullable(Of Decimal)

    Public Overridable Property Anag_Articoli As ICollection(Of Anag_Articoli) = New HashSet(Of Anag_Articoli)
    Public Overridable Property Anag_Celle As ICollection(Of Anag_Celle) = New HashSet(Of Anag_Celle)
    Public Overridable Property Anag_ConfezionamentiConfig As ICollection(Of Anag_ConfezionamentiConfig) = New HashSet(Of Anag_ConfezionamentiConfig)
    Public Overridable Property Anag_Filiere As ICollection(Of Anag_Filiere) = New HashSet(Of Anag_Filiere)
    Public Overridable Property Anag_Gm As ICollection(Of Anag_Gm) = New HashSet(Of Anag_Gm)
    Public Overridable Property Anag_Lavorazioni As ICollection(Of Anag_Lavorazioni) = New HashSet(Of Anag_Lavorazioni)
    Public Overridable Property Anag_Operatori As ICollection(Of Anag_Operatori) = New HashSet(Of Anag_Operatori)
    Public Overridable Property Anag_Pv As Anag_Pv
    Public Overridable Property Anag_RepartiBilance As ICollection(Of Anag_RepartiBilance) = New HashSet(Of Anag_RepartiBilance)
    Public Overridable Property Anag_Ricette As ICollection(Of Anag_Ricette) = New HashSet(Of Anag_Ricette)
    Public Overridable Property Anag_Tare As ICollection(Of Anag_Tare) = New HashSet(Of Anag_Tare)
    Public Overridable Property Lavorazioni As ICollection(Of Lavorazioni) = New HashSet(Of Lavorazioni)
    Public Overridable Property MaschereTr As ICollection(Of MaschereTr) = New HashSet(Of MaschereTr)

End Class
