'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Coupon
    Public Property KeyId As Decimal
    Public Property strCodice As String
    Public Property strDescrizione As String
    Public Property intTipoSconto As Short
    Public Property dblValoreSconto As Double
    Public Property intQtaIniziali As Nullable(Of Decimal)
    Public Property intQtaDisponibili As Nullable(Of Decimal)
    Public Property dateDataInizio As Nullable(Of Date)
    Public Property dateDataFine As Nullable(Of Date)
    Public Property bitAttivo As Boolean
    Public Property bitEliminato As Boolean

End Class
