'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Anag_Operatori
    Public Property KeyId As Decimal
    Public Property codePv As Nullable(Of Short)
    Public Property KeyIdAnag_Reparto As Nullable(Of Decimal)
    Public Property strNome As String
    Public Property strCognome As String
    Public Property strUsername As String
    Public Property strPassword As String
    Public Property intLivello As Decimal
    Public Property intTimeoutLogout As Decimal
    Public Property bitEliminato As Boolean
    Public Property strUID As String
    Public Property bitMultiPv As Nullable(Of Boolean)
    Public Property bitMultiReparto As Nullable(Of Boolean)
    Public Property bitConferimento As Nullable(Of Boolean)
    Public Property bitSezionamento As Nullable(Of Boolean)
    Public Property bitRegistraQta As Nullable(Of Boolean)
    Public Property bitSezionamentoMultiplo As Nullable(Of Boolean)
    Public Property bitContenitori As Nullable(Of Boolean)
    Public Property bitChiusuraContenitori As Nullable(Of Boolean)
    Public Property bitRicette As Nullable(Of Boolean)
    Public Property bitModificaPesoOrdineRicetta As Nullable(Of Boolean)
    Public Property bitMiscele As Nullable(Of Boolean)
    Public Property bitPreparati As Nullable(Of Boolean)
    Public Property bitDestinazioni As Nullable(Of Boolean)
    Public Property bitUscitaMerce As Nullable(Of Boolean)
    Public Property bitUscitaMerceSenzaOrdine As Nullable(Of Boolean)
    Public Property bitAddettoKitchen As Nullable(Of Boolean)
    Public Property bitInAreaLavorazione As Nullable(Of Boolean)
    Public Property bitParzializzazione As Nullable(Of Boolean)
    Public Property bitConfezionamento As Nullable(Of Boolean)
    Public Property bitDiVendita As Nullable(Of Boolean)
    Public Property bitCaloPeso As Nullable(Of Boolean)
    Public Property bitInventario As Nullable(Of Boolean)
    Public Property bitModificaPrezzoInVendita As Nullable(Of Boolean)
    Public Property bitOperatoreiCasher As Nullable(Of Boolean)
    Public Property bitTraccDinamicaInVendita As Nullable(Of Boolean)
    Public Property bitTaraLibera As Nullable(Of Boolean)
    Public Property bitTaraContenitore As Nullable(Of Boolean)
    Public Property bitLavorazioniFasi As Nullable(Of Boolean)
    Public Property bitImpasti As Nullable(Of Boolean)
    Public Property bitInsacchi As Nullable(Of Boolean)
    Public Property bitConferimentoDinamico As Nullable(Of Boolean)
    Public Property bitEtichettatura As Nullable(Of Boolean)
    Public Property bitConfezionamentoDinamico As Nullable(Of Boolean)
    Public Property bitTakeAway As Nullable(Of Boolean)
    Public Property bitGestioneRepartiBilance As Nullable(Of Boolean)
    Public Property bitConferimentoFluidi As Nullable(Of Boolean)
    Public Property bitUscitaMerceFluidi As Nullable(Of Boolean)
    Public Property bitTrasferimentoMerce As Nullable(Of Boolean)
    Public Property bitLua As Nullable(Of Boolean)
    Public Property bitPrelievoFluidi As Nullable(Of Boolean)
    Public Property bitTrasferimentoInternoFluidi As Nullable(Of Boolean)
    Public Property bitTravasoFluidi As Nullable(Of Boolean)
    Public Property bitMovimentiLiberi As Nullable(Of Boolean)
    Public Property bitCaloPesoSerbatoi As Nullable(Of Boolean)
    Public Property bitNoMovimento As Nullable(Of Boolean)
    Public Property bitOrdineSezionamento As Nullable(Of Boolean)
    Public Property bitOrdineRicetta As Nullable(Of Boolean)
    Public Property bitVisualizzaDDTUscita As Nullable(Of Boolean)
    Public Property bitOrdineFasi As Nullable(Of Boolean)
    Public Property bitVasche As Nullable(Of Boolean)
    Public Property bitContenitoriDaSezionamentoInLinea As Nullable(Of Boolean)
    Public Property bitVisualizzaDDTAcquisto As Nullable(Of Boolean)
    Public Property bitRistampaEtichette As Nullable(Of Boolean)
    Public Property bitCambioArticolo As Nullable(Of Boolean)
    Public Property bitInventarioMagazzino As Nullable(Of Boolean)

    Public Overridable Property Accessi As ICollection(Of Accessi) = New HashSet(Of Accessi)
    Public Overridable Property Anag_Pv As Anag_Pv
    Public Overridable Property Anag_Reparti As Anag_Reparti
    Public Overridable Property CambioArticolo As ICollection(Of CambioArticolo) = New HashSet(Of CambioArticolo)
    Public Overridable Property CartonePallets As ICollection(Of CartonePallets) = New HashSet(Of CartonePallets)
    Public Overridable Property Conferimenti As ICollection(Of Conferimenti) = New HashSet(Of Conferimenti)
    Public Overridable Property DdtAcquisto As ICollection(Of DdtAcquisto) = New HashSet(Of DdtAcquisto)
    Public Overridable Property EsecuzioneUnioneLotti_Dettagli As ICollection(Of EsecuzioneUnioneLotti_Dettagli) = New HashSet(Of EsecuzioneUnioneLotti_Dettagli)
    Public Overridable Property Fatture As ICollection(Of Fatture) = New HashSet(Of Fatture)
    Public Overridable Property ImpSeurop As ICollection(Of ImpSeurop) = New HashSet(Of ImpSeurop)
    Public Overridable Property InParzializzazione As ICollection(Of InParzializzazione) = New HashSet(Of InParzializzazione)
    Public Overridable Property InParzializzazione1 As ICollection(Of InParzializzazione) = New HashSet(Of InParzializzazione)
    Public Overridable Property InParzializzazione_Esecuzione As ICollection(Of InParzializzazione_Esecuzione) = New HashSet(Of InParzializzazione_Esecuzione)
    Public Overridable Property Lavorazioni As ICollection(Of Lavorazioni) = New HashSet(Of Lavorazioni)
    Public Overridable Property LavorazioniFasi_Ricette As ICollection(Of LavorazioniFasi_Ricette) = New HashSet(Of LavorazioniFasi_Ricette)
    Public Overridable Property LavorazioniFasi_Vasche As ICollection(Of LavorazioniFasi_Vasche) = New HashSet(Of LavorazioniFasi_Vasche)
    Public Overridable Property LavorazioniFasi_VascheArtIn As ICollection(Of LavorazioniFasi_VascheArtIn) = New HashSet(Of LavorazioniFasi_VascheArtIn)
    Public Overridable Property LavorazioniFasi_VascheArtOut As ICollection(Of LavorazioniFasi_VascheArtOut) = New HashSet(Of LavorazioniFasi_VascheArtOut)
    Public Overridable Property LottiInCucina As ICollection(Of LottiInCucina) = New HashSet(Of LottiInCucina)
    Public Overridable Property LottiInCucina_Dettagli As ICollection(Of LottiInCucina_Dettagli) = New HashSet(Of LottiInCucina_Dettagli)
    Public Overridable Property LottoUnicoAperto As ICollection(Of LottoUnicoAperto) = New HashSet(Of LottoUnicoAperto)
    Public Overridable Property Ordini As ICollection(Of Ordini) = New HashSet(Of Ordini)
    Public Overridable Property PoolDiStampa As ICollection(Of PoolDiStampa) = New HashSet(Of PoolDiStampa)
    Public Overridable Property PreLavorazioni As ICollection(Of PreLavorazioni) = New HashSet(Of PreLavorazioni)
    Public Overridable Property Sezionamenti As ICollection(Of Sezionamenti) = New HashSet(Of Sezionamenti)
    Public Overridable Property Spedizioni As ICollection(Of Spedizioni) = New HashSet(Of Spedizioni)
    Public Overridable Property Storico_RegistraQuantita As ICollection(Of Storico_RegistraQuantita) = New HashSet(Of Storico_RegistraQuantita)
    Public Overridable Property Tare As ICollection(Of Tare) = New HashSet(Of Tare)
    Public Overridable Property tmpConferimentiFluidi As ICollection(Of tmpConferimentiFluidi) = New HashSet(Of tmpConferimentiFluidi)
    Public Overridable Property tmpConfigConferimentiFluidi As ICollection(Of tmpConfigConferimentiFluidi) = New HashSet(Of tmpConfigConferimentiFluidi)
    Public Overridable Property TrasferimentoInterno As ICollection(Of TrasferimentoInterno) = New HashSet(Of TrasferimentoInterno)

End Class
