'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CambioArticolo
    Public Property KeyId As Decimal
    Public Property KeyIdConferimenti As Nullable(Of Decimal)
    Public Property KeyIdSezionamenti As Nullable(Of Decimal)
    Public Property KeyIdTracciabilitaAddizionaleOrigine As Nullable(Of Decimal)
    Public Property KeyIdTracciabilitaAddizionaleNew As Nullable(Of Decimal)
    Public Property KeyIdConferimentoNew As Nullable(Of Decimal)
    Public Property dateDataOperazione As Date
    Public Property KeyIdAnag_Operatori As Decimal

    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property Conferimenti As Conferimenti
    Public Overridable Property Conferimenti1 As Conferimenti
    Public Overridable Property Sezionamenti As Sezionamenti
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale
    Public Overridable Property TracciabilitaAddizionale1 As TracciabilitaAddizionale

End Class
