'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CartonePallets_Dettagli
    Public Property KeyId As Decimal
    Public Property KeyIdCartonePallets As Decimal
    Public Property strNuo As String
    Public Property KeyIdAnag_Articoli As Nullable(Of Decimal)
    Public Property dblQuantita As Nullable(Of Double)
    Public Property dateDataOperazione As Date

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property CartonePallets As CartonePallets

End Class
