'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CartonePallets
    Public Property KeyId As Decimal
    Public Property intLivello As Short
    Public Property strNuo As String
    Public Property dataDataOperazione As Date
    Public Property KeyIdAnag_Clienti As Nullable(Of Decimal)
    Public Property KeyIdAnag_Clienti_Destinazioni As Nullable(Of Decimal)
    Public Property KeyIdAnag_Operatore As Decimal
    Public Property KeyIdTraccAddizionale As Nullable(Of Decimal)
    Public Property intStato As Short
    Public Property bitVenduto As Boolean

    Public Overridable Property Anag_Clienti As Anag_Clienti
    Public Overridable Property Anag_Clienti_Destinazioni As Anag_Clienti_Destinazioni
    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property CaloPeso As ICollection(Of CaloPeso) = New HashSet(Of CaloPeso)
    Public Overridable Property CartonePallets_Dettagli As ICollection(Of CartonePallets_Dettagli) = New HashSet(Of CartonePallets_Dettagli)
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale
    Public Overridable Property InParzializzazione_Esecuzione As ICollection(Of InParzializzazione_Esecuzione) = New HashSet(Of InParzializzazione_Esecuzione)
    Public Overridable Property InParzializzazione_Esecuzione1 As ICollection(Of InParzializzazione_Esecuzione) = New HashSet(Of InParzializzazione_Esecuzione)
    Public Overridable Property InParzializzazione_Esecuzione2 As ICollection(Of InParzializzazione_Esecuzione) = New HashSet(Of InParzializzazione_Esecuzione)
    Public Overridable Property Spedizioni_Dettagli As ICollection(Of Spedizioni_Dettagli) = New HashSet(Of Spedizioni_Dettagli)

End Class
