'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CartonePalletsConfig
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Postazioni As Decimal
    Public Property strPathLayoutLiv1 As String
    Public Property KeyIdAnag_StampantiLiv1 As Nullable(Of Decimal)
    Public Property strPathLayoutLiv2 As String
    Public Property KeyIdAnag_StampantiLiv2 As Nullable(Of Decimal)
    Public Property strPathLayoutLiv3 As String
    Public Property KeyIdAnag_StampantiLiv3 As Nullable(Of Decimal)

    Public Overridable Property Anag_Postazioni As Anag_Postazioni
    Public Overridable Property Anag_Stampanti As Anag_Stampanti
    Public Overridable Property Anag_Stampanti1 As Anag_Stampanti
    Public Overridable Property Anag_Stampanti2 As Anag_Stampanti

End Class
