'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ConfDinamico_Conferimenti
    Public Property KeyId As Decimal
    Public Property KeyIdConfDinamico As Decimal
    Public Property KeyIdConferimenti As Decimal
    Public Property strEan128 As String

    Public Overridable Property ConfDinamico As ConfDinamico
    Public Overridable Property Conferimenti As Conferimenti

End Class
