'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Conferimenti_MultiEtik
    Public Property KeyId As Decimal
    Public Property KeyIdConferimenti As Decimal
    Public Property strNuo As String
    Public Property dblQuantita As Nullable(Of Double)
    Public Property bitUsato As Boolean

    Public Overridable Property Conferimenti As Conferimenti
    Public Overridable Property LottiInCucina_Dettagli As ICollection(Of LottiInCucina_Dettagli) = New HashSet(Of LottiInCucina_Dettagli)

End Class
