'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Conferimenti
    Public Property KeyId As Decimal
    Public Property codePv As Nullable(Of Short)
    Public Property KeyIdMaschereTr As Nullable(Of Decimal)
    Public Property KeyIdTracciabilitaAddizionale As Nullable(Of Decimal)
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property KeyIdAnag_Fornitori As Decimal
    Public Property strNumProtocollo As String
    Public Property dateDataMacellazione As Nullable(Of Date)
    Public Property dateDataDocumento As Nullable(Of Date)
    Public Property codeIdAnag_TipoDocumento As Nullable(Of Decimal)
    Public Property strNumDDT As String
    Public Property KeyIdAnag_Fieliere As Decimal
    Public Property KeyIdAnag_Celle As Nullable(Of Decimal)
    Public Property KeyIdAnag_Serbatoi As Nullable(Of Decimal)
    Public Property KeyIdAnag_Operatori As Decimal
    Public Property KeyIdAnag_Postazioni As Decimal
    Public Property dblQuantita As Double
    Public Property dblQuantitaDisponibile As Double
    Public Property KeyIdAnag_Tare As Nullable(Of Decimal)
    Public Property KeyIdTare As Nullable(Of Decimal)
    Public Property strNuo As String
    Public Property strIngredienti As String
    Public Property strAllergeni As String
    Public Property dateDataIngresso As Date
    Public Property dateDataScadenza As Nullable(Of Date)
    Public Property intStatoVisivoCamion As Nullable(Of Short)
    Public Property intStatoVisivoTrasportatore As Nullable(Of Short)
    Public Property intTemperaturaCamion As Nullable(Of Decimal)
    Public Property intTemparaturaMerce As Nullable(Of Decimal)
    Public Property intTemperaturaPhMerce As Nullable(Of Decimal)
    Public Property intStatoLocazioneFase As Nullable(Of Short)
    Public Property bitProcessato As Boolean
    Public Property bitEliminato As Boolean
    Public Property bitTrasformato As Nullable(Of Boolean)
    Public Property bitTerminatoDaInventario As Boolean
    Public Property bitUtilizzabile As Boolean
    Public Property strCodicePreconferimento As String
    Public Property KeyIdSpedizioni As Nullable(Of Decimal)
    Public Property KeyIdFatture As Nullable(Of Decimal)
    Public Property bitDaReso As Nullable(Of Boolean)
    Public Property KeyIdDdtAcquisto As Nullable(Of Decimal)
    Public Property KeyIdDdtAcquisto_Dettagli As Nullable(Of Decimal)
    Public Property dblPrezzoAcquisto As Nullable(Of Double)
    Public Property strLottoLavorazione As String
    Public Property KeyIdConferimentiProv As Nullable(Of Decimal)
    Public Property KeyIdEsecuzioneUnioneLotti As Nullable(Of Decimal)
    Public Property KeyIdMagazzinoDa As Nullable(Of Decimal)
    Public Property IntNumeroPezzi As Nullable(Of Decimal)

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Celle As Anag_Celle
    Public Overridable Property Anag_Filiere As Anag_Filiere
    Public Overridable Property Anag_Fornitori As Anag_Fornitori
    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property Anag_Pv As Anag_Pv
    Public Overridable Property Anag_Serbatoi As Anag_Serbatoi
    Public Overridable Property Anag_TipoDocumento As Anag_TipoDocumento
    Public Overridable Property CaloPeso As ICollection(Of CaloPeso) = New HashSet(Of CaloPeso)
    Public Overridable Property CambioArticolo As ICollection(Of CambioArticolo) = New HashSet(Of CambioArticolo)
    Public Overridable Property CambioArticolo1 As ICollection(Of CambioArticolo) = New HashSet(Of CambioArticolo)
    Public Overridable Property ConfDinamico_Conferimenti As ICollection(Of ConfDinamico_Conferimenti) = New HashSet(Of ConfDinamico_Conferimenti)
    Public Overridable Property DdtAcquisto_Dettagli As DdtAcquisto_Dettagli
    Public Overridable Property EsecuzioneUnioneLotti As EsecuzioneUnioneLotti
    Public Overridable Property Fatture As Fatture
    Public Overridable Property MaschereTr As MaschereTr
    Public Overridable Property Conferimenti_MultiEtik As ICollection(Of Conferimenti_MultiEtik) = New HashSet(Of Conferimenti_MultiEtik)
    Public Overridable Property Spedizioni As Spedizioni
    Public Overridable Property Tare As Tare
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale
    Public Overridable Property Contenitori_Dettagli As ICollection(Of Contenitori_Dettagli) = New HashSet(Of Contenitori_Dettagli)
    Public Overridable Property Ddt_Acquisto_Vivi_Dettagli As ICollection(Of Ddt_Acquisto_Vivi_Dettagli) = New HashSet(Of Ddt_Acquisto_Vivi_Dettagli)
    Public Overridable Property EsecuzioneUnioneLotti_Dettagli As ICollection(Of EsecuzioneUnioneLotti_Dettagli) = New HashSet(Of EsecuzioneUnioneLotti_Dettagli)
    Public Overridable Property InAreaLavorazione As ICollection(Of InAreaLavorazione) = New HashSet(Of InAreaLavorazione)
    Public Overridable Property InParzializzazione As ICollection(Of InParzializzazione) = New HashSet(Of InParzializzazione)
    Public Overridable Property InVendita As ICollection(Of InVendita) = New HashSet(Of InVendita)
    Public Overridable Property LavorazioniFasi_ConfezionamentiArtIN As ICollection(Of LavorazioniFasi_ConfezionamentiArtIN) = New HashSet(Of LavorazioniFasi_ConfezionamentiArtIN)
    Public Overridable Property LavorazioniFasi_ConfezionamentoDImballi As ICollection(Of LavorazioniFasi_ConfezionamentoDImballi) = New HashSet(Of LavorazioniFasi_ConfezionamentoDImballi)
    Public Overridable Property LavorazioniFasi_IngressoLotti As ICollection(Of LavorazioniFasi_IngressoLotti) = New HashSet(Of LavorazioniFasi_IngressoLotti)
    Public Overridable Property LavorazioniFasi_Ricette_Eseguite As ICollection(Of LavorazioniFasi_Ricette_Eseguite) = New HashSet(Of LavorazioniFasi_Ricette_Eseguite)
    Public Overridable Property LavorazioniFasi_VascheImballi As ICollection(Of LavorazioniFasi_VascheImballi) = New HashSet(Of LavorazioniFasi_VascheImballi)
    Public Overridable Property tmpConferimentiFluidi As ICollection(Of tmpConferimentiFluidi) = New HashSet(Of tmpConferimentiFluidi)

End Class
