'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ConfigurazioniPostazioni
    Public Property KeyId As Decimal
    Public Property KeyIdPostazione As Decimal
    Public Property bitMultiReparto As Nullable(Of Boolean)
    Public Property bitConferimento As Nullable(Of Boolean)
    Public Property bitSezionamento As Nullable(Of Boolean)
    Public Property bitContenitori As Nullable(Of Boolean)
    Public Property bitRicette As Nullable(Of Boolean)
    Public Property bitMiscele As Nullable(Of Boolean)
    Public Property bitPreparati As Nullable(Of Boolean)
    Public Property bitDestinazione_Confezionamento As Nullable(Of Boolean)

    Public Overridable Property Anag_Postazioni As Anag_Postazioni

End Class
