'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ConfDinamico
    Public Property KeyId As Decimal
    Public Property intNumBancali As Integer
    Public Property strPathFilePdf As String

    Public Overridable Property ConfDinamico_Conferimenti As ICollection(Of ConfDinamico_Conferimenti) = New HashSet(Of ConfDinamico_Conferimenti)

End Class
