'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Contenitori
    Public Property KeyId As Decimal
    Public Property codePv As Nullable(Of Short)
    Public Property KeyIdLavorazioniFasi As Nullable(Of Decimal)
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property strNuo As String
    Public Property dateDataCreazione As Date
    Public Property dateDataScadenza As Nullable(Of Date)
    Public Property dblQuantita As Double
    Public Property dblQuantitaDisponibile As Nullable(Of Double)
    Public Property KeyIdAnag_Tare As Nullable(Of Decimal)
    Public Property intStato As Short
    Public Property bitTerminatoDaInventario As Boolean
    Public Property KeyIdAnag_Celle As Nullable(Of Decimal)
    Public Property KeyIdAnag_Operatori As Decimal
    Public Property KeyIdContenitoriProv As Nullable(Of Decimal)
    Public Property KeyIdSpedizioni As Nullable(Of Decimal)
    Public Property KeyIdFatture As Nullable(Of Decimal)
    Public Property KeyIdAnag_Serbatoi As Nullable(Of Decimal)
    Public Property KeyIdTmpConferimentiFluidi As Nullable(Of Decimal)

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Celle As Anag_Celle
    Public Overridable Property Anag_Pv As Anag_Pv
    Public Overridable Property Anag_Serbatoi As Anag_Serbatoi
    Public Overridable Property Anag_Tare As Anag_Tare
    Public Overridable Property CaloPeso As ICollection(Of CaloPeso) = New HashSet(Of CaloPeso)
    Public Overridable Property Contenitori_Dettagli As ICollection(Of Contenitori_Dettagli) = New HashSet(Of Contenitori_Dettagli)
    Public Overridable Property Contenitori_Dettagli1 As ICollection(Of Contenitori_Dettagli) = New HashSet(Of Contenitori_Dettagli)
    Public Overridable Property Fatture As Fatture
    Public Overridable Property LavorazioniFasi As LavorazioniFasi
    Public Overridable Property Spedizioni As Spedizioni
    Public Overridable Property tmpConferimentiFluidi As tmpConferimentiFluidi
    Public Overridable Property EsecuzioneUnioneLotti_Dettagli As ICollection(Of EsecuzioneUnioneLotti_Dettagli) = New HashSet(Of EsecuzioneUnioneLotti_Dettagli)
    Public Overridable Property InAreaLavorazione As ICollection(Of InAreaLavorazione) = New HashSet(Of InAreaLavorazione)
    Public Overridable Property InParzializzazione As ICollection(Of InParzializzazione) = New HashSet(Of InParzializzazione)
    Public Overridable Property InVendita As ICollection(Of InVendita) = New HashSet(Of InVendita)
    Public Overridable Property LavorazioniFasi_IngressoLotti As ICollection(Of LavorazioniFasi_IngressoLotti) = New HashSet(Of LavorazioniFasi_IngressoLotti)
    Public Overridable Property LavorazioniFasi_Ricette_Eseguite As ICollection(Of LavorazioniFasi_Ricette_Eseguite) = New HashSet(Of LavorazioniFasi_Ricette_Eseguite)
    Public Overridable Property Spedizioni_Dettagli As ICollection(Of Spedizioni_Dettagli) = New HashSet(Of Spedizioni_Dettagli)
    Public Overridable Property tmpConferimentiFluidi1 As ICollection(Of tmpConferimentiFluidi) = New HashSet(Of tmpConferimentiFluidi)

End Class
