'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ContabilitaCassa
    Public Property KeyId As Decimal
    Public Property bitB As Boolean
    Public Property intType As Short
    Public Property idDongleKey As Integer
    Public Property dateDataOperazione As Date
    Public Property intFcImpostato As Nullable(Of Integer)
    Public Property intLivelliInternoAttuale As Nullable(Of Integer)
    Public Property intImportoRefill As Nullable(Of Integer)
    Public Property intImportoRefillAuto As Nullable(Of Integer)
    Public Property intImportoPrelievi As Nullable(Of Integer)
    Public Property intImportoGiaPresenteNeiCassetti As Nullable(Of Integer)
    Public Property intNumTransazioniTotali As Nullable(Of Integer)
    Public Property intVendutoTransazioniTotali As Nullable(Of Integer)
    Public Property intNumTransazioniiC As Nullable(Of Integer)
    Public Property intTotVendutoiC As Nullable(Of Integer)
    Public Property intTotInseritoiC As Nullable(Of Integer)
    Public Property intTotRestoErogatoiC As Nullable(Of Integer)
    Public Property intTotRestoNonErogatoiC As Nullable(Of Integer)
    Public Property intNumTransazioniCarte As Nullable(Of Integer)
    Public Property intTotVendutoCarte As Nullable(Of Integer)
    Public Property intNumTransazioniManuali As Nullable(Of Integer)
    Public Property intTotVendutoManuale As Nullable(Of Integer)
    Public Property intNumTrCreditoClienti As Nullable(Of Integer)
    Public Property intTotVendutoCreditoClienti As Nullable(Of Integer)
    Public Property intNumTrAltriMet As Nullable(Of Integer)
    Public Property intTotVendutoAltriMet As Nullable(Of Integer)
    Public Property intValoreChiusura As Nullable(Of Integer)
    Public Property bitExportedToWeb As Boolean
    Public Property bitExportedToWebFailed As Boolean

    Public Overridable Property ContabilitaCassa_Dettagli As ICollection(Of ContabilitaCassa_Dettagli) = New HashSet(Of ContabilitaCassa_Dettagli)

End Class
