'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Contenitori_Dettagli
    Public Property KeyId As Decimal
    Public Property KeyIdContenitori As Decimal
    Public Property KeyIdLavorazioniFasi As Nullable(Of Decimal)
    Public Property KeyIdConferimenti As Nullable(Of Decimal)
    Public Property KeyIdSezionamenti As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_ConfezionamentoDArtOut As Nullable(Of Decimal)
    Public Property dblQuantita As Nullable(Of Double)
    Public Property KeyIdContenitoreInserito As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Destinazione As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Impasti As Nullable(Of Decimal)

    Public Overridable Property Conferimenti As Conferimenti
    Public Overridable Property Contenitori As Contenitori
    Public Overridable Property Contenitori1 As Contenitori
    Public Overridable Property LavorazioniFasi As LavorazioniFasi
    Public Overridable Property LavorazioniFasi_ConfezionamentoDArtOut As LavorazioniFasi_ConfezionamentoDArtOut
    Public Overridable Property LavorazioniFasi_Destinazione As LavorazioniFasi_Destinazione
    Public Overridable Property LavorazioniFasi_Impasti As LavorazioniFasi_Impasti
    Public Overridable Property Sezionamenti As Sezionamenti

End Class
