'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ContabilitaCassa_Dettagli
    Public Property KeyId As Decimal
    Public Property KeyIdContabilitaCassa As Decimal
    Public Property KeyIdAnag_Iva As Decimal
    Public Property intTotale As Nullable(Of Integer)

    Public Overridable Property Anag_IVA As Anag_IVA
    Public Overridable Property ContabilitaCassa As ContabilitaCassa

End Class
