'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ddt_Acquisto_Vivi_Dettagli
    Public Property KeyId As Decimal
    Public Property KeyIdDdtAcquistoVivi As Decimal
    Public Property KeyIdConferimenti As Decimal
    Public Property intStato As Short

    Public Overridable Property Conferimenti As Conferimenti
    Public Overridable Property Ddt_Acquisto_Vivi As Ddt_Acquisto_Vivi

End Class
