'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ddt_Acquisto_Vivi
    Public Property KeyId As Decimal
    Public Property KeyIdDdtAcquisto As Decimal
    Public Property KeyIdAnag_Allevatori As Nullable(Of Decimal)
    Public Property KeyIdAnag_Trasportatori As Nullable(Of Decimal)
    Public Property strDataDocumento As String
    Public Property strNumeroDocumento As String
    Public Property strCodiceControllo As String
    Public Property KeyIdAnag_Cliente As Nullable(Of Decimal)
    Public Property KeyIdAnag_Clienti_Destinazioni As Nullable(Of Decimal)
    Public Property intStato As Nullable(Of Short)

    Public Overridable Property Anag_Allevatori As Anag_Allevatori
    Public Overridable Property Anag_Clienti As Anag_Clienti
    Public Overridable Property Anag_Clienti_Destinazioni As Anag_Clienti_Destinazioni
    Public Overridable Property Anag_Trasportatori As Anag_Trasportatori
    Public Overridable Property DdtAcquisto As DdtAcquisto
    Public Overridable Property Ddt_Acquisto_Vivi_Dettagli As ICollection(Of Ddt_Acquisto_Vivi_Dettagli) = New HashSet(Of Ddt_Acquisto_Vivi_Dettagli)

End Class
