'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DdtAcquisto_Dettagli
    Public Property KeyId As Decimal
    Public Property KeyIdDdtAcquisto As Nullable(Of Decimal)
    Public Property intTipoMerce As Short
    Public Property KeyIdAnag_Articoli As Nullable(Of Decimal)
    Public Property KeyIdAnag_Filiere As Nullable(Of Decimal)
    Public Property strIngredienti As String
    Public Property dateDataScadenza As Nullable(Of Date)
    Public Property KeyIdAnag_Um1 As Nullable(Of Decimal)
    Public Property dblQuantita1 As Nullable(Of Double)
    Public Property KeyIdAnag_Um2 As Nullable(Of Decimal)
    Public Property dblQuantita2 As Nullable(Of Double)
    Public Property dblPrezzoUnit As Nullable(Of Double)
    Public Property KeyIdAnag_IVA As Nullable(Of Decimal)
    Public Property intStato As Nullable(Of Short)
    Public Property strNota As String
    Public Property KeyIdMaschereTr As Nullable(Of Decimal)
    Public Property KeyIdTracciabilitaAddizionale As Nullable(Of Decimal)
    Public Property bitUsaVecchioNuo As Boolean
    Public Property strVecchioNuo As String
    Public Property strLottoLavorazione As String
    Public Property intNumPosizione As Nullable(Of Integer)
    Public Property intRiga As Nullable(Of Short)
    Public Property dblQuantitaEvasa1 As Double
    Public Property dblQuantitaEvasa2 As Nullable(Of Double)
    Public Property dateDataMacellazione As Nullable(Of Date)
    Public Property strBarcode As String
    Public Property bitSenzaRiordino As Boolean
    Public Property intNumeroPezzi As Nullable(Of Decimal)

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Filiere As Anag_Filiere
    Public Overridable Property Anag_IVA As Anag_IVA
    Public Overridable Property Anag_Um As Anag_Um
    Public Overridable Property Anag_Um1 As Anag_Um
    Public Overridable Property Conferimenti As ICollection(Of Conferimenti) = New HashSet(Of Conferimenti)
    Public Overridable Property DdtAcquisto As DdtAcquisto
    Public Overridable Property MaschereTr As MaschereTr
    Public Overridable Property DdtAcquisto_Dettagli_MultiEtik As ICollection(Of DdtAcquisto_Dettagli_MultiEtik) = New HashSet(Of DdtAcquisto_Dettagli_MultiEtik)
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale

End Class
