'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DdtAcquisto
    Public Property KeyId As Decimal
    Public Property codePv As Short
    Public Property KeyIdAnag_Fornitori As Nullable(Of Decimal)
    Public Property dateDataMacellazione As Nullable(Of Date)
    Public Property strNumDDT As String
    Public Property intAnnoRif As Nullable(Of Short)
    Public Property dateDataInsermento As Nullable(Of Date)
    Public Property KeyIdAnag_Operatori As Nullable(Of Decimal)
    Public Property strNote As String
    Public Property strPathFileTrac As String
    Public Property codeTipoImportTrac As Nullable(Of Short)
    Public Property intStato As Nullable(Of Short)
    Public Property bitLocked As Nullable(Of Boolean)
    Public Property bitEliminato As Nullable(Of Boolean)
    Public Property strGW As String
    Public Property KeyIdAnag_Magazzini As Nullable(Of Decimal)
    Public Property strNuo As String
    Public Property bitOrdineAutoProdotto As Boolean
    Public Property bitVivo As Boolean

    Public Overridable Property Anag_Fornitori As Anag_Fornitori
    Public Overridable Property Anag_Magazzini As Anag_Magazzini
    Public Overridable Property Anag_Magazzini1 As Anag_Magazzini
    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property Anag_Pv As Anag_Pv
    Public Overridable Property Ddt_Acquisto_Vivi As ICollection(Of Ddt_Acquisto_Vivi) = New HashSet(Of Ddt_Acquisto_Vivi)
    Public Overridable Property TipoImportTrac As TipoImportTrac
    Public Overridable Property DdtAcquisto_Dettagli As ICollection(Of DdtAcquisto_Dettagli) = New HashSet(Of DdtAcquisto_Dettagli)
    Public Overridable Property tmpConfigConferimentiFluidi As ICollection(Of tmpConfigConferimentiFluidi) = New HashSet(Of tmpConfigConferimentiFluidi)

End Class
