'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DdtAcquisto_Dettagli_MultiEtik
    Public Property KeyId As Decimal
    Public Property KeyIdDdtAcquisto_Dettagli As Nullable(Of Decimal)
    Public Property strNuo As String
    Public Property dblQuantita As Nullable(Of Double)
    Public Property intPorzioniContenute As Nullable(Of Decimal)

    Public Overridable Property DdtAcquisto_Dettagli As DdtAcquisto_Dettagli

End Class
