'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DriverBilance
    Public Property KeyId As Decimal
    Public Property strPath As String
    Public Property intTipo As Short
    Public Property strPathLock As String
    Public Property strPathSwOpzionale As String
    Public Property bitScaricaPesate As Boolean
    Public Property intTipoScarica As Nullable(Of Short)
    Public Property bitScaricaWatcher As Boolean
    Public Property strEanMask As String
    Public Property intTipoProtocolloScarica As Nullable(Of Short)
    Public Property strPathImportazionePesate As String
    Public Property bitEliminato As Boolean

    Public Overridable Property LavorazioniFasi_ConfezionamentiDriverBilance As ICollection(Of LavorazioniFasi_ConfezionamentiDriverBilance) = New HashSet(Of LavorazioniFasi_ConfezionamentiDriverBilance)

End Class
