'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EsecuzioneUnioneLotti_Dettagli
    Public Property KeyId As Decimal
    Public Property KeyIdEsecuzioneUnioneLotti As Decimal
    Public Property KeyIdConferimenti As Nullable(Of Decimal)
    Public Property KeyIdSezionamenti As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Ricette As Nullable(Of Decimal)
    Public Property KeyIdContenitori As Nullable(Of Decimal)
    Public Property KeyIdInParzializzazione_Esecuzione As Nullable(Of Decimal)
    Public Property KeyIdTraccAddizionale As Nullable(Of Decimal)
    Public Property dateDataInserimento As Nullable(Of Date)
    Public Property KeyIdAnag_Operatori As Nullable(Of Decimal)
    Public Property dblQuantita As Nullable(Of Double)
    Public Property bitActive As Nullable(Of Boolean)

    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property Conferimenti As Conferimenti
    Public Overridable Property Contenitori As Contenitori
    Public Overridable Property EsecuzioneUnioneLotti As EsecuzioneUnioneLotti
    Public Overridable Property InParzializzazione_Esecuzione As InParzializzazione_Esecuzione
    Public Overridable Property LavorazioniFasi_Ricette As LavorazioniFasi_Ricette
    Public Overridable Property Sezionamenti As Sezionamenti
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale

End Class
