'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Fatture
    Public Property KeyId As Decimal
    Public Property KeyIdSezionali As Nullable(Of Decimal)
    Public Property intNumFattura As Nullable(Of Integer)
    Public Property intAnno As Nullable(Of Short)
    Public Property KeyIdAnag_Cliente As Nullable(Of Decimal)
    Public Property KeyIdAnag_Clienti_Destinazioni As Nullable(Of Decimal)
    Public Property KeyIdAnag_Fornitori As Nullable(Of Decimal)
    Public Property codeIdTipoPagamento As Nullable(Of Short)
    Public Property dateDataOperazione As Date
    Public Property KeyIdAnag_Operatori As Decimal
    Public Property intStato As Nullable(Of Short)

    Public Overridable Property Anag_Clienti As Anag_Clienti
    Public Overridable Property Anag_Clienti_Destinazioni As Anag_Clienti_Destinazioni
    Public Overridable Property Anag_Fornitori As Anag_Fornitori
    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property Conferimenti As ICollection(Of Conferimenti) = New HashSet(Of Conferimenti)
    Public Overridable Property Contenitori As ICollection(Of Contenitori) = New HashSet(Of Contenitori)
    Public Overridable Property Fatture_Dettagli As ICollection(Of Fatture_Dettagli) = New HashSet(Of Fatture_Dettagli)
    Public Overridable Property Sezionali As Sezionali
    Public Overridable Property TipoPagamento As TipoPagamento
    Public Overridable Property Ordini_DDT_Fatture As ICollection(Of Ordini_DDT_Fatture) = New HashSet(Of Ordini_DDT_Fatture)
    Public Overridable Property Sezionamenti As ICollection(Of Sezionamenti) = New HashSet(Of Sezionamenti)
    Public Overridable Property Spedizioni_Dettagli As ICollection(Of Spedizioni_Dettagli) = New HashSet(Of Spedizioni_Dettagli)
    Public Overridable Property Spedizioni As ICollection(Of Spedizioni) = New HashSet(Of Spedizioni)

End Class
