'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Fatture_Dettagli
    Public Property KeyId As Decimal
    Public Property KeyFatture As Nullable(Of Decimal)
    Public Property intNumRiga As Nullable(Of Decimal)
    Public Property strCodiceArticolo As String
    Public Property strDescrizioneArticolo As String
    Public Property strCodiceArticoloCliente As String
    Public Property strDescrizioneArticoloCliente As String
    Public Property KeyIdAnag_Um As Decimal
    Public Property dblQuantita As Double
    Public Property dblPrezzoUnit As Double
    Public Property KeyIdAnag_Iva As Decimal
    Public Property dblPercentualeIva As Nullable(Of Double)
    Public Property KeyIdSpedizione_Dettaglio As Nullable(Of Decimal)
    Public Property percSco1 As Nullable(Of Double)
    Public Property percSco2 As Nullable(Of Double)
    Public Property percSco3 As Nullable(Of Double)
    Public Property bitOmaggioEsenteIva As Nullable(Of Boolean)
    Public Property bitOmaggio As Nullable(Of Boolean)

    Public Overridable Property Anag_IVA As Anag_IVA
    Public Overridable Property Anag_Um As Anag_Um
    Public Overridable Property Fatture As Fatture

End Class
