'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ImpSeuropDettagli
    Public Property KeyId As Decimal
    Public Property KeyIdImpSeurop As Decimal
    Public Property Aurico As String
    Public Property NumMac As String
    Public Property Catego As String
    Public Property Sesso As String
    Public Property CodRaz As String
    Public Property CodNazNas As String
    Public Property CodNazAll1 As String
    Public Property CodNazAll2 As String
    Public Property DatNas As Nullable(Of Date)
    Public Property CodAll As String
    Public Property DatArr As Nullable(Of Date)
    Public Property DatMac As Nullable(Of Date)
    Public Property Peso As Nullable(Of Double)
    Public Property Barcode As String
    Public Property CodArt As String
    Public Property Lotto As String
    Public Property CodNazMac As String
    Public Property IDCe As String
    Public Property CodNazSez As String
    Public Property IdCeSez As String
    Public Property CodMarQua As String
    Public Property Prezzo As Nullable(Of Double)
    Public Property IndTipGen As String
    Public Property DatPriRis As Nullable(Of Date)
    Public Property CodCli As String
    Public Property CodDes As String
    Public Property NumDoc As Nullable(Of Integer)
    Public Property TipDoc As String
    Public Property MesVit As Nullable(Of Integer)
    Public Property GioRis As Nullable(Of Integer)
    Public Property MesRis As Nullable(Of Integer)
    Public Property DatDoc As Nullable(Of Date)
    Public Property DesArt As String
    Public Property DatCon As Nullable(Of Date)
    Public Property DatSca As Nullable(Of Date)
    Public Property BarCode1 As String
    Public Property CodArtRic As String
    Public Property NumPez As Nullable(Of Integer)
    Public Property TotCar As Nullable(Of Integer)
    Public Property NotTra1 As String
    Public Property NotTra2 As String
    Public Property NotTra3 As String
    Public Property DatUltTra As Nullable(Of Date)

    Public Overridable Property ImpSeurop As ImpSeurop

End Class
