'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ImpSeurop
    Public Property KeyId As Decimal
    Public Property dateDataOperazione As Date
    Public Property KeyIdAnag_Operatori As Decimal
    Public Property KeyIdAnag_Fornitori As Nullable(Of Decimal)

    Public Overridable Property Anag_Fornitori As Anag_Fornitori
    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property ImpSeuropDettagli As ICollection(Of ImpSeuropDettagli) = New HashSet(Of ImpSeuropDettagli)

End Class
