'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InAreaLavorazione
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Celle As Nullable(Of Decimal)
    Public Property KeyIdAnag_Celle_Aree As Nullable(Of Decimal)
    Public Property KeyIdConferimenti As Nullable(Of Decimal)
    Public Property KeyIdSezionamenti As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Ricette As Nullable(Of Decimal)
    Public Property KeyIdContenitori As Nullable(Of Decimal)
    Public Property dateDataInizio As Date
    Public Property bitDeterminaTempo As Boolean
    Public Property dateDataFineDeterminata As Nullable(Of Date)
    Public Property dateDataFine As Nullable(Of Date)
    Public Property KeyIdAnag_Operatori As Decimal
    Public Property KeyIdAnag_OperatoriFine As Nullable(Of Decimal)
    Public Property bitEliminato As Boolean

    Public Overridable Property Anag_Celle As Anag_Celle
    Public Overridable Property Anag_Celle_Aree As Anag_Celle_Aree
    Public Overridable Property Conferimenti As Conferimenti
    Public Overridable Property Contenitori As Contenitori
    Public Overridable Property InAreaLavorazione_ContenitoriRiutilizzabili As ICollection(Of InAreaLavorazione_ContenitoriRiutilizzabili) = New HashSet(Of InAreaLavorazione_ContenitoriRiutilizzabili)
    Public Overridable Property LavorazioniFasi_Ricette As LavorazioniFasi_Ricette
    Public Overridable Property Sezionamenti As Sezionamenti

End Class
