'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InfoImportatore
    Public Property KeyId As Decimal
    Public Property dateLastDateImportArticoli As Nullable(Of Date)
    Public Property dateLastDateImportArticoliPrezziDefault As Nullable(Of Date)
    Public Property dateLastDateImportClienti As Nullable(Of Date)
    Public Property dateLastDateImportDestinazioniClienti As Nullable(Of Date)
    Public Property dateLastDateImportFornitori As Nullable(Of Date)
    Public Property dateLastDateImportGm As Nullable(Of Date)
    Public Property dateLastDateImportListini As Nullable(Of Date)
    Public Property dateLastDateImportVenditeiCasher As Nullable(Of Date)
    Public Property dateLastDateImportSpedizioni As Nullable(Of Date)
    Public Property dateLastDateImportOrdiniClienti As Nullable(Of Date)
    Public Property dateLastDateImportTransBilRetEliminateiCasher As Nullable(Of Date)
    Public Property dateLastDateImportChiusureiCasher As Nullable(Of Date)
    Public Property dateLastDateImportOrdiniFornitori As Nullable(Of Date)
    Public Property dateLastDateImportCelle As Nullable(Of Date)

End Class
