'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InParzializzazione
    Public Property KeyId As Decimal
    Public Property KeyIdConferimenti As Nullable(Of Decimal)
    Public Property KeyIdSezionamenti As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Ricette As Nullable(Of Decimal)
    Public Property KeyIdContenitori As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_ConfezionamentiArtOUT As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_ConfezionamentoDArtOut As Nullable(Of Decimal)
    Public Property dateDataInvio As Date
    Public Property KeyIdAnag_OperatoreDiInvio As Decimal
    Public Property dateDataPresaInCarico As Nullable(Of Date)
    Public Property KeyIdAnag_OperatorePresaInCarico As Nullable(Of Decimal)
    Public Property intStato As Nullable(Of Short)
    Public Property dateDataFine As Nullable(Of Date)
    Public Property bitNascosto As Boolean
    Public Property intTipo As Short
    Public Property KeyIdAnag_Clienti As Nullable(Of Decimal)

    Public Overridable Property Anag_Clienti As Anag_Clienti
    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property Anag_Operatori1 As Anag_Operatori
    Public Overridable Property Conferimenti As Conferimenti
    Public Overridable Property Contenitori As Contenitori
    Public Overridable Property InParzializzazione_ContenitoriRiutilizzabili As ICollection(Of InParzializzazione_ContenitoriRiutilizzabili) = New HashSet(Of InParzializzazione_ContenitoriRiutilizzabili)
    Public Overridable Property LavorazioniFasi_ConfezionamentiArtOUT As LavorazioniFasi_ConfezionamentiArtOUT
    Public Overridable Property LavorazioniFasi_ConfezionamentoDArtOut As LavorazioniFasi_ConfezionamentoDArtOut
    Public Overridable Property LavorazioniFasi_Ricette As LavorazioniFasi_Ricette
    Public Overridable Property Sezionamenti As Sezionamenti

End Class
