'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InParzializzazione_Esecuzione
    Public Property KeyId As Decimal
    Public Property KeyIdInParzializzazione As Decimal
    Public Property KeyIdAnag_Clienti As Nullable(Of Decimal)
    Public Property KeyIdAnag_Clienti_Destinazioni As Nullable(Of Decimal)
    Public Property KeyIdAnag_Celle As Nullable(Of Decimal)
    Public Property KeyIdAnag_Operatori As Nullable(Of Decimal)
    Public Property strNuo As String
    Public Property dateDataOperazione As Date
    Public Property dateDataScadenza As Nullable(Of Date)
    Public Property intStatoLocazione As Short
    Public Property dblQuantita As Nullable(Of Double)
    Public Property dblQuantitaDisponibile As Nullable(Of Double)
    Public Property dblPrezzoUnit As Nullable(Of Double)
    Public Property KeyIdAnag_Bilance As Nullable(Of Decimal)
    Public Property KeyIdAnag_Tare As Nullable(Of Decimal)
    Public Property KeyIdTare As Nullable(Of Decimal)
    Public Property bitStampaStessoNuo As Boolean
    Public Property intNFS As Nullable(Of Integer)
    Public Property intContaPzUsciti As Decimal
    Public Property dblQuantitaUscita As Nullable(Of Double)
    Public Property bitTrasformato As Boolean
    Public Property bitTerminatoDaInventario As Boolean
    Public Property bitInCPLivello1 As Boolean
    Public Property KeyIdCartonePallets1 As Nullable(Of Decimal)
    Public Property bitInCPLivello2 As Boolean
    Public Property KeyIdCartonePallets2 As Nullable(Of Decimal)
    Public Property bitInCPLivello3 As Boolean
    Public Property KeyIdCartonePallets3 As Nullable(Of Decimal)
    Public Property bitEliminato As Boolean
    Public Property KeyIdSpedizioni As Nullable(Of Decimal)
    Public Property KeyIdFatture As Nullable(Of Decimal)
    Public Property ProgressivoPesata As Nullable(Of Short)
    Public Property ProgressivoLivello As Nullable(Of Short)

    Public Overridable Property Anag_Clienti As Anag_Clienti
    Public Overridable Property Anag_Clienti_Destinazioni As Anag_Clienti_Destinazioni
    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property Anag_Tare As Anag_Tare
    Public Overridable Property CaloPeso As ICollection(Of CaloPeso) = New HashSet(Of CaloPeso)
    Public Overridable Property CartonePallets As CartonePallets
    Public Overridable Property CartonePallets1 As CartonePallets
    Public Overridable Property CartonePallets2 As CartonePallets
    Public Overridable Property EsecuzioneUnioneLotti_Dettagli As ICollection(Of EsecuzioneUnioneLotti_Dettagli) = New HashSet(Of EsecuzioneUnioneLotti_Dettagli)
    Public Overridable Property Tare As Tare
    Public Overridable Property InVendita As ICollection(Of InVendita) = New HashSet(Of InVendita)
    Public Overridable Property Spedizioni_Dettagli As ICollection(Of Spedizioni_Dettagli) = New HashSet(Of Spedizioni_Dettagli)

End Class
