'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InParzializzazione_ContenitoriRiutilizzabili
    Public Property KeyId As Decimal
    Public Property KeyIdInParzializzazione As Decimal
    Public Property KeyIdAnag_ArticoliBarcode As Decimal
    Public Property bitLibero As Boolean

    Public Overridable Property Anag_ArticoliBarcode As Anag_ArticoliBarcode
    Public Overridable Property InParzializzazione As InParzializzazione

End Class
