'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Inventario
    Public Property KeyId As Decimal
    Public Property dateData As Date
    Public Property KeyIdAnag_Celle As Nullable(Of Decimal)
    Public Property KeyIdAnag_Operatori As Nullable(Of Decimal)
    Public Property intStato As Nullable(Of Short)
    Public Property strNota As String

    Public Overridable Property Inventario_Dettagli As ICollection(Of Inventario_Dettagli) = New HashSet(Of Inventario_Dettagli)

End Class
