'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InVendita
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Celle As Decimal
    Public Property KeyIdConferimenti As Nullable(Of Decimal)
    Public Property KeyIdSezionamenti As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Ricette As Nullable(Of Decimal)
    Public Property KeyIdContenitori As Nullable(Of Decimal)
    Public Property KeyIdInParzializzazione_Esecuzione As Nullable(Of Decimal)
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property KeyIdTraccAddizionale As Nullable(Of Decimal)
    Public Property bitTraccDinamica As Boolean
    Public Property KeyIdArticoliInBilance As Nullable(Of Decimal)
    Public Property KeyIdEsecuzioneUnioneLotti As Nullable(Of Decimal)
    Public Property strNuo As String
    Public Property dblQuantita As Double
    Public Property dblQuantitaDisponibile As Double
    Public Property KeyIdAnag_Um As Nullable(Of Decimal)
    Public Property dblPrezzoUnit As Nullable(Of Double)
    Public Property KeyIdAnag_Iva As Nullable(Of Decimal)
    Public Property dateDataOra As Date
    Public Property dateDataScadenza As Nullable(Of Date)
    Public Property intStato As Short
    Public Property bitTerminato As Boolean
    Public Property bitVariato As Boolean

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Celle As Anag_Celle
    Public Overridable Property Anag_IVA As Anag_IVA
    Public Overridable Property Anag_Um As Anag_Um
    Public Overridable Property Conferimenti As Conferimenti
    Public Overridable Property Contenitori As Contenitori
    Public Overridable Property EsecuzioneUnioneLotti As EsecuzioneUnioneLotti
    Public Overridable Property InParzializzazione_Esecuzione As InParzializzazione_Esecuzione
    Public Overridable Property KeyIdArticoliInBilance1 As KeyIdArticoliInBilance
    Public Overridable Property LavorazioniFasi_Ricette As LavorazioniFasi_Ricette
    Public Overridable Property Sezionamenti As Sezionamenti
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale

End Class
