'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Inventario_Dettagli
    Public Property KeyId As Decimal
    Public Property KeyIdInventario As Decimal
    Public Property strNuo As String
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property strDescrizioneArticolo As String
    Public Property KeyIdAnag_Um As Decimal
    Public Property dblQuantita As Nullable(Of Double)

    Public Overridable Property Anag_Um As Anag_Um
    Public Overridable Property Inventario As Inventario

End Class
