'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class KeyIdArticoliInBilance_Plu
    Public Property KeyId As Decimal
    Public Property KeyIdKeyIdArticoliInBilance As Decimal
    Public Property KeyIdAnag_Articoli As Decimal

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property KeyIdArticoliInBilance As KeyIdArticoliInBilance

End Class
