'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class KeyIdArticoliInBilance
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property bitContenitore As Boolean

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property InVendita As ICollection(Of InVendita) = New HashSet(Of InVendita)
    Public Overridable Property KeyIdArticoliInBilance_Plu As ICollection(Of KeyIdArticoliInBilance_Plu) = New HashSet(Of KeyIdArticoliInBilance_Plu)

End Class
