'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_VascheArtOut
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi_Vasche As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property intGiorniScadenza As Nullable(Of Integer)
    Public Property dateDataOra As Nullable(Of Date)
    Public Property strNuo As String
    Public Property dblQuantita As Nullable(Of Double)
    Public Property dblQuantitaDisponibile As Nullable(Of Double)
    Public Property KeyIdTracciabilitaAddizionale As Nullable(Of Decimal)
    Public Property KeyIdAnag_Celle As Nullable(Of Decimal)
    Public Property intStato As Short
    Public Property bitTerminatoDaInventario As Boolean
    Public Property KeyIdAnag_Clienti As Nullable(Of Decimal)
    Public Property KeyIdAnag_Clienti_Destinazioni As Nullable(Of Decimal)
    Public Property KeyIdAnag_Operatori As Decimal
    Public Property KeyIdOrdiniClienti As Nullable(Of Decimal)
    Public Property KeyIdOrdiniInterni As Nullable(Of Decimal)
    Public Property bitEliminato As Boolean

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Celle As Anag_Celle
    Public Overridable Property Anag_Clienti As Anag_Clienti
    Public Overridable Property Anag_Clienti_Destinazioni As Anag_Clienti_Destinazioni
    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property LavorazioniFasi_IngressoLotti As ICollection(Of LavorazioniFasi_IngressoLotti) = New HashSet(Of LavorazioniFasi_IngressoLotti)
    Public Overridable Property LavorazioniFasi_Vasche As LavorazioniFasi_Vasche
    Public Overridable Property LavorazioniFasi_VascheArtOut1 As LavorazioniFasi_VascheArtOut
    Public Overridable Property LavorazioniFasi_VascheArtOut2 As LavorazioniFasi_VascheArtOut
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale
    Public Overridable Property LavorazioniFasi_VascheImballi As ICollection(Of LavorazioniFasi_VascheImballi) = New HashSet(Of LavorazioniFasi_VascheImballi)
    Public Overridable Property LavorazioniFasi_VascheIngredienti As ICollection(Of LavorazioniFasi_VascheIngredienti) = New HashSet(Of LavorazioniFasi_VascheIngredienti)
    Public Overridable Property Spedizioni_Dettagli As ICollection(Of Spedizioni_Dettagli) = New HashSet(Of Spedizioni_Dettagli)

End Class
