'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_ConfezionamentoDImballi
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi_ConfezionamentoDArtOut As Decimal
    Public Property strNuo As String
    Public Property KeyIdConferimento As Decimal
    Public Property dblQuantita As Double
    Public Property bitEliminato As Boolean

    Public Overridable Property Conferimenti As Conferimenti
    Public Overridable Property LavorazioniFasi_ConfezionamentoDArtOut As LavorazioniFasi_ConfezionamentoDArtOut

End Class
