'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_Confezionamenti
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi As Decimal
    Public Property bitActiveScaricaDaDriverBilance As Boolean

    Public Overridable Property LavorazioniFasi As LavorazioniFasi
    Public Overridable Property LavorazioniFasi_ConfezionamentiArtIN As ICollection(Of LavorazioniFasi_ConfezionamentiArtIN) = New HashSet(Of LavorazioniFasi_ConfezionamentiArtIN)
    Public Overridable Property LavorazioniFasi_ConfezionamentiArtOUT As ICollection(Of LavorazioniFasi_ConfezionamentiArtOUT) = New HashSet(Of LavorazioniFasi_ConfezionamentiArtOUT)
    Public Overridable Property LavorazioniFasi_ConfezionamentiDriverBilance As ICollection(Of LavorazioniFasi_ConfezionamentiDriverBilance) = New HashSet(Of LavorazioniFasi_ConfezionamentiDriverBilance)

End Class
