'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_VascheArtIn
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi_Vasche As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property strNuo As String
    Public Property dblQuantita As Nullable(Of Double)
    Public Property KeyIdTracciabilitaAddizionale As Nullable(Of Decimal)
    Public Property dateDataOraInserimento As Nullable(Of Date)
    Public Property KeyIdAnag_Operatori As Decimal

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property LavorazioniFasi_Vasche As LavorazioniFasi_Vasche
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale

End Class
