'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_InsaccoImballiLotti
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi_InsaccoImballi As Decimal
    Public Property strNuo As String
    Public Property KeyIdTracciabilitaAddizionale As Decimal
    Public Property dblQuantita As Double

End Class
