'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_ImpastiAdditivi
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property KeyIdAnag_Um As Decimal
    Public Property intTipoAdditivo As Short
    Public Property dblQuantitaSuggerita As Nullable(Of Double)
    Public Property bitCalcolaPercentuale As Boolean

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Um As Anag_Um
    Public Overridable Property LavorazioniFasi As LavorazioniFasi
    Public Overridable Property LavorazioniFasi_ImpastiAdditiviLotti As ICollection(Of LavorazioniFasi_ImpastiAdditiviLotti) = New HashSet(Of LavorazioniFasi_ImpastiAdditiviLotti)

End Class
