'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_ConfezionamentoDArtOut
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi_ConfezionamentoD As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property dateDataOra As Nullable(Of Date)
    Public Property intGiorniScadenza As Nullable(Of Integer)
    Public Property strNuo As String
    Public Property bitEtichettaturaDiretta As Boolean
    Public Property bitPesoIntermedio As Boolean
    Public Property dblQuantitaDisponibile As Nullable(Of Double)
    Public Property KeyIdAnag_Celle As Nullable(Of Decimal)
    Public Property intStato As Short
    Public Property bitTerminatoDaInventario As Boolean
    Public Property dblQuantitaEtichettata As Nullable(Of Double)
    Public Property bitRimanenza As Boolean
    Public Property KeyIdTotalizzazioni As Nullable(Of Decimal)
    Public Property KeyIdTracciabilitaAddizionale As Nullable(Of Decimal)

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property CaloPeso As ICollection(Of CaloPeso) = New HashSet(Of CaloPeso)
    Public Overridable Property Contenitori_Dettagli As ICollection(Of Contenitori_Dettagli) = New HashSet(Of Contenitori_Dettagli)
    Public Overridable Property InParzializzazione As ICollection(Of InParzializzazione) = New HashSet(Of InParzializzazione)
    Public Overridable Property LavorazioniFasi_ConfezionamentoD As LavorazioniFasi_ConfezionamentoD
    Public Overridable Property Totalizzazione As Totalizzazione
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale
    Public Overridable Property LavorazioniFasi_ConfezionamentoDArtOutDettagli As ICollection(Of LavorazioniFasi_ConfezionamentoDArtOutDettagli) = New HashSet(Of LavorazioniFasi_ConfezionamentoDArtOutDettagli)
    Public Overridable Property LavorazioniFasi_ConfezionamentoDImballi As ICollection(Of LavorazioniFasi_ConfezionamentoDImballi) = New HashSet(Of LavorazioniFasi_ConfezionamentoDImballi)
    Public Overridable Property LavorazioniFasi_IngressoLotti As ICollection(Of LavorazioniFasi_IngressoLotti) = New HashSet(Of LavorazioniFasi_IngressoLotti)
    Public Overridable Property Spedizioni_Dettagli As ICollection(Of Spedizioni_Dettagli) = New HashSet(Of Spedizioni_Dettagli)

End Class
