'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_Carrelli
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi As Decimal
    Public Property KeyIdLavorazioniFasiProv As Nullable(Of Decimal)

    Public Overridable Property LavorazioniFasi As LavorazioniFasi
    Public Overridable Property LavorazioniFasi1 As LavorazioniFasi
    Public Overridable Property LavorazioniFasi_CarrelliDettagli As ICollection(Of LavorazioniFasi_CarrelliDettagli) = New HashSet(Of LavorazioniFasi_CarrelliDettagli)

End Class
