'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_Sezionamento
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi As Nullable(Of Decimal)
    Public Property KeyIdAnag_Articoli As Nullable(Of Decimal)
    Public Property dblPercentuale As Nullable(Of Double)
    Public Property KeyIdLavorazioniFasiSezionamento_Padre As Nullable(Of Decimal)
    Public Property intTipo As Short
    Public Property strDescrizioneScelta As String
    Public Property KeyIdAnag_ArticoliConfezionamenti As Nullable(Of Decimal)

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_ArticoliConfezionamenti As Anag_ArticoliConfezionamenti
    Public Overridable Property LavorazioniFasi As LavorazioniFasi
    Public Overridable Property LavorazioniFasi_Sezionamento1 As ICollection(Of LavorazioniFasi_Sezionamento) = New HashSet(Of LavorazioniFasi_Sezionamento)
    Public Overridable Property LavorazioniFasi_Sezionamento2 As LavorazioniFasi_Sezionamento
    Public Overridable Property Sezionamenti As ICollection(Of Sezionamenti) = New HashSet(Of Sezionamenti)

End Class
