'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_ImpastiAdditiviLotti
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi_ImpastiAdditivi As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property KeyIdTracciabilitaAddizionale As Nullable(Of Decimal)
    Public Property strNuo As String
    Public Property dblQuantita As Double

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property LavorazioniFasi_ImpastiAdditivi As LavorazioniFasi_ImpastiAdditivi
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale

End Class
