'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_IngressoLotti
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi As Decimal
    Public Property KeyIdConferimenti As Nullable(Of Decimal)
    Public Property KeyIdSezionamenti As Nullable(Of Decimal)
    Public Property KeyIdContenitori As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Ricette As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Destinazione As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Impasti As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Insacco As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_ConfezionamentoDArtOut As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_ArtOutPerAltreLav As Nullable(Of Decimal)
    Public Property KeyIdTracciabilitaAddizionale As Nullable(Of Decimal)
    Public Property KeyIdTracciabilitaAddizionaleNew As Nullable(Of Decimal)
    Public Property dateDataInserimento As Date
    Public Property dblQuantita As Nullable(Of Double)
    Public Property bitLetto As Boolean
    Public Property KeyIdLavorazioniFasi_VascheArtOut As Nullable(Of Decimal)

    Public Overridable Property Conferimenti As Conferimenti
    Public Overridable Property Contenitori As Contenitori
    Public Overridable Property LavorazioniFasi As LavorazioniFasi
    Public Overridable Property LavorazioniFasi_ArtOutPerAltreLav As LavorazioniFasi_ArtOutPerAltreLav
    Public Overridable Property LavorazioniFasi_ConfezionamentoDArtOut As LavorazioniFasi_ConfezionamentoDArtOut
    Public Overridable Property LavorazioniFasi_Destinazione As LavorazioniFasi_Destinazione
    Public Overridable Property LavorazioniFasi_Impasti As LavorazioniFasi_Impasti
    Public Overridable Property LavorazioniFasi_Insacco As LavorazioniFasi_Insacco
    Public Overridable Property LavorazioniFasi_Ricette As LavorazioniFasi_Ricette
    Public Overridable Property LavorazioniFasi_VascheArtOut As LavorazioniFasi_VascheArtOut
    Public Overridable Property Sezionamenti As Sezionamenti
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale
    Public Overridable Property TracciabilitaAddizionale1 As TracciabilitaAddizionale
    Public Overridable Property Sezionamenti1 As ICollection(Of Sezionamenti) = New HashSet(Of Sezionamenti)

End Class
