'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_ConfezionamentiArtIN
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi_Confezionamenti As Decimal
    Public Property KeyIdConferimenti As Nullable(Of Decimal)
    Public Property KeyIdSezionamenti As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Ricette As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Destinazione As Nullable(Of Decimal)
    Public Property strNuo As String
    Public Property KeyIdTracciabilitaAddizionale As Nullable(Of Decimal)
    Public Property bitLetto As Boolean
    Public Property dblQuantitaIn As Nullable(Of Double)
    Public Property dblQuantitaDisponibile As Nullable(Of Double)

    Public Overridable Property Conferimenti As Conferimenti
    Public Overridable Property LavorazioniFasi_Confezionamenti As LavorazioniFasi_Confezionamenti
    Public Overridable Property LavorazioniFasi_Destinazione As LavorazioniFasi_Destinazione
    Public Overridable Property LavorazioniFasi_Ricette As LavorazioniFasi_Ricette
    Public Overridable Property Sezionamenti As Sezionamenti
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale

End Class
