'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioni As Decimal
    Public Property intOrdine As Decimal
    Public Property strNuo As String
    Public Property KeyIdAnag_LavorazioniTipiLav As Decimal
    Public Property KeyIdLavorazioniFasi_SezDes As Decimal
    Public Property strNota As String
    Public Property intStato As Short
    Public Property KeyIdAnag_OperatoriPresaInCarico As Nullable(Of Decimal)
    Public Property bitCreataInAutomatico As Nullable(Of Boolean)
    Public Property dateDataInizioFase As Nullable(Of Date)
    Public Property dateDataFineFase As Nullable(Of Date)
    Public Property intMinutiPausa As Decimal
    Public Property bitFaseSaltata As Boolean

    Public Overridable Property Anag_LavorazioniTipiLav As Anag_LavorazioniTipiLav
    Public Overridable Property Contenitori As ICollection(Of Contenitori) = New HashSet(Of Contenitori)
    Public Overridable Property Contenitori_Dettagli As ICollection(Of Contenitori_Dettagli) = New HashSet(Of Contenitori_Dettagli)
    Public Overridable Property Lavorazioni As Lavorazioni
    Public Overridable Property LavorazioniFasi_ArtOutPerAltreLav As ICollection(Of LavorazioniFasi_ArtOutPerAltreLav) = New HashSet(Of LavorazioniFasi_ArtOutPerAltreLav)
    Public Overridable Property LavorazioniFasi_Carrelli As ICollection(Of LavorazioniFasi_Carrelli) = New HashSet(Of LavorazioniFasi_Carrelli)
    Public Overridable Property LavorazioniFasi_Carrelli1 As ICollection(Of LavorazioniFasi_Carrelli) = New HashSet(Of LavorazioniFasi_Carrelli)
    Public Overridable Property LavorazioniFasi_Confezionamenti As ICollection(Of LavorazioniFasi_Confezionamenti) = New HashSet(Of LavorazioniFasi_Confezionamenti)
    Public Overridable Property LavorazioniFasi_ConfezionamentoD As ICollection(Of LavorazioniFasi_ConfezionamentoD) = New HashSet(Of LavorazioniFasi_ConfezionamentoD)
    Public Overridable Property LavorazioniFasi_ConfSezionamento As ICollection(Of LavorazioniFasi_ConfSezionamento) = New HashSet(Of LavorazioniFasi_ConfSezionamento)
    Public Overridable Property LavorazioniFasi_ContSezionamento As ICollection(Of LavorazioniFasi_ContSezionamento) = New HashSet(Of LavorazioniFasi_ContSezionamento)
    Public Overridable Property LavorazioniFasi_Destinazione As ICollection(Of LavorazioniFasi_Destinazione) = New HashSet(Of LavorazioniFasi_Destinazione)
    Public Overridable Property LavorazioniFasi_Impasti As ICollection(Of LavorazioniFasi_Impasti) = New HashSet(Of LavorazioniFasi_Impasti)
    Public Overridable Property LavorazioniFasi_ImpastiAdditivi As ICollection(Of LavorazioniFasi_ImpastiAdditivi) = New HashSet(Of LavorazioniFasi_ImpastiAdditivi)
    Public Overridable Property LavorazioniFasi_IngressoLotti As ICollection(Of LavorazioniFasi_IngressoLotti) = New HashSet(Of LavorazioniFasi_IngressoLotti)
    Public Overridable Property LavorazioniFasi_Insacco As ICollection(Of LavorazioniFasi_Insacco) = New HashSet(Of LavorazioniFasi_Insacco)
    Public Overridable Property LavorazioniFasi_InsaccoImballi As ICollection(Of LavorazioniFasi_InsaccoImballi) = New HashSet(Of LavorazioniFasi_InsaccoImballi)
    Public Overridable Property LavorazioniFasi_Ricette_Eseguite As ICollection(Of LavorazioniFasi_Ricette_Eseguite) = New HashSet(Of LavorazioniFasi_Ricette_Eseguite)
    Public Overridable Property LavorazioniFasi_Ricette As ICollection(Of LavorazioniFasi_Ricette) = New HashSet(Of LavorazioniFasi_Ricette)
    Public Overridable Property LavorazioniFasi_SdlSezionamento As ICollection(Of LavorazioniFasi_SdlSezionamento) = New HashSet(Of LavorazioniFasi_SdlSezionamento)
    Public Overridable Property LavorazioniFasi_Sezionamento As ICollection(Of LavorazioniFasi_Sezionamento) = New HashSet(Of LavorazioniFasi_Sezionamento)
    Public Overridable Property LavorazioniFasi_Vasche As ICollection(Of LavorazioniFasi_Vasche) = New HashSet(Of LavorazioniFasi_Vasche)
    Public Overridable Property LavorazioniFasi_VascheFasiSecondarie As ICollection(Of LavorazioniFasi_VascheFasiSecondarie) = New HashSet(Of LavorazioniFasi_VascheFasiSecondarie)
    Public Overridable Property Ordini_Dettagli As ICollection(Of Ordini_Dettagli) = New HashSet(Of Ordini_Dettagli)
    Public Overridable Property Totalizzazione As ICollection(Of Totalizzazione) = New HashSet(Of Totalizzazione)

End Class
