'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_ConfezionamentoDArtOutDettagli
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi_ConfezionamentoDArtOut As Decimal
    Public Property dblQuantita As Nullable(Of Double)

    Public Overridable Property LavorazioniFasi_ConfezionamentoDArtOut As LavorazioniFasi_ConfezionamentoDArtOut

End Class
