'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_Vasche
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi As Decimal
    Public Property strNomeLayoutEtik As String
    Public Property strNuoPrecedente As String
    Public Property KeyIdAnag_Operatori As Nullable(Of Decimal)
    Public Property intStatoFase As Nullable(Of Short)
    Public Property dateDataApertura As Nullable(Of Date)
    Public Property dateDataChiusura As Nullable(Of Date)
    Public Property KeyIdAnag_Lavorazioni_Vasche As Decimal

    Public Overridable Property Anag_Lavorazioni_Vasche As Anag_Lavorazioni_Vasche
    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property LavorazioniFasi As LavorazioniFasi
    Public Overridable Property LavorazioniFasi_VascheArtIn As ICollection(Of LavorazioniFasi_VascheArtIn) = New HashSet(Of LavorazioniFasi_VascheArtIn)
    Public Overridable Property LavorazioniFasi_VascheArtOut As ICollection(Of LavorazioniFasi_VascheArtOut) = New HashSet(Of LavorazioniFasi_VascheArtOut)

End Class
