'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_Confezionamento_Carrelli
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasiConfezionamentoD As Decimal
    Public Property KeyIdLavorazioniFasiCarrelloDettagli As Decimal
    Public Property bitStampato As Boolean

    Public Overridable Property LavorazioniFasi_CarrelliDettagli As LavorazioniFasi_CarrelliDettagli
    Public Overridable Property LavorazioniFasi_ConfezionamentoD As LavorazioniFasi_ConfezionamentoD

End Class
