'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_ConfSezionamento
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi As Decimal
    Public Property bitPresezionamento As Nullable(Of Boolean)
    Public Property bitPresezionamentoEseguito As Nullable(Of Boolean)
    Public Property bitRistampaEtik As Nullable(Of Boolean)
    Public Property bitPesaRimanenzaAChiusura As Nullable(Of Boolean)
    Public Property intTipo As Nullable(Of Short)
    Public Property bitPesaNodoPadre As Boolean
    Public Property bitSezInLineaNoPadre As Boolean
    Public Property bitObbligoPesataScartiLavorazione As Nullable(Of Boolean)
    Public Property bitInvioAutomaticoScartoAChiusura As Nullable(Of Boolean)

    Public Overridable Property LavorazioniFasi As LavorazioniFasi

End Class
