'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_ArtOutPerAltreLav
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioni_Fasi As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property dateDataOperazione As Nullable(Of Date)
    Public Property strNuo As String
    Public Property KeyIdTraccAddizionale As Nullable(Of Decimal)

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property LavorazioniFasi As LavorazioniFasi
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale
    Public Overridable Property LavorazioniFasi_IngressoLotti As ICollection(Of LavorazioniFasi_IngressoLotti) = New HashSet(Of LavorazioniFasi_IngressoLotti)

End Class
