'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_Ricette_Eseguite
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi As Decimal
    Public Property KeyIdAnag_RicetteDettagliRif As Nullable(Of Decimal)
    Public Property KeyIdAnag_RicetteDettagli_ListaModificabiliRif As Nullable(Of Decimal)
    Public Property KeyIdConferimenti As Nullable(Of Decimal)
    Public Property KeyIdSezionamenti As Nullable(Of Decimal)
    Public Property KeyIdContenitori As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Ricette As Nullable(Of Decimal)
    Public Property intQtaInGr As Nullable(Of Decimal)
    Public Property intQtaSuggeritaInGr As Nullable(Of Decimal)
    Public Property bitEliminato As Boolean

    Public Overridable Property Anag_RicetteDettagli As Anag_RicetteDettagli
    Public Overridable Property Anag_RicetteDettagli_ListaModificabili As Anag_RicetteDettagli_ListaModificabili
    Public Overridable Property Conferimenti As Conferimenti
    Public Overridable Property Contenitori As Contenitori
    Public Overridable Property LavorazioniFasi As LavorazioniFasi
    Public Overridable Property LavorazioniFasi_Ricette As LavorazioniFasi_Ricette
    Public Overridable Property Sezionamenti As Sezionamenti

End Class
