'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_Ricette
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi As Decimal
    Public Property dblQuantitaDaPreprare As Nullable(Of Double)
    Public Property bitRiequilibrata As Nullable(Of Boolean)
    Public Property dblQuantitaPreparata As Nullable(Of Double)
    Public Property bitMultiProdotto As Nullable(Of Boolean)
    Public Property KeyIdAnag_ArticoloProdotto As Nullable(Of Decimal)
    Public Property KeyIdAnag_ArticoliConfezionamenti As Nullable(Of Decimal)
    Public Property strIngredientiAggiuntivi As String
    Public Property dblQuantitaDisponibile As Nullable(Of Double)
    Public Property KeyIdAnag_Tare As Nullable(Of Decimal)
    Public Property KeyIdTare As Nullable(Of Decimal)
    Public Property bitUtilizzata As Boolean
    Public Property KeyIdAnag_Celle As Nullable(Of Decimal)
    Public Property dateData As Nullable(Of Date)
    Public Property dateDataScadenza As Nullable(Of Date)
    Public Property strNuo As String
    Public Property intQtaDaConf As Nullable(Of Decimal)
    Public Property dblCostoLavDaConf As Nullable(Of Double)
    Public Property KeyIdLavorazioniFasi_RicetteProv As Nullable(Of Decimal)
    Public Property bitMultiEtichettatura As Nullable(Of Boolean)
    Public Property intNumEtichette As Nullable(Of Decimal)
    Public Property intContenutoEtichetta As Nullable(Of Decimal)
    Public Property intStato As Short
    Public Property bitTerminatoDaInventario As Boolean
    Public Property intTipoScomposizione As Short
    Public Property KeyIdAnag_Operatori As Nullable(Of Decimal)
    Public Property KeyIdSpedizioni As Nullable(Of Decimal)
    Public Property KeyIdFatture As Nullable(Of Decimal)

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_ArticoliConfezionamenti As Anag_ArticoliConfezionamenti
    Public Overridable Property Anag_Celle As Anag_Celle
    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property Anag_Tare As Anag_Tare
    Public Overridable Property CaloPeso As ICollection(Of CaloPeso) = New HashSet(Of CaloPeso)
    Public Overridable Property EsecuzioneUnioneLotti_Dettagli As ICollection(Of EsecuzioneUnioneLotti_Dettagli) = New HashSet(Of EsecuzioneUnioneLotti_Dettagli)
    Public Overridable Property InAreaLavorazione As ICollection(Of InAreaLavorazione) = New HashSet(Of InAreaLavorazione)
    Public Overridable Property InParzializzazione As ICollection(Of InParzializzazione) = New HashSet(Of InParzializzazione)
    Public Overridable Property InVendita As ICollection(Of InVendita) = New HashSet(Of InVendita)
    Public Overridable Property LavorazioniFasi As LavorazioniFasi
    Public Overridable Property LavorazioniFasi_ConfezionamentiArtIN As ICollection(Of LavorazioniFasi_ConfezionamentiArtIN) = New HashSet(Of LavorazioniFasi_ConfezionamentiArtIN)
    Public Overridable Property LavorazioniFasi_IngressoLotti As ICollection(Of LavorazioniFasi_IngressoLotti) = New HashSet(Of LavorazioniFasi_IngressoLotti)
    Public Overridable Property LavorazioniFasi_Ricette_Eseguite As ICollection(Of LavorazioniFasi_Ricette_Eseguite) = New HashSet(Of LavorazioniFasi_Ricette_Eseguite)
    Public Overridable Property LavorazioniFasi_Ricette_MultiEtik As ICollection(Of LavorazioniFasi_Ricette_MultiEtik) = New HashSet(Of LavorazioniFasi_Ricette_MultiEtik)
    Public Overridable Property Tare As Tare
    Public Overridable Property Spedizioni_Dettagli As ICollection(Of Spedizioni_Dettagli) = New HashSet(Of Spedizioni_Dettagli)

End Class
