'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasiCustom
    Public Property KeyId As Decimal
    Public Property dateDataOra As Date

    Public Overridable Property Lavorazioni As ICollection(Of Lavorazioni) = New HashSet(Of Lavorazioni)
    Public Overridable Property LavorazioniFasiCustom_Dettagli As ICollection(Of LavorazioniFasiCustom_Dettagli) = New HashSet(Of LavorazioniFasiCustom_Dettagli)
    Public Overridable Property PreLavorazioni As ICollection(Of PreLavorazioni) = New HashSet(Of PreLavorazioni)

End Class
