'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_CarrelliDettagli
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi_Carrelli As Decimal
    Public Property dateDataOra As Date
    Public Property KeyIdAnag_ContenitoriMobili As Nullable(Of Decimal)
    Public Property intNumCarrello As Short
    Public Property intNumPz As Integer
    Public Property KeyIdTare As Nullable(Of Decimal)
    Public Property intTaraInGr As Nullable(Of Integer)
    Public Property dblPesoLordo As Nullable(Of Double)
    Public Property bitEliminato As Boolean
    Public Property intNumPzDisponibili As Integer
    Public Property dblPesoSingoloPz As Double

    Public Overridable Property Anag_ContenitoriMobili As Anag_ContenitoriMobili
    Public Overridable Property LavorazioniFasi_Carrelli As LavorazioniFasi_Carrelli
    Public Overridable Property Tare As Tare
    Public Overridable Property LavorazioniFasi_Confezionamento_Carrelli As ICollection(Of LavorazioniFasi_Confezionamento_Carrelli) = New HashSet(Of LavorazioniFasi_Confezionamento_Carrelli)
    Public Overridable Property LavorazioniFasi_Destinazione As ICollection(Of LavorazioniFasi_Destinazione) = New HashSet(Of LavorazioniFasi_Destinazione)
    Public Overridable Property LavorazioniFasi_Insacco As ICollection(Of LavorazioniFasi_Insacco) = New HashSet(Of LavorazioniFasi_Insacco)

End Class
