'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_ConfezionamentiArtOUT
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi_Confezionamenti As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property intGiorniScadenza As Nullable(Of Integer)
    Public Property strNomeLayoutEtik As String

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property InParzializzazione As ICollection(Of InParzializzazione) = New HashSet(Of InParzializzazione)
    Public Overridable Property LavorazioniFasi_Confezionamenti As LavorazioniFasi_Confezionamenti

End Class
