'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_ConfezionamentoD
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi As Decimal
    Public Property intGiorniScadenza As Nullable(Of Integer)
    Public Property strNomeLayoutEtik As String
    Public Property strNuoPrecedente As String
    Public Property KeyIdTracciabilitaAddizionaleNew As Nullable(Of Decimal)
    Public Property KeyIdAnag_Celle As Nullable(Of Decimal)

    Public Overridable Property Anag_Celle As Anag_Celle
    Public Overridable Property LavorazioniFasi As LavorazioniFasi
    Public Overridable Property LavorazioniFasi_Confezionamento_Carrelli As ICollection(Of LavorazioniFasi_Confezionamento_Carrelli) = New HashSet(Of LavorazioniFasi_Confezionamento_Carrelli)
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale
    Public Overridable Property LavorazioniFasi_ConfezionamentoDArtOut As ICollection(Of LavorazioniFasi_ConfezionamentoDArtOut) = New HashSet(Of LavorazioniFasi_ConfezionamentoDArtOut)

End Class
