'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Lavorazioni
    Public Property KeyId As Decimal
    Public Property codePv As Nullable(Of Short)
    Public Property KeyIdAnag_Reparti As Decimal
    Public Property KeyIdAnag_Clienti As Nullable(Of Decimal)
    Public Property KeyIdAnag_OperatoriCreazione As Decimal
    Public Property intStato As Short
    Public Property KeyIdPreLavorazioni As Nullable(Of Decimal)
    Public Property KeyIdAnag_LavorazioniComplete As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasiCustom As Nullable(Of Decimal)
    Public Property dateDataInizio As Date
    Public Property dateDataFine As Nullable(Of Date)

    Public Overridable Property Anag_Clienti As Anag_Clienti
    Public Overridable Property Anag_LavorazioniComplete As Anag_LavorazioniComplete
    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property Anag_Pv As Anag_Pv
    Public Overridable Property Anag_Reparti As Anag_Reparti
    Public Overridable Property LavorazioniFasiCustom As LavorazioniFasiCustom
    Public Overridable Property PreLavorazioni As PreLavorazioni
    Public Overridable Property LavorazioniFasi As ICollection(Of LavorazioniFasi) = New HashSet(Of LavorazioniFasi)

End Class
