'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_Insacco
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi As Decimal
    Public Property KeyIdAnag_Articoli As Nullable(Of Decimal)
    Public Property strNuo As String
    Public Property dblQuantita As Nullable(Of Double)
    Public Property dblQuantitaTemp As Nullable(Of Double)
    Public Property dblQuantitaDisponibile As Nullable(Of Double)
    Public Property intNumPz As Nullable(Of Integer)
    Public Property intNumPzDisponibili As Nullable(Of Integer)
    Public Property KeyIdLavorazioniFasi_CarrelliDettagli As Nullable(Of Decimal)
    Public Property intStatoLocazioneFase As Nullable(Of Short)
    Public Property strNuoPrecedente As String
    Public Property bitTrasformato As Boolean
    Public Property bitEliminato As Boolean
    Public Property bitTerminatoDaInventario As Boolean
    Public Property dblPesoSingoloPz As Nullable(Of Double)
    Public Property KeyIdAnag_Celle As Nullable(Of Decimal)

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Celle As Anag_Celle
    Public Overridable Property LavorazioniFasi As LavorazioniFasi
    Public Overridable Property LavorazioniFasi_CarrelliDettagli As LavorazioniFasi_CarrelliDettagli
    Public Overridable Property LavorazioniFasi_IngressoLotti As ICollection(Of LavorazioniFasi_IngressoLotti) = New HashSet(Of LavorazioniFasi_IngressoLotti)
    Public Overridable Property Spedizioni_Dettagli As ICollection(Of Spedizioni_Dettagli) = New HashSet(Of Spedizioni_Dettagli)

End Class
