'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_Ricette_MultiEtik
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi_Ricette As Decimal
    Public Property strNuoEtik As String
    Public Property intNumeroCartone As Nullable(Of Integer)
    Public Property strNuoCartone As String
    Public Property bitComplessivo As Nullable(Of Boolean)
    Public Property dblQta As Nullable(Of Double)
    Public Property dblTara As Nullable(Of Double)
    Public Property bitFiscale As Nullable(Of Boolean)
    Public Property KeyIdAnag_Bilance As Nullable(Of Decimal)
    Public Property intNFS As Nullable(Of Integer)
    Public Property bitUtilizzata As Nullable(Of Boolean)

    Public Overridable Property LavorazioniFasi_Ricette As LavorazioniFasi_Ricette
    Public Overridable Property Spedizioni_Dettagli As ICollection(Of Spedizioni_Dettagli) = New HashSet(Of Spedizioni_Dettagli)

End Class
