'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LavorazioniFasi_ConfezionamentiDriverBilance
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi_Confezionamenti As Decimal
    Public Property KeyIdDriverBilance As Decimal
    Public Property bitArticoliInviati As Boolean

    Public Overridable Property DriverBilance As DriverBilance
    Public Overridable Property LavorazioniFasi_Confezionamenti As LavorazioniFasi_Confezionamenti

End Class
