'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Listini
    Public Property KeyId As Decimal
    Public Property intTipo As Short
    Public Property strCodice As String
    Public Property strDescrizione As String
    Public Property bitDefault As Boolean
    Public Property dateDataInizioValidita As Nullable(Of Date)
    Public Property dateDataFineValidita As Nullable(Of Date)
    Public Property dateDataCreazione As Date
    Public Property dateDataModifica As Date
    Public Property KeyIdListiniRif As Nullable(Of Decimal)
    Public Property intTipoValoreCalcolo As Nullable(Of Short)
    Public Property dblValorePerc As Nullable(Of Double)
    Public Property bitBloccaPrezzi As Boolean
    Public Property bitNascosto As Boolean
    Public Property bitEliminato As Boolean
    Public Property KeyIdCE As Nullable(Of Decimal)
    Public Property KeyIdAnagCassa As Nullable(Of Decimal)

    Public Overridable Property Listini_Associazione As ICollection(Of Listini_Associazione) = New HashSet(Of Listini_Associazione)
    Public Overridable Property Listini1 As ICollection(Of Listini) = New HashSet(Of Listini)
    Public Overridable Property Listini2 As Listini
    Public Overridable Property ListiniDettagli As ICollection(Of ListiniDettagli) = New HashSet(Of ListiniDettagli)

End Class
