'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ListiniDettagli
    Public Property KeyId As Decimal
    Public Property KeyIdListini As Decimal
    Public Property KeyIdListiniDettagliRif As Nullable(Of Decimal)
    Public Property strCodiceInterno As String
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property KeyIdAnag_Um As Decimal
    Public Property intQtaDa As Nullable(Of Double)
    Public Property intQtaA As Nullable(Of Double)
    Public Property dblPrezzo As Double
    Public Property intTipoValoreCalcolo As Nullable(Of Short)
    Public Property dblValorePerc As Nullable(Of Double)
    Public Property dateDataInserimento As Date
    Public Property dateDataModifica As Date
    Public Property strNota As String
    Public Property bitBloccaPrezzo As Boolean
    Public Property bitEliminato As Boolean
    Public Property KeyIdCE As Nullable(Of Decimal)
    Public Property bitStampaModifica As Boolean

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Um As Anag_Um
    Public Overridable Property Listini As Listini
    Public Overridable Property ListiniDettagli1 As ICollection(Of ListiniDettagli) = New HashSet(Of ListiniDettagli)
    Public Overridable Property ListiniDettagli2 As ListiniDettagli
    Public Overridable Property ListiniDettagli_Media As ICollection(Of ListiniDettagli_Media) = New HashSet(Of ListiniDettagli_Media)
    Public Overridable Property Ordini_Dettagli As ICollection(Of Ordini_Dettagli) = New HashSet(Of Ordini_Dettagli)

End Class
