'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Listini_Associazione
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Clienti As Nullable(Of Decimal)
    Public Property KeyIdAnag_Fornitori As Nullable(Of Decimal)
    Public Property KeyIdAnag_Celle As Nullable(Of Decimal)
    Public Property KeyIdListini As Decimal

    Public Overridable Property Anag_Celle As Anag_Celle
    Public Overridable Property Anag_Clienti As Anag_Clienti
    Public Overridable Property Anag_Fornitori As Anag_Fornitori
    Public Overridable Property Listini As Listini

End Class
