'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LottiInCucina_Dettagli
    Public Property KeyId As Decimal
    Public Property KeyIdLottiInCucina As Decimal
    Public Property KeyIdAnag_Operatori As Decimal
    Public Property dateDataOperazione As Date
    Public Property KeyIdConferimenti_MultiEtik As Decimal
    Public Property intPorzioni As Decimal

    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property Conferimenti_MultiEtik As Conferimenti_MultiEtik
    Public Overridable Property LottiInCucina As LottiInCucina

End Class
