'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LottoUnicoAperto
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Aree As Nullable(Of Decimal)
    Public Property strNuo As String
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property KeyIdTracciabilitaAddizionale As Decimal
    Public Property dblQuantita As Double
    Public Property dblQuantitaDisponibile As Double
    Public Property dblPercTolleranza As Double
    Public Property intStato As Short
    Public Property dateDataIngresso As Date
    Public Property dateDataApertura As Date
    Public Property dateDataScadenza As Nullable(Of Date)
    Public Property KeyIdAnag_Operatori As Decimal

    Public Overridable Property Anag_Aree As Anag_Aree
    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale

End Class
