'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LottiInCucina
    Public Property KeyId As Decimal
    Public Property dateDataInizio As Date
    Public Property dateDataFine As Nullable(Of Date)
    Public Property KeyIdAnag_Articoli As Nullable(Of Decimal)
    Public Property intPorzioniDisponibili As Nullable(Of Decimal)
    Public Property strNote As String
    Public Property bitTerminato As Boolean
    Public Property KeyIdAnag_OperatoriFine As Nullable(Of Decimal)
    Public Property bitNascosto As Boolean

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property LottiInCucina_Dettagli As ICollection(Of LottiInCucina_Dettagli) = New HashSet(Of LottiInCucina_Dettagli)

End Class
