'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MaschereTr_Campi
    Public Property KeyId As Decimal
    Public Property KeyIdMaschereTr As Nullable(Of Decimal)
    Public Property KeyIdAnag_Riga0 As Nullable(Of Decimal)
    Public Property intTipo As Nullable(Of Decimal)
    Public Property strAi As String
    Public Property bitCampoObbligatorio As Nullable(Of Boolean)
    Public Property bitCampoNonIndispensabile As Nullable(Of Boolean)
    Public Property KeyIdCE As Nullable(Of Decimal)
    Public Property strColonnaSeuropDettagli As String
    Public Property intColonnaSeuropDettagli As String
    Public Property bitSeuropCercaNazioni As Boolean
    Public Property intTipo2 As Nullable(Of Decimal)
    Public Property bitClassificazione As Boolean

    Public Overridable Property Anag_Riga0 As Anag_Riga0
    Public Overridable Property MaschereTr As MaschereTr
    Public Overridable Property MaschereTr_Campi_Lista As ICollection(Of MaschereTr_Campi_Lista) = New HashSet(Of MaschereTr_Campi_Lista)

End Class
