'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MaschereTr_Campi_Lista
    Public Property KeyId As Decimal
    Public Property KeyIdMaschereTr_Campi As Nullable(Of Decimal)
    Public Property strDescrizione As String
    Public Property KeyIdCE As Nullable(Of Decimal)

    Public Overridable Property MaschereTr_Campi As MaschereTr_Campi

End Class
