'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MaschereTr
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Reparti As Nullable(Of Decimal)
    Public Property strDescrizione As String
    Public Property KeyIdCE As Nullable(Of Decimal)
    Public Property bitEliminato As Nullable(Of Boolean)
    Public Property bitCambioArticolo As Boolean

    Public Overridable Property Anag_Articoli As ICollection(Of Anag_Articoli) = New HashSet(Of Anag_Articoli)
    Public Overridable Property Anag_Decodifica_Articoli As ICollection(Of Anag_Decodifica_Articoli) = New HashSet(Of Anag_Decodifica_Articoli)
    Public Overridable Property Anag_Reparti As Anag_Reparti
    Public Overridable Property Conferimenti As ICollection(Of Conferimenti) = New HashSet(Of Conferimenti)
    Public Overridable Property DdtAcquisto_Dettagli As ICollection(Of DdtAcquisto_Dettagli) = New HashSet(Of DdtAcquisto_Dettagli)
    Public Overridable Property MaschereTr_Campi As ICollection(Of MaschereTr_Campi) = New HashSet(Of MaschereTr_Campi)
    Public Overridable Property TracciabilitaAddizionale As ICollection(Of TracciabilitaAddizionale) = New HashSet(Of TracciabilitaAddizionale)

End Class
