'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MovimentiMagazzino
    Public Property KeyId As Decimal
    Public Property codeAnag_CausaliMagazzino As Nullable(Of Integer)
    Public Property codeIdAnag_TipoDocumento As Nullable(Of Decimal)
    Public Property strNumDoc As String
    Public Property KeyIdAnag_Fornitori As Nullable(Of Decimal)
    Public Property dateDataDoc As Nullable(Of Date)
    Public Property strNuoMov As String
    Public Property strNuoProv As String
    Public Property strNuoDest As String
    Public Property codePv As Nullable(Of Short)
    Public Property intTipo As Short
    Public Property KeyIdAnag_Articoli As Nullable(Of Decimal)
    Public Property KeyIdAnag_Ricette As Nullable(Of Decimal)
    Public Property dblQuantita As Nullable(Of Double)
    Public Property dblPrezzo As Nullable(Of Double)
    Public Property dblImporto As Nullable(Of Double)
    Public Property KeyIdAnag_Iva As Nullable(Of Decimal)
    Public Property KeyIdTracciabilitaAddizionale As Nullable(Of Decimal)
    Public Property bitEliminato As Boolean
    Public Property bitEsportato As Boolean
    Public Property KeyIdAnag_CelleA As Nullable(Of Decimal)
    Public Property bitPuoiProcessare As Boolean
    Public Property strTipoDocumentoLibero As String
    Public Property strCausaleLibera As String
    Public Property CodiceCellaPostTravaso As String
    Public Property bitPassareGestionaleEsterno As Boolean

    Public Overridable Property Anag_CausaliMagazzino As Anag_CausaliMagazzino
    Public Overridable Property Anag_Celle As Anag_Celle
    Public Overridable Property Anag_Fornitori As Anag_Fornitori
    Public Overridable Property Anag_IVA As Anag_IVA
    Public Overridable Property Anag_Ricette As Anag_Ricette
    Public Overridable Property Anag_TipoDocumento As Anag_TipoDocumento
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale

End Class
