'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ordini
    Public Property KeyId As Decimal
    Public Property intNumSerie As Nullable(Of Integer)
    Public Property intNumOrdine As Nullable(Of Integer)
    Public Property intAnno As Nullable(Of Short)
    Public Property codePv As Nullable(Of Short)
    Public Property KeyIdAnag_Cliente As Nullable(Of Decimal)
    Public Property KeyIdAnag_Clienti_Destinazioni As Nullable(Of Decimal)
    Public Property KeyIdAnag_Fornitori As Nullable(Of Decimal)
    Public Property dateDataOrdine As Date
    Public Property dateDataConsegna As Nullable(Of Date)
    Public Property oraConsegna As Nullable(Of System.TimeSpan)
    Public Property KeyIdAnag_Operatori As Nullable(Of Decimal)
    Public Property codeStatoOrdine As Short
    Public Property strNota As String
    Public Property codeIdTipoPagamento As Nullable(Of Short)
    Public Property strCodiceVettore As String
    Public Property strCodicePorto As String
    Public Property strCodiceAgente As String
    Public Property bitEvaso As Boolean
    Public Property bitEliminato As Boolean
    Public Property intTipoOrdine As Short

    Public Overridable Property Anag_Clienti As Anag_Clienti
    Public Overridable Property Anag_Fornitori As Anag_Fornitori
    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property Anag_Pv As Anag_Pv
    Public Overridable Property Ordini_Dettagli_Note As ICollection(Of Ordini_Dettagli_Note) = New HashSet(Of Ordini_Dettagli_Note)
    Public Overridable Property TipoPagamento As TipoPagamento
    Public Overridable Property Ordini_DDT_Fatture As ICollection(Of Ordini_DDT_Fatture) = New HashSet(Of Ordini_DDT_Fatture)
    Public Overridable Property Ordini_Dettagli As ICollection(Of Ordini_Dettagli) = New HashSet(Of Ordini_Dettagli)
    Public Overridable Property StatiOrdini As StatiOrdini
    Public Overridable Property Spedizioni As ICollection(Of Spedizioni) = New HashSet(Of Spedizioni)
    Public Overridable Property tmpConfigConferimentiFluidi As ICollection(Of tmpConfigConferimentiFluidi) = New HashSet(Of tmpConfigConferimentiFluidi)
    Public Overridable Property TrasferimentoInterno As ICollection(Of TrasferimentoInterno) = New HashSet(Of TrasferimentoInterno)

End Class
