'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ordini_Dettagli
    Public Property KeyId As Decimal
    Public Property KeyIdOrdini As Nullable(Of Decimal)
    Public Property intNumRiga As Nullable(Of Integer)
    Public Property KeyIdListiniDettagli As Nullable(Of Decimal)
    Public Property KeyIdAnag_Articoli As Nullable(Of Decimal)
    Public Property strDescrizioneArticolo As String
    Public Property strCodiceArticoloCliente As String
    Public Property strDescrizioneArticoloCliente As String
    Public Property KeyIdAnag_UmOrdine As Nullable(Of Decimal)
    Public Property KeyIdAnag_UmVendita As Nullable(Of Decimal)
    Public Property dblQuantitaRichiesta As Nullable(Of Double)
    Public Property dblQuantitaConfermata As Nullable(Of Double)
    Public Property dblPrezzoUnit As Nullable(Of Double)
    Public Property dblPercentualeIva As Nullable(Of Double)
    Public Property strNota As String
    Public Property percSco1 As Nullable(Of Double)
    Public Property percSco2 As Nullable(Of Double)
    Public Property percSco3 As Nullable(Of Double)
    Public Property percProv As Nullable(Of Double)
    Public Property bitOmaggioEsenteIva As Nullable(Of Boolean)
    Public Property bitOmaggio As Nullable(Of Boolean)
    Public Property bitComandato As Boolean
    Public Property bitModificato As Boolean
    Public Property intStato As Short
    Public Property KeyIdLavorazioniFasi As Nullable(Of Decimal)
    Public Property bitStatoRigaEvasa As Boolean
    Public Property intProgressivoLotto As Nullable(Of Integer)

    Public Overridable Property LavorazioniFasi As LavorazioniFasi
    Public Overridable Property ListiniDettagli As ListiniDettagli
    Public Overridable Property Ordini As Ordini
    Public Overridable Property TrasferimentoInterno_Dettagli As ICollection(Of TrasferimentoInterno_Dettagli) = New HashSet(Of TrasferimentoInterno_Dettagli)

End Class
