'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ordini_DDT_Fatture
    Public Property KeyId As Decimal
    Public Property KeyIdOrdini As Nullable(Of Decimal)
    Public Property KeyIdSpedizioni As Nullable(Of Decimal)
    Public Property KeyIdFatture As Nullable(Of Decimal)

    Public Overridable Property Fatture As Fatture
    Public Overridable Property Ordini As Ordini
    Public Overridable Property Spedizioni_Dettagli As Spedizioni_Dettagli

End Class
