'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ordini_Dettagli_Note
    Public Property KeyId As Decimal
    Public Property KeyIdOrdini As Nullable(Of Decimal)
    Public Property intNumRiga As Nullable(Of Integer)
    Public Property strNota As String
    Public Property strTipo As String

    Public Overridable Property Ordini As Ordini

End Class
