'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PoolDiStampa
    Public Property KeyId As Decimal
    Public Property strNuo As String
    Public Property KeyIdAnag_Stampanti As Decimal
    Public Property strDescrizioneStampante As String
    Public Property intProgressivo As Decimal
    Public Property dateDataOra As Date
    Public Property KeyIdAnag_Operatori As Decimal
    Public Property bitEseguito As Boolean
    Public Property dateDataOraEseguito As Nullable(Of Date)

    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property Anag_Stampanti As Anag_Stampanti

End Class
