'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PoolExportedToMTRepo
    Public Property KeyId As Decimal
    Public Property dateDataOra As Date
    Public Property KeyIdSpedizioni As Decimal

    Public Overridable Property Spedizioni As Spedizioni

End Class
