'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PreLavorazioni
    Public Property KeyId As Decimal
    Public Property dateDataInserimento As Date
    Public Property KeyIdAnag_Operatori As Decimal
    Public Property KeyIdAnag_LavorazioniComplete As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasiCustom As Nullable(Of Decimal)
    Public Property strNota As String
    Public Property dblQuantita As Double
    Public Property dblQuantitaRichiesta As Double
    Public Property dblCapContenitore As Double
    Public Property dateDataPartenza As Date
    Public Property intNumCarrelliPreparati As Nullable(Of Integer)
    Public Property bitTrasformato As Boolean
    Public Property bitEliminato As Boolean

    Public Overridable Property Anag_LavorazioniComplete As Anag_LavorazioniComplete
    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property Lavorazioni As ICollection(Of Lavorazioni) = New HashSet(Of Lavorazioni)
    Public Overridable Property LavorazioniFasiCustom As LavorazioniFasiCustom
    Public Overridable Property PreLavorazioniDatiDaSerb As ICollection(Of PreLavorazioniDatiDaSerb) = New HashSet(Of PreLavorazioniDatiDaSerb)
    Public Overridable Property PreLavorazioniDettagli As ICollection(Of PreLavorazioniDettagli) = New HashSet(Of PreLavorazioniDettagli)

End Class
