'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PreLavorazioniDatiDaSerb
    Public Property KeyId As Decimal
    Public Property KeyIdPreLavorazioni As Decimal
    Public Property intNumVagone As Integer
    Public Property KeyIdNuo As Decimal
    Public Property strNuo As String
    Public Property dblQuantita As Double
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property KeyIdTraccAddizionale As Decimal

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property PreLavorazioni As PreLavorazioni
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale

End Class
