'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PreLavorazioniDettagli
    Public Property KeyId As Decimal
    Public Property KeyIdPrelavorazioni As Decimal
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property KeyIdAnag_Um As Decimal
    Public Property dblQuantita As Double

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Um As Anag_Um
    Public Overridable Property PreLavorazioni As PreLavorazioni

End Class
