'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PrimaNota
    Public Property KeyId As Decimal
    Public Property numOperazione As Decimal
    Public Property dateDataOperazione As Date
    Public Property codeCausale As Integer
    Public Property strNumDoc As String
    Public Property KeyIdSezionali As Nullable(Of Decimal)
    Public Property CFKeyIdAnag_Clienti As Nullable(Of Decimal)
    Public Property CFKeyIdAnag_Clienti_Destinazioni As Nullable(Of Decimal)
    Public Property CFKeyIdAnag_Fornitori As Nullable(Of Decimal)
    Public Property CFdblEntrata As Nullable(Of Double)
    Public Property CFdblUscita As Nullable(Of Double)
    Public Property CAdblEntrata As Nullable(Of Double)
    Public Property CAdblUscita As Nullable(Of Double)
    Public Property BA1Entrata As Nullable(Of Double)
    Public Property BA1Uscita As Nullable(Of Double)
    Public Property KeyIdSpedizioni As Nullable(Of Decimal)
    Public Property bitProcessatoDareAvere As Boolean
    Public Property bitEliminato As Boolean
    Public Property strNota As String

    Public Overridable Property Anag_Clienti As Anag_Clienti
    Public Overridable Property Anag_Clienti_Destinazioni As Anag_Clienti_Destinazioni
    Public Overridable Property Anag_Fornitori As Anag_Fornitori
    Public Overridable Property Spedizioni As Spedizioni

End Class
