'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Progressivi
    Public Property KeyId As Decimal
    Public Property codePv As Nullable(Of Short)
    Public Property intTipo As Short
    Public Property KeyIdAnag_Articoli As Nullable(Of Decimal)
    Public Property KeyIdAnag_Ricette As Nullable(Of Decimal)
    Public Property KeyIdTracciabilitaAddizionale As Nullable(Of Decimal)
    Public Property Carichi As Nullable(Of Decimal)
    Public Property Scarichi As Nullable(Of Decimal)
    Public Property CarichiCL As Nullable(Of Decimal)
    Public Property ScarichiCL As Nullable(Of Decimal)
    Public Property OrdinatoC As Nullable(Of Decimal)
    Public Property OrdinatoF As Nullable(Of Decimal)
    Public Property bitTerminatoDaInventario As Boolean

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Pv As Anag_Pv
    Public Overridable Property Anag_Ricette As Anag_Ricette
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale

End Class
