'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sezionali
    Public Property KeyId As Decimal
    Public Property codePv As Nullable(Of Short)
    Public Property codeIdAnag_TipoDocumento As Nullable(Of Decimal)
    Public Property strDescrizione As String
    Public Property strCodice As String
    Public Property intProgressivoDa As Nullable(Of Long)
    Public Property intAnno As Nullable(Of Short)
    Public Property bitB As Boolean
    Public Property bitInContabilita As Boolean
    Public Property bitEsportaMovimento As Boolean

    Public Overridable Property Anag_Pv As Anag_Pv
    Public Overridable Property Anag_TipoDocumento As Anag_TipoDocumento
    Public Overridable Property Fatture As ICollection(Of Fatture) = New HashSet(Of Fatture)
    Public Overridable Property Spedizioni As ICollection(Of Spedizioni) = New HashSet(Of Spedizioni)

End Class
