'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SezionamentiImballi
    Public Property KeyId As Decimal
    Public Property KeyIdSezionamento As Nullable(Of Decimal)
    Public Property KeyIdAnag_Lav_SezImb As Nullable(Of Decimal)
    Public Property strCodImballo As String

    Public Overridable Property Anag_Lav_SezImb As Anag_Lav_SezImb
    Public Overridable Property Sezionamenti As Sezionamenti

End Class
