'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sezionamenti
    Public Property KeyId As Decimal
    Public Property codePv As Nullable(Of Short)
    Public Property strNuoLavorazioniFasi As String
    Public Property KeyIdLavorazioniFasi_Sezionamento As Nullable(Of Decimal)
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property KeyIdAnag_Celle As Nullable(Of Decimal)
    Public Property KeyIdAnag_Operatori As Decimal
    Public Property KeyIdAnag_Postazioni As Decimal
    Public Property dblQuantita As Double
    Public Property dblQuantitaRicavata As Nullable(Of Double)
    Public Property dblQuantitaDisponibile As Double
    Public Property dblSecondoPeso As Nullable(Of Double)
    Public Property KeyIdAnag_Tare As Nullable(Of Decimal)
    Public Property KeyIdTare As Nullable(Of Decimal)
    Public Property strNuo As String
    Public Property dateDataOperazione As Date
    Public Property dateDataScadenza As Nullable(Of Date)
    Public Property intStatoLocazioneFase As Short
    Public Property bitPresezionamento As Boolean
    Public Property bitPresezionamentoChiuso As Boolean
    Public Property bitProcessato As Boolean
    Public Property bitTrasformato As Boolean
    Public Property bitTerminatoDaInventario As Boolean
    Public Property bitEliminato As Boolean
    Public Property KeyIdSezionamentiProv As Nullable(Of Decimal)
    Public Property KeyIdSpedizioni As Nullable(Of Decimal)
    Public Property KeyIdFatture As Nullable(Of Decimal)
    Public Property KeyIdTracciabilitaAddizionale As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_IngressoLotti As Nullable(Of Decimal)

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Celle As Anag_Celle
    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property Anag_Postazioni As Anag_Postazioni
    Public Overridable Property Anag_Pv As Anag_Pv
    Public Overridable Property Anag_Tare As Anag_Tare
    Public Overridable Property CaloPeso As ICollection(Of CaloPeso) = New HashSet(Of CaloPeso)
    Public Overridable Property CambioArticolo As ICollection(Of CambioArticolo) = New HashSet(Of CambioArticolo)
    Public Overridable Property Contenitori_Dettagli As ICollection(Of Contenitori_Dettagli) = New HashSet(Of Contenitori_Dettagli)
    Public Overridable Property EsecuzioneUnioneLotti_Dettagli As ICollection(Of EsecuzioneUnioneLotti_Dettagli) = New HashSet(Of EsecuzioneUnioneLotti_Dettagli)
    Public Overridable Property Fatture As Fatture
    Public Overridable Property InAreaLavorazione As ICollection(Of InAreaLavorazione) = New HashSet(Of InAreaLavorazione)
    Public Overridable Property InParzializzazione As ICollection(Of InParzializzazione) = New HashSet(Of InParzializzazione)
    Public Overridable Property InVendita As ICollection(Of InVendita) = New HashSet(Of InVendita)
    Public Overridable Property LavorazioniFasi_ConfezionamentiArtIN As ICollection(Of LavorazioniFasi_ConfezionamentiArtIN) = New HashSet(Of LavorazioniFasi_ConfezionamentiArtIN)
    Public Overridable Property LavorazioniFasi_IngressoLotti As ICollection(Of LavorazioniFasi_IngressoLotti) = New HashSet(Of LavorazioniFasi_IngressoLotti)
    Public Overridable Property LavorazioniFasi_IngressoLotti1 As LavorazioniFasi_IngressoLotti
    Public Overridable Property LavorazioniFasi_Ricette_Eseguite As ICollection(Of LavorazioniFasi_Ricette_Eseguite) = New HashSet(Of LavorazioniFasi_Ricette_Eseguite)
    Public Overridable Property LavorazioniFasi_Sezionamento As LavorazioniFasi_Sezionamento
    Public Overridable Property Spedizioni As Spedizioni
    Public Overridable Property Tare As Tare
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale
    Public Overridable Property SezionamentiImballi As ICollection(Of SezionamentiImballi) = New HashSet(Of SezionamentiImballi)
    Public Overridable Property Spedizioni_Dettagli As ICollection(Of Spedizioni_Dettagli) = New HashSet(Of Spedizioni_Dettagli)

End Class
