'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Spedizioni
    Public Property KeyId As Decimal
    Public Property strNuo As String
    Public Property KeyIdOrdiniClienti As Nullable(Of Decimal)
    Public Property KeyIdAnag_Cliente As Decimal
    Public Property KeyIdAnag_Clienti_Destinazioni As Nullable(Of Decimal)
    Public Property dateData As Date
    Public Property dateDataConsegna As Nullable(Of Date)
    Public Property orarioConsegna As Nullable(Of System.TimeSpan)
    Public Property KeyIdSezionali As Decimal
    Public Property strCodiceSezionale As String
    Public Property intNumDDT As Nullable(Of Integer)
    Public Property intAnno As Nullable(Of Short)
    Public Property codeIdAnag_Causali As Nullable(Of Decimal)
    Public Property intNumColli As Nullable(Of Decimal)
    Public Property KeyIdAnag_Operatori As Decimal
    Public Property KeyIdFatture As Nullable(Of Decimal)
    Public Property bitFileGenerato As Boolean
    Public Property bitExportedToWeb As Boolean
    Public Property bitExportedToMTRepo As Boolean
    Public Property bitStampatoAuto As Nullable(Of Boolean)
    Public Property bitConfermato As Boolean
    Public Property bitRientrato As Boolean
    Public Property KeyIdSpedizioniProv As Nullable(Of Decimal)
    Public Property codeAnag_CausaliMagazzino As Integer
    Public Property intTipoUscitaMerce As Short
    Public Property strTipoDocumentoLibero As String
    Public Property strCausaleLibera As String
    Public Property bitStampatoRiepilogoAuto As Nullable(Of Boolean)
    Public Property strNotaFailedExport As String
    Public Property intTipoFailureExport As Nullable(Of Short)

    Public Overridable Property Anag_Causali_Trasp As Anag_Causali_Trasp
    Public Overridable Property Anag_CausaliMagazzino As Anag_CausaliMagazzino
    Public Overridable Property Anag_Clienti As Anag_Clienti
    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property Conferimenti As ICollection(Of Conferimenti) = New HashSet(Of Conferimenti)
    Public Overridable Property Contenitori As ICollection(Of Contenitori) = New HashSet(Of Contenitori)
    Public Overridable Property Fatture As Fatture
    Public Overridable Property Ordini As Ordini
    Public Overridable Property PoolExportedToMTRepo As ICollection(Of PoolExportedToMTRepo) = New HashSet(Of PoolExportedToMTRepo)
    Public Overridable Property PrimaNota As ICollection(Of PrimaNota) = New HashSet(Of PrimaNota)
    Public Overridable Property Sezionali As Sezionali
    Public Overridable Property Sezionamenti As ICollection(Of Sezionamenti) = New HashSet(Of Sezionamenti)
    Public Overridable Property Spedizioni_AspettoEsterioreBeni As ICollection(Of Spedizioni_AspettoEsterioreBeni) = New HashSet(Of Spedizioni_AspettoEsterioreBeni)
    Public Overridable Property Spedizioni_Dettagli As ICollection(Of Spedizioni_Dettagli) = New HashSet(Of Spedizioni_Dettagli)
    Public Overridable Property Spedizioni1 As ICollection(Of Spedizioni) = New HashSet(Of Spedizioni)
    Public Overridable Property Spedizioni2 As Spedizioni
    Public Overridable Property SpedizioniAnag_Clienti As SpedizioniAnag_Clienti

End Class
