'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Spedizioni_Dettagli
    Public Property KeyId As Decimal
    Public Property KeyIdSpedizioni As Decimal
    Public Property intTipoMerce As Short
    Public Property KeyIdAnag_Articolo As Decimal
    Public Property strCodiceArticolo As String
    Public Property strDescrizioneArticolo As String
    Public Property strCodiceArticoloCliente As String
    Public Property strDescrizioneArticoloCliente As String
    Public Property KeyIdConferimenti As Nullable(Of Decimal)
    Public Property KeyIdSezionamenti As Nullable(Of Decimal)
    Public Property KeyIdContenitori As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Ricette As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Ricette_MultiEtik As Nullable(Of Decimal)
    Public Property KeyIdInParzializzazione_Esecuzione As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_ConfezionamentoDArtOut As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Destinazione As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Impasti As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Insacco As Nullable(Of Decimal)
    Public Property KeyIdCartonePallets As Nullable(Of Decimal)
    Public Property KeyIdEsecuzioneUnioneLotti As Nullable(Of Decimal)
    Public Property dblQuantita As Double
    Public Property intNumPesate As Nullable(Of Decimal)
    Public Property KeyIdTare As Nullable(Of Decimal)
    Public Property dblPrezzoUnit As Nullable(Of Double)
    Public Property dblPercentualeIva As Nullable(Of Double)
    Public Property dblPrezzoUnitIva As Nullable(Of Double)
    Public Property intTipoPrezzoUnitPartenza As Short
    Public Property KeyIdAnag_Um As Decimal
    Public Property percSco1 As Nullable(Of Double)
    Public Property percSco2 As Nullable(Of Double)
    Public Property percSco3 As Nullable(Of Double)
    Public Property percProv As Nullable(Of Double)
    Public Property bitOmaggioEsenteIva As Nullable(Of Boolean)
    Public Property bitOmaggio As Nullable(Of Boolean)
    Public Property bitEliminato As Boolean
    Public Property bitRientrato As Boolean
    Public Property KeyIdFatture As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_VascheArtOut As Nullable(Of Decimal)

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Um As Anag_Um
    Public Overridable Property CartonePallets As CartonePallets
    Public Overridable Property Contenitori As Contenitori
    Public Overridable Property EsecuzioneUnioneLotti As EsecuzioneUnioneLotti
    Public Overridable Property Fatture As Fatture
    Public Overridable Property InParzializzazione_Esecuzione As InParzializzazione_Esecuzione
    Public Overridable Property LavorazioniFasi_ConfezionamentoDArtOut As LavorazioniFasi_ConfezionamentoDArtOut
    Public Overridable Property LavorazioniFasi_Destinazione As LavorazioniFasi_Destinazione
    Public Overridable Property LavorazioniFasi_Impasti As LavorazioniFasi_Impasti
    Public Overridable Property LavorazioniFasi_Insacco As LavorazioniFasi_Insacco
    Public Overridable Property LavorazioniFasi_Ricette As LavorazioniFasi_Ricette
    Public Overridable Property LavorazioniFasi_Ricette_MultiEtik As LavorazioniFasi_Ricette_MultiEtik
    Public Overridable Property LavorazioniFasi_VascheArtOut As LavorazioniFasi_VascheArtOut
    Public Overridable Property Ordini_DDT_Fatture As ICollection(Of Ordini_DDT_Fatture) = New HashSet(Of Ordini_DDT_Fatture)
    Public Overridable Property Sezionamenti As Sezionamenti
    Public Overridable Property Spedizioni As Spedizioni
    Public Overridable Property Tare As Tare

End Class
