'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Spedizioni_AspettoEsterioreBeni
    Public Property KeyId As Decimal
    Public Property KeyIdSpedizioni As Decimal
    Public Property KeyIdAnag_AspettoEsterioreBeni As Decimal

    Public Overridable Property Anag_AspettoEsterioreBeni As Anag_AspettoEsterioreBeni
    Public Overridable Property Spedizioni As Spedizioni

End Class
