'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SpedizioniAnag_Clienti
    Public Property KeyId As Decimal
    Public Property strCodice As String
    Public Property strRagioneSociale As String
    Public Property strIndirizzo As String
    Public Property strCap As String
    Public Property strCitta As String
    Public Property strProvincia As String
    Public Property strCodFiscale As String
    Public Property strPIva As String
    Public Property Cod_MacroArea As String
    Public Property Cod_Area As String
    Public Property Cod_Zona As String
    Public Property strTelefono As String
    Public Property strMobile As String
    Public Property strNome As String
    Public Property strCognome As String
    Public Property strCodiceLingua As String
    Public Property strCodiceDestinazione As String
    Public Property strIndirizzoDestinazione As String
    Public Property strCapDestinazione As String
    Public Property strCittaDestinazione As String
    Public Property strProvinciaDestinazione As String
    Public Property strMail As String
    Public Property strMailPec As String

    Public Overridable Property Spedizioni As Spedizioni

End Class
