'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class StatiOrdini
    Public Property code As Short
    Public Property strDescrizione As String

    Public Overridable Property Ordini As ICollection(Of Ordini) = New HashSet(Of Ordini)

End Class
