'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Storico_LavorazioniFasiRicette
    Public Property KeyId As Decimal
    Public Property KeyIdLavorazioniFasi As Nullable(Of Decimal)
    Public Property dblQuantitaDaPreprare As Nullable(Of Double)
    Public Property bitRiequilibrata As Nullable(Of Boolean)
    Public Property dblQuantitaPreparata As Nullable(Of Double)
    Public Property bitMultiProdotto As Nullable(Of Boolean)
    Public Property KeyIdAnag_ArticoloProdotto As Nullable(Of Decimal)
    Public Property KeyIdAnag_ArticoliConfezionamenti As Nullable(Of Decimal)
    Public Property strIngredientiAggiuntivi As String
    Public Property dblQuantitaDisponibile As Nullable(Of Double)
    Public Property KeyIdAnag_Tare As Nullable(Of Decimal)
    Public Property bitUtilizzata As Nullable(Of Boolean)
    Public Property KeyIdAnag_Celle As Nullable(Of Decimal)
    Public Property dateData As Nullable(Of Date)
    Public Property dateDataScadenza As Nullable(Of Date)
    Public Property strNuo As String
    Public Property intQtaDaConf As Nullable(Of Decimal)
    Public Property dblCostoLavDaConf As Nullable(Of Double)
    Public Property KeyIdLavorazioniFasi_RicetteProv As Nullable(Of Decimal)
    Public Property bitMultiEtichettatura As Nullable(Of Boolean)
    Public Property intNumEtichette As Nullable(Of Decimal)
    Public Property intContenutoEtichetta As Nullable(Of Decimal)
    Public Property intStato As Nullable(Of Short)
    Public Property bitTerminatoDaInventario As Nullable(Of Boolean)
    Public Property intTipoScomposizione As Nullable(Of Short)
    Public Property KeyIdAnag_Operatori As Nullable(Of Decimal)
    Public Property KeyIdSpedizioni As Nullable(Of Decimal)
    Public Property KeyIdFatture As Nullable(Of Decimal)
    Public Property strTipoOperazione As String
    Public Property dateDataOra As Nullable(Of Date)

End Class
