'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Storico_Contenitori
    Public Property KeyId As Decimal
    Public Property codePv As Nullable(Of Short)
    Public Property KeyIdLavorazioniFasi As Nullable(Of Decimal)
    Public Property KeyIdAnag_Articoli As Nullable(Of Decimal)
    Public Property strNuo As String
    Public Property dateDataCreazione As Nullable(Of Date)
    Public Property dateDataScadenza As Nullable(Of Date)
    Public Property dblQuantita As Nullable(Of Double)
    Public Property dblQuantitaDisponibile As Nullable(Of Double)
    Public Property KeyIdAnag_Tare As Nullable(Of Decimal)
    Public Property intStato As Nullable(Of Short)
    Public Property bitTerminatoDaInventario As Nullable(Of Boolean)
    Public Property KeyIdAnag_Celle As Nullable(Of Decimal)
    Public Property KeyIdAnag_Operatori As Nullable(Of Decimal)
    Public Property KeyIdContenitoriProv As Nullable(Of Decimal)
    Public Property KeyIdSpedizioni As Nullable(Of Decimal)
    Public Property KeyIdFatture As Nullable(Of Decimal)
    Public Property strTipoOperazione As String
    Public Property dateDataOra As Nullable(Of Date)

End Class
