'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Storico_InParzializzazioneEsecuzione
    Public Property KeyId As Decimal
    Public Property KeyIdInParzializzazione As Nullable(Of Decimal)
    Public Property KeyIdAnag_Clienti As Nullable(Of Decimal)
    Public Property KeyIdAnag_Celle As Nullable(Of Decimal)
    Public Property KeyIdAnag_Operatori As Nullable(Of Decimal)
    Public Property strNuo As String
    Public Property dateDataOperazione As Nullable(Of Date)
    Public Property dateDataScadenza As Nullable(Of Date)
    Public Property intStatoLocazione As Nullable(Of Short)
    Public Property dblQuantita As Nullable(Of Double)
    Public Property dblQuantitaDisponibile As Nullable(Of Double)
    Public Property dblPrezzoUnit As Nullable(Of Double)
    Public Property KeyIdAnag_Bilance As Nullable(Of Decimal)
    Public Property KeyIdAnag_Tare As Nullable(Of Decimal)
    Public Property bitStampaStessoNuo As Nullable(Of Boolean)
    Public Property intNFS As Nullable(Of Integer)
    Public Property intContaPzUsciti As Nullable(Of Decimal)
    Public Property dblQuantitaUscita As Nullable(Of Double)
    Public Property bitTrasformato As Nullable(Of Boolean)
    Public Property bitTerminatoDaInventario As Nullable(Of Boolean)
    Public Property bitEliminato As Nullable(Of Boolean)
    Public Property KeyIdSpedizioni As Nullable(Of Decimal)
    Public Property KeyIdFatture As Nullable(Of Decimal)
    Public Property strTipoOperazione As String
    Public Property dateDataOra As Nullable(Of Date)

End Class
