'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Storico_RegistraQuantita
    Public Property KeyId As Decimal
    Public Property strNuo As String
    Public Property dblQta As Double
    Public Property KeyIdAnag_Operatori As Decimal

    Public Overridable Property Anag_Operatori As Anag_Operatori

End Class
