'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Storico_Conferimenti
    Public Property KeyId As Decimal
    Public Property codePv As Nullable(Of Short)
    Public Property KeyIdMaschereTr As Nullable(Of Decimal)
    Public Property KeyIdTracciabilitaAddizionale As Nullable(Of Decimal)
    Public Property KeyIdAnag_Articoli As Nullable(Of Decimal)
    Public Property KeyIdAnag_Fornitori As Nullable(Of Decimal)
    Public Property strNumDDT As String
    Public Property KeyIdAnag_Fieliere As Nullable(Of Decimal)
    Public Property KeyIdAnag_Celle As Nullable(Of Decimal)
    Public Property KeyIdAnag_Operatori As Nullable(Of Decimal)
    Public Property KeyIdAnag_Postazioni As Nullable(Of Decimal)
    Public Property dblQuantita As Nullable(Of Double)
    Public Property dblQuantitaDisponibile As Nullable(Of Double)
    Public Property KeyIdAnag_Tare As Nullable(Of Decimal)
    Public Property strNuo As String
    Public Property strIngredienti As String
    Public Property strAllergeni As String
    Public Property dateDataIngresso As Nullable(Of Date)
    Public Property dateDataScadenza As Nullable(Of Date)
    Public Property intStatoVisivoCamion As Nullable(Of Short)
    Public Property intStatoVisivoTrasportatore As Nullable(Of Short)
    Public Property intTemperaturaCamion As Nullable(Of Decimal)
    Public Property intTemparaturaMerce As Nullable(Of Decimal)
    Public Property intTemperaturaPhMerce As Nullable(Of Decimal)
    Public Property intStatoLocazioneFase As Nullable(Of Decimal)
    Public Property bitProcessato As Nullable(Of Boolean)
    Public Property bitEliminato As Nullable(Of Boolean)
    Public Property bitTrasformato As Nullable(Of Boolean)
    Public Property bitTerminatoDaInventario As Nullable(Of Boolean)
    Public Property bitUtilizzabile As Nullable(Of Boolean)
    Public Property strCodicePreconferimento As String
    Public Property KeyIdSpedizioni As Nullable(Of Decimal)
    Public Property KeyIdFatture As Nullable(Of Decimal)
    Public Property bitDaReso As Nullable(Of Boolean)
    Public Property KeyIdDdtAcquisto As Nullable(Of Decimal)
    Public Property KeyIdDdtAcquisto_Dettagli As Nullable(Of Decimal)
    Public Property dblPrezzoAcquisto As Nullable(Of Double)
    Public Property strLottoLavorazione As String
    Public Property KeyIdConferimentiProv As Nullable(Of Decimal)
    Public Property strTipoOperazione As String
    Public Property dateDataOra As Nullable(Of Date)

End Class
