'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Storico_PesiPlc
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Plc As Nullable(Of Decimal)
    Public Property KeyIdAnag_Serbatoio As Nullable(Of Decimal)
    Public Property dblPeso As Nullable(Of Double)
    Public Property intTipoOperazioneSerbatoi As Nullable(Of Short)
    Public Property dateDataOperazione As Nullable(Of Date)
    Public Property intTipoOperazionePlc As Nullable(Of Short)
    Public Property intTipoCausaleOperazione As Nullable(Of Short)

    Public Overridable Property Anag_Plc As Anag_Plc
    Public Overridable Property Anag_Serbatoi As Anag_Serbatoi

End Class
