'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tare_Dettagli
    Public Property KeyId As Decimal
    Public Property KeyIdTare As Decimal
    Public Property intTipo As Short
    Public Property KeyIdAnag_Articoli As Nullable(Of Decimal)
    Public Property KeyIdAnag_Tare As Nullable(Of Decimal)
    Public Property intPesoInGr As Integer
    Public Property intNumPz As Integer
    Public Property intPesoTotaleInGr As Integer

    Public Overridable Property Tare As Tare

End Class
