'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tare
    Public Property KeyId As Decimal
    Public Property dataOra As Date
    Public Property KeyIdAnag_Operatore As Decimal

    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property Conferimenti As ICollection(Of Conferimenti) = New HashSet(Of Conferimenti)
    Public Overridable Property InParzializzazione_Esecuzione As ICollection(Of InParzializzazione_Esecuzione) = New HashSet(Of InParzializzazione_Esecuzione)
    Public Overridable Property LavorazioniFasi_CarrelliDettagli As ICollection(Of LavorazioniFasi_CarrelliDettagli) = New HashSet(Of LavorazioniFasi_CarrelliDettagli)
    Public Overridable Property LavorazioniFasi_Ricette As ICollection(Of LavorazioniFasi_Ricette) = New HashSet(Of LavorazioniFasi_Ricette)
    Public Overridable Property Sezionamenti As ICollection(Of Sezionamenti) = New HashSet(Of Sezionamenti)
    Public Overridable Property Spedizioni_Dettagli As ICollection(Of Spedizioni_Dettagli) = New HashSet(Of Spedizioni_Dettagli)
    Public Overridable Property Tare_Dettagli As ICollection(Of Tare_Dettagli) = New HashSet(Of Tare_Dettagli)
    Public Overridable Property tmpUscitaMerceManuale As ICollection(Of tmpUscitaMerceManuale) = New HashSet(Of tmpUscitaMerceManuale)

End Class
