'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TaskSchedule
    Public Property KeyId As Decimal
    Public Property strComando As String
    Public Property dateUltimaEsecuzione As Nullable(Of Date)
    Public Property bitRipetiOgni As Boolean
    Public Property intRipetiOgni As Nullable(Of Decimal)
    Public Property bitEseguiAdOgniAvvio As Boolean
    Public Property bitEseguiAdOrario As Boolean
    Public Property intOra As Nullable(Of Integer)
    Public Property intMinuti As Nullable(Of Integer)
    Public Property bitTaskAttivato As Boolean

End Class
