'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TipoImportTrac
    Public Property codeTipoImportTrac As Short
    Public Property descTipoImportTrac As String

    Public Overridable Property Anag_Fornitori As ICollection(Of Anag_Fornitori) = New HashSet(Of Anag_Fornitori)
    Public Overridable Property DdtAcquisto As ICollection(Of DdtAcquisto) = New HashSet(Of DdtAcquisto)

End Class
