'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TipoPagamento
    Public Property codeId As Short
    Public Property strDescrizione As String
    Public Property intNumRate As Nullable(Of Decimal)
    Public Property bitFineMese As Nullable(Of Boolean)
    Public Property intNumGiorniTraRate As Nullable(Of Decimal)
    Public Property strCodiceModPaga As String

    Public Overridable Property Anag_Clienti As ICollection(Of Anag_Clienti) = New HashSet(Of Anag_Clienti)
    Public Overridable Property Anag_Fornitori As ICollection(Of Anag_Fornitori) = New HashSet(Of Anag_Fornitori)
    Public Overridable Property Fatture As ICollection(Of Fatture) = New HashSet(Of Fatture)
    Public Overridable Property Ordini As ICollection(Of Ordini) = New HashSet(Of Ordini)

End Class
