'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tmpConferimentiFluidi
    Public Property KeyId As Decimal
    Public Property KeyIdTmpConfigConferimentiFluidi As Decimal
    Public Property KeyIdAnag_Serbatoi As Decimal
    Public Property KeyIdAnag_Operatori As Decimal
    Public Property dateDataInizio As Date
    Public Property dateDataFine As Nullable(Of Date)
    Public Property bitIngresso As Boolean
    Public Property bitPrelievo As Boolean
    Public Property dblQuantita As Nullable(Of Double)
    Public Property KeyIdConferimento As Nullable(Of Decimal)
    Public Property strNuo As String
    Public Property bitEliminato As Boolean
    Public Property bitProcessato As Boolean
    Public Property bitTrasferimentoInterno As Nullable(Of Boolean)
    Public Property KeyIdContenitore As Nullable(Of Decimal)
    Public Property KeyIdAnag_Magazzini_Da As Nullable(Of Decimal)
    Public Property KeyIdAnag_Magazzini_A As Nullable(Of Decimal)
    Public Property bitPrelievoPerContenitore As Boolean

    Public Overridable Property Anag_Magazzini As Anag_Magazzini
    Public Overridable Property Anag_Magazzini1 As Anag_Magazzini
    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property Anag_Serbatoi As Anag_Serbatoi
    Public Overridable Property Conferimenti As Conferimenti
    Public Overridable Property Contenitori As ICollection(Of Contenitori) = New HashSet(Of Contenitori)
    Public Overridable Property Contenitori1 As Contenitori
    Public Overridable Property tmpConfigConferimentiFluidi As tmpConfigConferimentiFluidi

End Class
