'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tmpConfigConferimentiFluidiDettagli
    Public Property KeyId As Decimal
    Public Property KeyIdTmpConfigConferimentiFluidi As Decimal
    Public Property KeyIdAnag_Serbatoi As Decimal
    Public Property intOrdine As Integer

    Public Overridable Property Anag_Serbatoi As Anag_Serbatoi
    Public Overridable Property tmpConfigConferimentiFluidi As tmpConfigConferimentiFluidi

End Class
