'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tmpConfigConferimentiFluidi
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Operatori As Decimal
    Public Property dateDataOperazione As Date
    Public Property bitIngresso As Boolean
    Public Property bitPrelievo As Boolean
    Public Property bitEliminato As Boolean
    Public Property bitProcessato As Boolean
    Public Property KeyIdAnag_Clienti As Nullable(Of Decimal)
    Public Property KeyIdAnag_Clienti_Destinazioni As Nullable(Of Decimal)
    Public Property KeyIdOrdini As Nullable(Of Decimal)
    Public Property KeyIdDdtAcquisto As Nullable(Of Decimal)
    Public Property bitTrasferimentoInterno As Boolean
    Public Property bitCaloPeso As Boolean
    Public Property bitPrelievoPerContenitore As Boolean

    Public Overridable Property Anag_Clienti As Anag_Clienti
    Public Overridable Property Anag_Clienti_Destinazioni As Anag_Clienti_Destinazioni
    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property DdtAcquisto As DdtAcquisto
    Public Overridable Property Ordini As Ordini
    Public Overridable Property tmpConferimentiFluidi As ICollection(Of tmpConferimentiFluidi) = New HashSet(Of tmpConferimentiFluidi)
    Public Overridable Property tmpConfigConferimentiFluidiDettagli As ICollection(Of tmpConfigConferimentiFluidiDettagli) = New HashSet(Of tmpConfigConferimentiFluidiDettagli)

End Class
