'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tmpInventario
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Operatori As Nullable(Of Decimal)
    Public Property codePv As Short
    Public Property dateDataOperazione As Date
    Public Property KeyIdConferimenti As Nullable(Of Decimal)
    Public Property KeyIdSezionamenti As Nullable(Of Decimal)
    Public Property KeyIdContenitori As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Ricette As Nullable(Of Decimal)
    Public Property KeyIdInParzializzazione_Esecuzione As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_ConfezionamentoDArtOut As Nullable(Of Decimal)
    Public Property strNuo As String
    Public Property dblQuantita As Double
    Public Property intTipo As Short
    Public Property KeyIdAnag_Articoli As Nullable(Of Decimal)
    Public Property KeyIdAnag_Ricette As Nullable(Of Decimal)
    Public Property KeyIdTracciabilitaAddizionale As Nullable(Of Decimal)
    Public Property bitProcessato As Boolean
    Public Property bitEliminato As Boolean
    Public Property KeyIdLavorazioniFasi_VascheArtOut As Nullable(Of Decimal)
    Public Property intTipoInventario As Short

End Class
