'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tmpTrasferimentoInterno_Dettagli
    Public Property KeyId As Decimal
    Public Property KeyIdOrdini As Nullable(Of Decimal)
    Public Property strNuo As String
    Public Property KeyIdAnag_Articoli As Nullable(Of Decimal)
    Public Property dblQuantita As Nullable(Of Double)
    Public Property KeyIdAnag_Um As Nullable(Of Decimal)
    Public Property KeyIdTraccAddizionale As Nullable(Of Decimal)
    Public Property intTipoTrasferimento As Nullable(Of Short)

End Class
