'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tmpUscitaMerceManuale
    Public Property KeyId As Decimal
    Public Property KeyIdOrdiniClienti As Nullable(Of Decimal)
    Public Property KeyIdAnag_Clienti As Decimal
    Public Property KeyIdAnag_Clienti_Destinazioni As Nullable(Of Decimal)
    Public Property strNuo As String
    Public Property strNuoNuovo As String
    Public Property intTipoMerce As Short
    Public Property KeyIdConferimenti As Nullable(Of Decimal)
    Public Property KeyIdSezionamenti As Nullable(Of Decimal)
    Public Property KeyIdContenitori As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Ricette As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Ricette_MultiEtik As Nullable(Of Decimal)
    Public Property KeyIdInParzializzazione_Esecuzione As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_ConfezionamentoDArtOut As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Destinazione As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Impasti As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi_Insacco As Nullable(Of Decimal)
    Public Property KeyIdCartonePallets As Nullable(Of Decimal)
    Public Property dblQuantita As Nullable(Of Double)
    Public Property KeyIdTare As Nullable(Of Decimal)
    Public Property KeyIdAnag_Bilance As Nullable(Of Decimal)
    Public Property intNFS As Nullable(Of Integer)
    Public Property dblPrezzoUnit As Nullable(Of Double)
    Public Property strBarcode As String
    Public Property KeyIdAnag_Um As Nullable(Of Decimal)
    Public Property bitQtaRistabilita As Nullable(Of Boolean)
    Public Property bitProcessato As Nullable(Of Boolean)
    Public Property bitNuoDedicato As Boolean
    Public Property dateDataOra As Nullable(Of Date)
    Public Property intTipoUscitaMerce As Short
    Public Property KeyIdLavorazioniFasi_VascheArtOut As Nullable(Of Decimal)

    Public Overridable Property Anag_Bilance As Anag_Bilance
    Public Overridable Property Tare As Tare

End Class
