'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Totalizzazione
    Public Property KeyId As Decimal
    Public Property codePv As Nullable(Of Short)
    Public Property KeyIdTracciabilitaAddizionale As Nullable(Of Decimal)
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property KeyIdAnag_Celle As Nullable(Of Decimal)
    Public Property KeyIdLavorazioniFasi As Nullable(Of Decimal)
    Public Property strNuo As String
    Public Property datDataOra As Nullable(Of Date)
    Public Property dblQuantita As Double
    Public Property dblQuantitaDisponibile As Nullable(Of Double)

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Celle As Anag_Celle
    Public Overridable Property Anag_Pv As Anag_Pv
    Public Overridable Property LavorazioniFasi As LavorazioniFasi
    Public Overridable Property LavorazioniFasi_ConfezionamentoDArtOut As ICollection(Of LavorazioniFasi_ConfezionamentoDArtOut) = New HashSet(Of LavorazioniFasi_ConfezionamentoDArtOut)
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale

End Class
