'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TracciabilitaAddizionale_Dettagli
    Public Property KeyId As Decimal
    Public Property KeyIdTracciabilitaAddizionale As Decimal
    Public Property KeyIdAnag_Riga0 As Nullable(Of Decimal)
    Public Property strIntestazione As String
    Public Property strValore As String
    Public Property intIndice As Nullable(Of Integer)
    Public Property bitCampoNonIndispensabile As Nullable(Of Boolean)

    Public Overridable Property Anag_Riga0 As Anag_Riga0
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale

End Class
