'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TracciabilitaAddizionale
    Public Property keyId As Decimal
    Public Property KeyIdMaschereTr As Nullable(Of Decimal)
    Public Property strLotto As String
    Public Property dateDataOra As Nullable(Of Date)
    Public Property KeyIdGW As Nullable(Of Decimal)

    Public Overridable Property CambioArticolo As ICollection(Of CambioArticolo) = New HashSet(Of CambioArticolo)
    Public Overridable Property CambioArticolo1 As ICollection(Of CambioArticolo) = New HashSet(Of CambioArticolo)
    Public Overridable Property CartonePallets As ICollection(Of CartonePallets) = New HashSet(Of CartonePallets)
    Public Overridable Property Conferimenti As ICollection(Of Conferimenti) = New HashSet(Of Conferimenti)
    Public Overridable Property DdtAcquisto_Dettagli As ICollection(Of DdtAcquisto_Dettagli) = New HashSet(Of DdtAcquisto_Dettagli)
    Public Overridable Property EsecuzioneUnioneLotti As ICollection(Of EsecuzioneUnioneLotti) = New HashSet(Of EsecuzioneUnioneLotti)
    Public Overridable Property EsecuzioneUnioneLotti_Dettagli As ICollection(Of EsecuzioneUnioneLotti_Dettagli) = New HashSet(Of EsecuzioneUnioneLotti_Dettagli)
    Public Overridable Property InVendita As ICollection(Of InVendita) = New HashSet(Of InVendita)
    Public Overridable Property LavorazioniFasi_ArtOutPerAltreLav As ICollection(Of LavorazioniFasi_ArtOutPerAltreLav) = New HashSet(Of LavorazioniFasi_ArtOutPerAltreLav)
    Public Overridable Property LavorazioniFasi_ConfezionamentiArtIN As ICollection(Of LavorazioniFasi_ConfezionamentiArtIN) = New HashSet(Of LavorazioniFasi_ConfezionamentiArtIN)
    Public Overridable Property LavorazioniFasi_ConfezionamentoD As ICollection(Of LavorazioniFasi_ConfezionamentoD) = New HashSet(Of LavorazioniFasi_ConfezionamentoD)
    Public Overridable Property LavorazioniFasi_ConfezionamentoDArtOut As ICollection(Of LavorazioniFasi_ConfezionamentoDArtOut) = New HashSet(Of LavorazioniFasi_ConfezionamentoDArtOut)
    Public Overridable Property LavorazioniFasi_ImpastiAdditiviLotti As ICollection(Of LavorazioniFasi_ImpastiAdditiviLotti) = New HashSet(Of LavorazioniFasi_ImpastiAdditiviLotti)
    Public Overridable Property LavorazioniFasi_IngressoLotti As ICollection(Of LavorazioniFasi_IngressoLotti) = New HashSet(Of LavorazioniFasi_IngressoLotti)
    Public Overridable Property LavorazioniFasi_IngressoLotti1 As ICollection(Of LavorazioniFasi_IngressoLotti) = New HashSet(Of LavorazioniFasi_IngressoLotti)
    Public Overridable Property LavorazioniFasi_VascheArtIn As ICollection(Of LavorazioniFasi_VascheArtIn) = New HashSet(Of LavorazioniFasi_VascheArtIn)
    Public Overridable Property LavorazioniFasi_VascheArtOut As ICollection(Of LavorazioniFasi_VascheArtOut) = New HashSet(Of LavorazioniFasi_VascheArtOut)
    Public Overridable Property LavorazioniFasi_VascheFasiSecondarie As ICollection(Of LavorazioniFasi_VascheFasiSecondarie) = New HashSet(Of LavorazioniFasi_VascheFasiSecondarie)
    Public Overridable Property LavorazioniFasi_VascheIngredienti As ICollection(Of LavorazioniFasi_VascheIngredienti) = New HashSet(Of LavorazioniFasi_VascheIngredienti)
    Public Overridable Property LottoUnicoAperto As ICollection(Of LottoUnicoAperto) = New HashSet(Of LottoUnicoAperto)
    Public Overridable Property MaschereTr As MaschereTr
    Public Overridable Property MovimentiMagazzino As ICollection(Of MovimentiMagazzino) = New HashSet(Of MovimentiMagazzino)
    Public Overridable Property PreLavorazioniDatiDaSerb As ICollection(Of PreLavorazioniDatiDaSerb) = New HashSet(Of PreLavorazioniDatiDaSerb)
    Public Overridable Property Progressivi As ICollection(Of Progressivi) = New HashSet(Of Progressivi)
    Public Overridable Property Sezionamenti As ICollection(Of Sezionamenti) = New HashSet(Of Sezionamenti)
    Public Overridable Property Totalizzazione As ICollection(Of Totalizzazione) = New HashSet(Of Totalizzazione)
    Public Overridable Property TracciabilitaAddizionale_Dettagli As ICollection(Of TracciabilitaAddizionale_Dettagli) = New HashSet(Of TracciabilitaAddizionale_Dettagli)
    Public Overridable Property TrasferimentoInterno_Dettagli As ICollection(Of TrasferimentoInterno_Dettagli) = New HashSet(Of TrasferimentoInterno_Dettagli)

End Class
