'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Traduzioni_Parole
    Public Property KeyId As Decimal
    Public Property strParola As String
    Public Property strCodiceLingua As String
    Public Property strTraduzione As String

    Public Overridable Property Anag_Lingue As Anag_Lingue

End Class
