'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TransazioniCasse
    Public Property KeyId As Decimal
    Public Property KeyIdDongle As Nullable(Of Decimal)
    Public Property dateDataOra As Date
    Public Property intTipoTransazione As Integer
    Public Property intMetodoDiPagamento As Integer
    Public Property intNumScontrino As Integer
    Public Property intNumOperatore As Nullable(Of Integer)
    Public Property KeyIdAnag_Articoli As Nullable(Of Decimal)
    Public Property strDescrizione As String
    Public Property KeyIdAnag_IVA As Decimal
    Public Property KeyIdAnag_Um As Decimal
    Public Property dblQuantita As Double
    Public Property dblImporto As Double
    Public Property dblImportoTotale As Double
    Public Property intStato As Short
    Public Property KeyIdAnag_OperatorePresaInCarico As Nullable(Of Decimal)
    Public Property KeyIdAnag_Coupon As Nullable(Of Decimal)
    Public Property strNuo As String
    Public Property KeyIdAnag_Clienti As Nullable(Of Decimal)
    Public Property bitDocDaGenerare As Boolean
    Public Property bitEsportato As Boolean
    Public Property bitEsportatoFallito As Boolean

    Public Overridable Property Anag_Articoli As Anag_Articoli

End Class
