'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TransazioniBilanceRetail
    Public Property KeyId As Decimal
    Public Property intTipo As Decimal
    Public Property numEntita As Decimal
    Public Property intNumScontrino As Decimal
    Public Property intCodiceReparto As Integer
    Public Property dateDataOraTransazione As Date
    Public Property dateDataOraSalvataggio As Date
    Public Property intNumOperatore As Nullable(Of Integer)
    Public Property intNumBilancia As Nullable(Of Integer)
    Public Property bitStorno As Boolean
    Public Property intCodicePlu As Nullable(Of Integer)
    Public Property strArticoloUm As String
    Public Property intNumPezzi As Nullable(Of Integer)
    Public Property intPesoGrammi As Nullable(Of Integer)
    Public Property dblImporto As Nullable(Of Double)
    Public Property strDescrizionePlu As String
    Public Property strEan As String
    Public Property strNote As String
    Public Property strNuo As String
    Public Property bitTakeAway As Boolean
    Public Property bitProcessato As Boolean
    Public Property bitVenduto As Boolean
    Public Property dateDataOraVenduto As Nullable(Of Date)
    Public Property bitExportedToiCasher As Boolean
    Public Property bitEliminato As Boolean
    Public Property dateDataOraEliminazione As Nullable(Of Date)
    Public Property bitProcessataEliminazione As Boolean
    Public Property bitRiconfezionato As Boolean
    Public Property KeyIdLavorazioniFasi_Confezionamenti As Nullable(Of Decimal)

End Class
