'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TrasferimentoInterno
    Public Property KeyId As Decimal
    Public Property KeyIdOrdini As Nullable(Of Decimal)
    Public Property KeyIdMittenteAnag_Magazzini As Decimal
    Public Property KeyIdDestinatarioAnag_Magazzini As Decimal
    Public Property dateDataOperazione As Date
    Public Property KeyIdAnag_Operatori As Decimal
    Public Property intStato As Short
    Public Property bitEsportato As Boolean

    Public Overridable Property Anag_Magazzini As Anag_Magazzini
    Public Overridable Property Anag_Magazzini1 As Anag_Magazzini
    Public Overridable Property Anag_Operatori As Anag_Operatori
    Public Overridable Property Ordini As Ordini
    Public Overridable Property TrasferimentoInterno_Dettagli As ICollection(Of TrasferimentoInterno_Dettagli) = New HashSet(Of TrasferimentoInterno_Dettagli)

End Class
