'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TrasferimentoInterno_Dettagli
    Public Property KeyId As Decimal
    Public Property KeyIdTrasferimentoInterno As Decimal
    Public Property KeyIdOrdini_Dettagli As Nullable(Of Decimal)
    Public Property strNuo As String
    Public Property KeyIdAnag_Articoli As Decimal
    Public Property KeyIdAnag_Um As Decimal
    Public Property dblQuantita As Double
    Public Property KeyIdTracciabilitaAddizionale As Decimal
    Public Property intTipoTrasferimento As Short
    Public Property dblQuantitaRicevuta As Nullable(Of Double)

    Public Overridable Property Anag_Articoli As Anag_Articoli
    Public Overridable Property Anag_Um As Anag_Um
    Public Overridable Property Ordini_Dettagli As Ordini_Dettagli
    Public Overridable Property TracciabilitaAddizionale As TracciabilitaAddizionale
    Public Overridable Property TrasferimentoInterno As TrasferimentoInterno

End Class
