'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UltimaTracciabilita
    Public Property KeyId As Decimal
    Public Property KeyIdMaschereTr As Nullable(Of Decimal)
    Public Property KeyIdTracciabilitaAddizionale As Nullable(Of Decimal)
    Public Property dateDataOra As Nullable(Of Date)

End Class
