'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UltimiFornitori
    Public Property KeyId As Decimal
    Public Property KeyIdAnag_Fornitori As Nullable(Of Decimal)
    Public Property KeyIdAnag_Postazioni As Nullable(Of Decimal)
    Public Property dateDataOra As Nullable(Of Date)

End Class
